---
title: "Beste Boeken 2019"
description: |
  A short description of the post.
author:
  - name: Harrie Jonkman
    url: www.harriejonkman.nl
date: 12-15-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


**Beste boeken van 2019** 

December is de maand van de lijstjes. Net als vele anderen maak ik dan jaarlijstje met, in mijn geval, de beste films, de beste cd's en de beste boeken. Hier nu ook zo'n lijstje met beste boeken van 2019, maar dan statistische boeken. Op dit terrein verschijnt bijzonder veel en ik wil niet zeggen dat ik op dit terrein alles overzie. Maar hieronder de vijf boeken die mij afgelopen jaar het meeste aanspraken en die ik er nog steeds regelmatig op na sla.

1. Kieran Healey, *Data visualization: a practical introduction*

Dit is een boek over data visualisatie en met name het R-pakket *ggplot*.  Hier (https://kieranhealy.org/publications/dataviz/,) vind je er informatie over. Het is bijzonder duidelijk geschreven. Aan de hand van het maken van figuren, grafieken en kaarten leer je heel goed met R en RStudio om te gaan. Lees dit boek aandachtig en maak de kaarten zelf die Kieran Healey in dit boek maakt. Het boek is met plezier en gemak geschreven. Ik schreef er eerder een kort stukje over ().

2. Robin Lovelace, Jakob Novosad en Jannes Muenchow, *Geocomputation with R*

Dat boek vind je hier (https://kieranhealy.org/publications/dataviz/). Deze drie wetenschappers hebben in twee, drie jaar dit boek geschreven over het maken van geografische kaarten. De theorie en de praktijk worden heel goed door deze drie jonge wetenschappers besproken. Op internet kun je hun syntaxen vinden en verschillende presentaties die ze hierover hebben gegeven. R is een gratis programma dat tegenwoordig de concurrentie aan kan met dure GIS-programma's. Net als het boek van Healey is ook dit boek met plezier en gemak geschreven en het boek duwt je in de tijd vooruit. Ook over dit boek schreef ik eerder een blog (). 

3. Rafael Irizarry, *Introduction to Data Science. Data Analysis and Prediction Algorithms with R*

Rafael Irizarry is epidemioloog van de Harvard University en geeft uitgebreide collegereeksen over moderne data-analyse. Als ik begin 20 zou zijn en waar ook een cursus mocht uitzoeken zou ik misschien wel zijn cursus uit hebben gekozen. Op basis van de introductiecursus gaf hij dit open-source boek uit (https://kieranhealy.org/publications/dataviz/). Hij laat zien hoe je data analyse uitvoert en wat er bij komt kijken aan voorbereiden, opschonen, visualiseren, modelleren en communiceren. Hij heeft aandacht voor standaard statistiek maar ook voor waarschijnlijkheidsleer en machinelearning. Daarnaast besteedt hij aandacht aan allerlei aanvullende zaken die hierbij om de hoek komen kijken als het gebruik van GitHUB, basis computerkennis en reproduceerbaar onderzoek. Een heel goed studieboek over moderne data-analyse in deze tijd.

4. Danielle Navarro, *Learning Statistics with R*

Danielle Navarro geeft al jarenlang statistiek aan studenten psychologie van de Universiteit van Adeleide (Australië). Zij heeft haar boek dat ze hierbij gebruikt ook toegankelijk gemaakt voor anderen en je vindt het hier (https://learningstatisticswithr.com/). Dat las ik tegen het einde van het jaar. Verschillende aspecten van de statistiek worden uitgelegd en als je dit boek hebt doorgewerkt, kun je goed artikelen begrijpen en ook analyses uitvoeren. Daarnaast besteedt zij aandacht aan Bayesiaanse statistiek. Deze vorm van statistiek ligt haar beter en aan het einde legt zij heel goed uit hoe dit werkt. Dat hoofdstuk heb ik hier vertaald ()

5. Russel Poldrock, *Statistical Thinking for the 21st Century*

Dit is het boek dat ik recent las en dat mij bijzonder aanspreekt. Het is een heerlijk tegendraads boek van iemand die les geeft over statistiek en niet tevreden was met het studieboek dat hij gebruikte. Dat kon hij beter. Hij is een Bayesiaan en bouwt zijn boek vanuit dit raamwerk op. Voor hem is deze vorm van statistiek de statistiek van deze eeuw. Verschillende aspecten die je in gewone statistiek boeken tegenkomt, bespreek hij ook maar dan vanuit dat 21eeuwse perspectief. Net als de andere boeken laat hij ook zien hoe je dit het allemaal uitvoert (zowel het schrijven met wiskundige tekens, tabellen maken als de modellen maken). Bijzonder leerzaam en dit boek zal ik er nog vaak op naslaan. Dit boek vind je hier (http://statsthinking21.org/