<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.345">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JoonHo Lee, Nicholas Sim, Feng Ji, and Sophia Rabe-Hesketh, vertaling HarrieJonkman">
<meta name="dcterms.date" content="2022-02-06">
<meta name="description" content="Introductie op multilevel modelleren met gebruik van rstanarm: Een tutorial voor onderwijsonderzoekers">

<title>Harrie’s Hoekje - Multilevel modeling met STAN</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Harrie’s Hoekje</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">Harrie’s Hoekje</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Jonkman1"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Multilevel modeling met STAN</h1>
                          <div class="quarto-categories">
                <div class="quarto-category">analyse</div>
              </div>
                  </div>
  </div>
    
  <div>
    <div class="description">
      <p>Introductie op multilevel modelleren met gebruik van <strong>rstanarm</strong>: Een tutorial voor onderwijsonderzoekers</p>
    </div>
  </div>




  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>JoonHo Lee, Nicholas Sim, Feng Ji, and Sophia Rabe-Hesketh, vertaling HarrieJonkman </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 6, 2022</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<div class="cell">

</div>
<blockquote class="blockquote">
<p>Een paar jaar geleden schreven Joonho Lee en collega’s van de Berkley Universiteit onder leiding van Sophia Rabe-Hesketh (van wie ik al eerder veel geleerd heb over multilevel analyse) een mooie tutorial over het gebruik van <strong>rstanarm</strong> in multilevelanalyse. Omdat deze tutorial in vele opzichten leerzaam is, heb ik deze vertaald. Zo maakte ik mij het werken met rstanarm eigen maar ook hoe je zo’n tutorial in rmarkdown zet. Alle credits gaan natuurlijk naar Joonhoo Lee e.a.. De oorspronkelijke tutorial van 24 april 2018 vind je <a href="https://mc-stan.org/users/documentation/case-studies/tutorial_rstanarm.html">hier</a>. Later vond ik ook op github de syntax en kon ik diverse eigen fouten weer bijstellen <a href="https://github.com/stan-dev/example-models/blob/master/education/tutorial_rstanarm/tutorial_rstanarm.Rmd">hier</a>.</p>
</blockquote>
<section id="introductie" class="level1">
<h1>Introductie</h1>
<p>Een veel voorkomend kenmerk van datastructuren in het onderwijs is dat analyse-eenheden (b.v. leerlingen) genest zijn in hogere organisatorische clusters (b.v. scholen). Dit soort structuren leidt tot afhankelijkheid tussen de antwoorden die worden waargenomen voor eenheden binnen dezelfde cluster. Leerlingen in dezelfde school hebben in het algemeen de neiging meer gelijkenissen te vertonen in hun academische en attitudinale kenmerken dan leerlingen die willekeurig uit de bevolking worden gekozen.</p>
<p><em>Multilevel modellen</em>1 zijn ontworpen om dergelijke afhankelijkheid binnen clusters te modelleren. Multilevelmodellen erkennen het bestaan van gegevensclustering (op twee of meer niveaus) door residuele componenten op elk niveau in de hiërarchie toe te staan. Bijvoorbeeld, een model met twee niveaus dat de groepering van leerlingresultaten binnen scholen toelaat, zou residuen op zowel leerling- als schoolniveau omvatten. De residuele variantie wordt dan verdeeld in een tussen-school component (de variantie van de residuen op schoolniveau) en een binnen-school component (de variantie van de residuen op leerlingniveau).</p>
<p>In deze tutorial laten Joonhoo Lee en collega’s zien hoe je een multilevel lineair model kunt fitten binnen een volledig Bayesiaans raamwerk met <strong>rstanarm</strong>. Deze handleiding is in de eerste plaats gericht op onderwijsonderzoekers die <strong>lme4</strong> in <strong>R</strong> hebben gebruikt om modellen te fitten op hun gegevens en die mogelijk geïnteresseerd zijn in het leren fitten van Bayesiaanse multilevel modellen. Voor lezers die <strong>lme4</strong> nog niet eerder hebben gebruikt, geven we echter een kort overzicht van het gebruik van het pakket voor het fitten van multilevel modellen.</p>
<p>Deze tutorial maakt gebruik van <strong>Stan</strong> versie 2.17.3 en vereist de volgende <strong>R</strong> pakketten.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pakketten die nodig zijn</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlmRev)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstanarm)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="data-voorbeeld" class="level2">
<h2 class="anchored" data-anchor-id="data-voorbeeld">Data voorbeeld</h2>
<p>Ze analyseren de Gcsemv dataset (Rasbash et al.&nbsp;2000) uit het <strong>mlmRev</strong> pakket in <strong>R</strong>. De gegevens omvatten de GCSE-examenscores (General Certificate of Secondary Education) van 1.905 leerlingen van 73 scholen in Engeland op een natuurwetenschappelijk vak. De Gcsemv-dataset bestaat uit de volgende 5 variabelen:</p>
<ul>
<li><em>school</em>: schoolidentificatiecode<br>
</li>
<li><em>student</em>: identificatiecode student<br>
</li>
<li><em>gender</em>: geslacht van een leerling (M: Man, F: Vrouw)<br>
</li>
<li><em>written</em>: totaalscore op schriftelijk werkstuk</li>
<li><em>course</em>: totaalscore op schriftelijk werkstuk</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use example dataset from mlmRev package: GCSE exam score</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Gcsemv, <span class="at">package =</span> <span class="st">"mlmRev"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(Gcsemv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     school        student     gender      written          course      
 68137  : 104   77     :  14   F:1128   Min.   : 0.60   Min.   :  9.25  
 68411  :  84   83     :  14   M: 777   1st Qu.:37.00   1st Qu.: 62.90  
 68107  :  79   53     :  13            Median :46.00   Median : 75.90  
 68809  :  73   66     :  13            Mean   :46.37   Mean   : 73.39  
 22520  :  65   27     :  12            3rd Qu.:55.00   3rd Qu.: 86.10  
 60457  :  54   110    :  12            Max.   :90.00   Max.   :100.00  
 (Other):1446   (Other):1827            NA's   :202     NA's   :180     </code></pre>
</div>
</div>
<p>Twee onderdelen van het examen werden geregistreerd als uitkomstvariabelen: schriftelijk werkstuk (<strong>written</strong>) en cursuswerkstuk (<strong>course</strong>). In deze tutorial wordt alleen de totaalscore op het cursuswerkstuk (<em>course</em>) geanalyseerd. Zoals hierboven te zien is, ontbreken er bij sommige waarnemingen waarden voor bepaalde covariaten. Hoewel we de data niet subsetten om alleen volledige gevallen op te nemen om aan te tonen dat <strong>rstanarm</strong> deze waarnemingen automatisch laat vallen, is het over het algemeen een goed gebruik om dit handmatig te doen indien nodig.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Maak Male dereferentiecategorie en hernoem de variabele</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Gcsemv<span class="sc">$</span>female <span class="ot">&lt;-</span> <span class="fu">relevel</span>(Gcsemv<span class="sc">$</span>gender, <span class="st">"M"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Gebruik alleen de totaalscore op course </span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>GCSE <span class="ot">&lt;-</span> <span class="fu">subset</span>(<span class="at">x =</span> Gcsemv, </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">select =</span> <span class="fu">c</span>(school, student, female, course))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Tel unieke scholen en studenten</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>J <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(GCSE<span class="sc">$</span>school))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(GCSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Het pakket <strong>rstanarm</strong> automatiseert verschillende stappen van datavoorbewerking, waardoor het gebruik ervan sterk lijkt op dat van <strong>lme4</strong> en wel op de volgende manier.</p>
<ul>
<li><p><em>Input</em> - <strong>rstanarm</strong> kan een dataframe als input nemen2.</p></li>
<li><p><em>Ontbrekende gegevens</em> - <strong>rstanarm</strong> verwijdert automatisch waarnemingen met NA waarden voor elke variabele gebruikt in het model3.</p></li>
<li><p><em>Identifiers</em> - <strong>rstanarm</strong> vereist niet dat identifiers opeenvolgend zijn4. We stellen voor dat het een goede gewoonte is om alle cluster- en unit-identifiers, evenals categorische variabelen als factoren op te slaan. Dit geldt evenzeer voor <strong>lme4</strong> als voor <strong>rstanarm</strong>. Men kan de structuur van de variabelen controleren met behulp van de <code>str()</code> functie.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check structure of data frame</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(GCSE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1905 obs. of  4 variables:
 $ school : Factor w/ 73 levels "20920","22520",..: 1 1 1 1 1 1 1 1 1 2 ...
 $ student: Factor w/ 649 levels "1","2","3","4",..: 16 25 27 31 42 62 101 113 146 1 ...
 $ female : Factor w/ 2 levels "M","F": 1 2 2 2 1 2 2 1 1 2 ...
 $ course : num  NA 71.2 76.8 87.9 44.4 NA 89.8 17.5 32.4 84.2 ...</code></pre>
</div>
</div>
</section>
</section>
<section id="likelihood-inferentie-met-lmer" class="level1">
<h1>Likelihood inferentie met <code>lmer()</code></h1>
<p>In dit deel bespreken we kort drie lineaire multilevelmodellen die in deze tutorial zullen worden toegepast. We beginnen met een variërend intercept model zonder voorspellers (Model 1), dan gaan we verder met het variërend intercept model met één voorspeller (Model 2), en het variërend intercept en helling model (Model 3).</p>
<section id="model-1-variërend-intercept-model-zonder-voorspellers-variantiecomponentenmodel" class="level2">
<h2 class="anchored" data-anchor-id="model-1-variërend-intercept-model-zonder-voorspellers-variantiecomponentenmodel">Model 1: Variërend intercept model zonder voorspellers (Variantiecomponentenmodel)</h2>
<p>Beschouw het eenvoudigste multilevel model voor leerlingen <span class="math inline">\(i=1,...,n\)</span> genest binnen scholen <span class="math inline">\(j=1,...,J\)</span> en voor wie we examenresultaten als respons hebben. We kunnen een variabel interceptmodel met twee niveaus zonder voorspellers schrijven met de gebruikelijke tweedelige formulering als</p>
<p><span class="math display">\[Y_{ij}=\alpha_{j} + \epsilon_{ij}, \text{ where } \epsilon{ij} \sim N(0,\sigma^2_{y}) \]</span> <span class="math display">\[\alpha{_j}=u_{\alpha} + u_{j}, \text { where } \epsilon{ij} \sim N(0,\sigma^2_{y})\]</span></p>
<p>waarin <span class="math inline">\(yij\)</span> de examenscore is voor de <span class="math inline">\(ith\)</span> leerling op de <span class="math inline">\(jth\)</span> school, <span class="math inline">\(\alpha_{j}\)</span> de variërende intercept voor de jde school, en <span class="math inline">\(u_{a}\)</span> het algemene gemiddelde voor alle scholen. Als alternatief kan het model in verkorte vorm worden uitgedrukt als</p>
<p><span class="math display">\[y_{ij}=u_{a} + u_{j} = \epsilon_{ij}\]</span> Als we verder aannemen dat de fouten op leerlingniveau <span class="math inline">\(\epsilon_{ij}\)</span> normaal verdeeld zijn met gemiddelde 0 en variantie <span class="math inline">\(\sigma^2_{y}\)</span>, en dat de variërende intercepten op schoolniveau <span class="math inline">\(\alpha_j\)</span> normaal verdeeld zijn met gemiddelde <span class="math inline">\(u_{a}\)</span> en variantie <span class="math inline">\(\sigma^2_{a}\)</span>, dan kan het model worden uitgedrukt als</p>
<p><span class="math display">\[y_{ij}∼ N(\alpha_{j},\sigma^2_{y})\]</span></p>
<p><span class="math display">\[a_{j}∼ N(u_{a},\sigma^2_{a})\]</span></p>
<p>Dit model kan dan worden aangepast met <code>lmer()</code>. We specificeren een intercept (de voorspeller “1”) en laten deze variëren met de niveau-2-identifier (<em>school</em>). We specificeren ook de <code>REML = FALSE</code> optie om maximum likelihood (ML) schattingen te krijgen in plaats van de standaard restricted maximum likelihood (REML) schattingen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school), </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> GCSE, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: course ~ 1 + (1 | school)
   Data: GCSE

     AIC      BIC   logLik deviance df.resid 
 14111.4  14127.7  -7052.7  14105.4     1722 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.9693 -0.5101  0.1116  0.6741  2.7613 

Random effects:
 Groups   Name        Variance Std.Dev.
 school   (Intercept)  75.24    8.674  
 Residual             190.77   13.812  
Number of obs: 1725, groups:  school, 73

Fixed effects:
            Estimate Std. Error t value
(Intercept)    73.72       1.11    66.4</code></pre>
</div>
</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Onder <code>Fixed effects</code> zien we dat het intercept <span class="math inline">\(u_{a}\)</span>, gemiddeld over de populatie van scholen, wordt geschat op 73,72. Onder <code>Random-effects</code> zien we dat de standaardafwijking tussen de scholen <span class="math inline">\(\sigma_{a}\)</span> wordt geschat op <span class="math inline">\(8.67\)</span> en de standaardafwijking binnen de scholen <span class="math inline">\(\sigma_{y}\)</span> op <span class="math inline">\(13.81\)</span>.</p>
</section>
<section id="model-2-variërend-intercept-model-met-een-enkele-voorspeller" class="level2">
<h2 class="anchored" data-anchor-id="model-2-variërend-intercept-model-met-een-enkele-voorspeller">Model 2: Variërend intercept model met een enkele voorspeller</h2>
<p>Het variërende interceptmodel5 met een indicatorvariabele voor het vrouwzijn xij kan worden geschreven als</p>
<p><span class="math display">\[Y_{ij}∼N(a_{j}+\beta x{ij}, \sigma^2_{y}),\]</span></p>
<p><span class="math display">\[a_{j}∼N(u_{a}, \sigma^2_{a})\]</span>.</p>
<p>De vergelijking van de gemiddelde regressielijn voor alle scholen is <span class="math inline">\(u_{ij}=u_{α}+βxij\)</span>. De regressielijnen voor specifieke scholen zullen evenwijdig zijn aan de gemiddelde regressielijn (met dezelfde helling β), maar verschillen wat betreft het intercept <span class="math inline">\(a_{j}\)</span>. Dit model kan geschat worden door vrouwelijk toe te voegen aan de formule in de <code>lmer()</code> functie, waardoor alleen het intercept per school varieert en de “helling” voor vrouwelijkheid constant blijft voor alle scholen</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> female <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school), </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> GCSE, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: course ~ 1 + female + (1 | school)
   Data: GCSE

     AIC      BIC   logLik deviance df.resid 
 14017.4  14039.2  -7004.7  14009.4     1721 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.7809 -0.5401  0.1259  0.6795  2.6753 

Random effects:
 Groups   Name        Variance Std.Dev.
 school   (Intercept)  76.65    8.755  
 Residual             179.96   13.415  
Number of obs: 1725, groups:  school, 73

Fixed effects:
            Estimate Std. Error t value
(Intercept)   69.730      1.185   58.87
femaleF        6.739      0.678    9.94

Correlation of Fixed Effects:
        (Intr)
femaleF -0.338</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>De gemiddelde regressielijn over de scholen wordt dus geschat als <span class="math inline">\(\hat{\mu}_{ij}=69.73+ 6.74 x_{ij}\)</span>, waarbij <span class="math inline">\(\sigma_\_alpha\)</span> en <span class="math inline">\(\sigma_y\)</span> worden geschat als respectievelijk <span class="math inline">\(8.76\)</span> en <span class="math inline">\(13.41\)</span>. Als we deze schattingen van <span class="math inline">\(\mu_alpha\)</span>, <span class="math inline">\(\beta\)</span>, <span class="math inline">\(\sigma^2_{y}\)</span>, en <span class="math inline">\(\sigma^2_{alpha}\)</span> als de ware parameterwaarden beschouwen, kunnen we de **Best Linear Unbiased Predictions (BLUPs) voor de fouten op schoolniveau <span class="math inline">\(\hat{u}_j = \hat{\alpha}_{j} - \hat{\mu}_{\alpha}\)</span> verkrijgen.</p>
<p>De BLUPs zijn equivalent met de zogenaamde <strong>Empirical Bayes</strong> (EB)-voorspelling, die het gemiddelde is van de posterieure verdeling van <span class="math inline">\(u_{j}\)</span> gegeven alle geschatte parameters, alsmede de willekeurige variabelen <span class="math inline">\(y_{ij}\)</span> en <span class="math inline">\(x_{ij}\)</span> voor het cluster. Deze voorspellingen worden “Bayes” genoemd omdat ze gebruik maken van de vooraf gespecificeerde prioriteitsverdeling<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> <span class="math inline">\(u_j \sim N(\mu_\alpha, \sigma^2_\alpha)\)</span>, en bij uitbreiding <span class="math inline">\(u_j \sim N(0, \sigma^2_\alpha)\)</span>, en “Empirisch” genoemd omdat de parameters van deze prior, <span class="math inline">\(\mu_\alpha\)</span> en <span class="math inline">\(\sigma^2_{\alpha}\)</span>, naast <span class="math inline">\(\beta\)</span> en <span class="math inline">\(\sigma^2_{y}\)</span>, geschat worden uit de data.</p>
<p>In vergelijking met de ML-benadering (Maximum Likelihood - maximale waarschijnlijkheid), waarbij waarden voor <span class="math inline">\(u_j\)</span> worden voorspeld door alleen de geschatte parameters en gegevens van cluster <span class="math inline">\(j\)</span> te gebruiken, houdt de EB-benadering bovendien rekening met de voorafgaande verdeling van <span class="math inline">\(u_{j}\)</span>, en levert zij voorspelde waarden op die dichter bij <span class="math inline">\(0\)</span> liggen (een verschijnsel dat wordt beschreven als <em>shrinkage</em> of <em>partial pooling</em>). Om te zien waarom dit verschijnsel <em>shrinkage</em> wordt genoemd, drukken we de uit EB voorspelling verkregen schattingen voor <span class="math inline">\(u_j\)</span> gewoonlijk uit als <span class="math inline">\(\hat{u}_j^{text{EB}} = \hat{R}_j\hat{u}_j^{\text{ML}}\)</span> waarbij <span class="math inline">\(\hat{u}_j^{\text{ML}}\)</span> de ML schattingen zijn, en <span class="math inline">\(\hat{R}_j = \frac{\sigma_alpha^2}{n_j}\)</span> de zogenaamde Shrinkage factor is.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">ranef</span>(M2)<span class="sc">$</span>school)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      (Intercept)
20920 -10.1702110
22520 -17.0578149
22710   7.8007260
22738   0.4871012
22908  -8.1940346
23208   4.4304453</code></pre>
</div>
</div>
<p>Deze waarden schatten hoeveel het intercept naar boven of beneden verschoven is in bepaalde scholen. Bijvoorbeeld, in de eerste school in de dataset is het geschatte intercept ongeveer 10.17 lager dan gemiddeld, zodat de schoolspecifieke regressielijn <span class="math inline">\((69.73 - 10.17) + 6.74 x_{ij}\)</span> is.</p>
<p>Gelman&amp;Hill (2006) karakteriseren multilevel modellering als <em>partial pooling</em> (ook wel <em>shrinkage</em> genoemd), wat een compromis is tussen twee uitersten: <em>complete pooling</em>, waarbij de clustering helemaal niet in het model wordt meegenomen, en <em>no pooling</em>, waarbij voor elke school aparte intercepten worden geschat als coëfficiënten van dummy-variabelen. De geschatte schoolspecifieke regressielijnen in het bovenstaande model zijn gebaseerd op <em>partial pooling</em> schattingen. Om dit aan te tonen, schatten we eerst de intercept en de helling voor elke school op drie manieren:</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Complete-pooling regression</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pooled <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> course <span class="sc">~</span> female,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> GCSE)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>a_pooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(pooled)[<span class="dv">1</span>]   <span class="co"># complete-pooling intercept</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>b_pooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(pooled)[<span class="dv">2</span>]   <span class="co"># complete-pooling slope</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># No-pooling regression</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>nopooled <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> course <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> school <span class="sc">+</span> female,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> GCSE)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>a_nopooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(nopooled)[<span class="dv">1</span><span class="sc">:</span>J]   <span class="co"># 73 no-pooling intercepts              </span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>b_nopooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(nopooled)[J<span class="sc">+</span><span class="dv">1</span>]</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Partial pooling (multilevel) regression</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>a_part_pooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(M2)<span class="sc">$</span>school[, <span class="dv">1</span>]</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>b_part_pooled <span class="ot">&lt;-</span> <span class="fu">coef</span>(M2)<span class="sc">$</span>school[, <span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vervolgens plotten we de gegevens en schoolspecifieke regressielijnen voor een selectie van acht scholen met behulp van de volgende commando’s.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>:</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># (0) Assen plaatsen &amp; scholen kiezen</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> GCSE<span class="sc">$</span>course</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(GCSE<span class="sc">$</span>female) <span class="sc">-</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(N, <span class="sc">-</span>.<span class="dv">05</span>, .<span class="dv">05</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>schid <span class="ot">&lt;-</span> GCSE<span class="sc">$</span>school</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>sel.sch <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"65385"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>             <span class="st">"68207"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>             <span class="st">"60729"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>             <span class="st">"67051"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>             <span class="st">"50631"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>             <span class="st">"60427"</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>             <span class="st">"64321"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>             <span class="st">"68137"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># (1) Subset 8 van de scholen; genereer data frame</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(y, x, schid)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>df8 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, schid <span class="sc">%in%</span> sel.sch)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a><span class="co"># (2) Aangeven van schattingen van volledige-pooling, geen-pooling, gedeeltelijke pooling </span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>a_pooled <span class="ot">&lt;-</span> a_pooled </span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>b_pooled <span class="ot">&lt;-</span> b_pooled</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>a_nopooled <span class="ot">&lt;-</span> a_nopooled[df8<span class="sc">$</span>schid]</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>b_nopooled <span class="ot">&lt;-</span> b_nopooled</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>a_part_pooled <span class="ot">&lt;-</span> a_part_pooled[df8<span class="sc">$</span>schid]</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>df8<span class="sc">$</span>b_part_pooled <span class="ot">&lt;-</span> b_part_pooled[df8<span class="sc">$</span>schid]</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="co"># (3) Plot van hoe regressie fit voor de 8 scholen</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df8, </span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span> </span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="at">facets =</span> <span class="sc">~</span> schid, </span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>             <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> .<span class="dv">05</span>, </span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> a_pooled, </span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>                  <span class="at">slope =</span> b_pooled), </span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"solid"</span>, </span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"blue"</span>, </span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> a_nopooled, </span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>                  <span class="at">slope =</span> b_nopooled), </span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"longdash"</span>, </span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> a_part_pooled, </span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a>                  <span class="at">slope =</span> b_part_pooled), </span>
<span id="cb14-46"><a href="#cb14-46" aria-hidden="true" tabindex="-1"></a>              <span class="at">linetype =</span> <span class="st">"dotted"</span>, </span>
<span id="cb14-47"><a href="#cb14-47" aria-hidden="true" tabindex="-1"></a>              <span class="at">color =</span> <span class="st">"purple"</span>, </span>
<span id="cb14-48"><a href="#cb14-48" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb14-49"><a href="#cb14-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), </span>
<span id="cb14-50"><a href="#cb14-50" aria-hidden="true" tabindex="-1"></a>                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"male"</span>, <span class="st">"female"</span>)) <span class="sc">+</span> </span>
<span id="cb14-51"><a href="#cb14-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Schatting van Volledige-pooling, Geen-pooling en Gedeeltelijke pooling"</span>,</span>
<span id="cb14-52"><a href="#cb14-52" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, </span>
<span id="cb14-53"><a href="#cb14-53" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Totale score op cursuswerk paper"</span>)<span class="sc">+</span><span class="fu">theme_bw</span>( <span class="at">base_family =</span> <span class="st">"serif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="multilevelrstan_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="528"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">De blauw-gestreepte, rood-gestreepte en paars-gestippelde lijnen geven respectievelijk de volledige pooling, no-pooling en gedeeltelijke pooling schattingen weer. We zien dat de geschatte schoolspecifieke regressielijn van de gedeeltelijke pooling-schattingen tussen de volledige pooling- en de geenpooling-regressielijn ligt. Er is meer pooling (paarse stippellijn dichter bij blauwe ononderbroken lijn) op scholen met een kleine steekproefomvang.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-3-variërend-intercept-en-slope-model-met-een-enkele-voorspeller" class="level2">
<h2 class="anchored" data-anchor-id="model-3-variërend-intercept-en-slope-model-met-een-enkele-voorspeller">Model 3: Variërend intercept en slope model met een enkele voorspeller</h2>
<p>We breiden nu het variërende interceptmodel met één voorspeller uit om zowel het intercept als de helling willekeurig te laten variëren tussen scholen met behulp van het volgende model <span class="math display">\[y_{ij} = \alpha_j + \beta_j x_{ij} +\epsilon_{ij},\]</span> <span class="math display">\[\alpha_j = \mu_\alpha + u_j,\]</span> <span class="math display">\[\beta_j = \mu_\beta + v_j,\]</span> or in a reduced form as <span class="math display">\[y_{ij} = \mu_\alpha + \mu_\beta x_{ij} + u_j + v_j x_{ij} + \epsilon_{ij}\]</span> where <span class="math inline">\(\epsilon_{ij} \sim N(0, \sigma_{y}^{2})\)</span> and <span class="math inline">\(\left( \begin{matrix} u_j \\ v_j \end{matrix} \right) \sim N\left( \left( \begin{matrix} 0 \\ 0 \end{matrix} \right) ,\left( \begin{matrix} { \sigma }_{ \alpha }^{ 2 } &amp; \rho { \sigma }_{ \alpha }{ \sigma }_{ \beta } \\ \rho { \sigma }_{ \alpha }{ \sigma }_{ \beta } &amp; { \sigma }_{ \beta }^{ 2 } \end{matrix} \right) \right)\)</span>.]:</p>
<p><span class="math display">\[y_{ij}\sim N(\alpha_{j}+\beta_{j}x_{ij} , \sigma_y ^2 ),\]</span> <span class="math display">\[\left( \begin{matrix} \alpha _{ j } \\ \beta _{ j } \end{matrix} \right) \sim N\left( \left( \begin{matrix} { \mu  }_{ \alpha  } \\ { \mu  }_{ \beta  } \end{matrix} \right) , \left( \begin{matrix} { \sigma  }_{ \alpha  }^{ 2 } &amp; \rho { \sigma  }_{ \alpha  }{ \sigma  }_{ \beta  } \\ \rho { \sigma  }_{ \alpha  }{ \sigma  }_{ \beta  } &amp; { \sigma  }_{ \beta  }^{ 2 } \end{matrix} \right)  \right).\]</span></p>
<p>Merk op dat we nu variatie hebben in de <span class="math inline">\(\alpha_{j}\)</span>’s en de <span class="math inline">\(\beta_{j}\)</span>’s, en ook een correlatie parameter <span class="math inline">\(\rho\)</span> tussen <span class="math inline">\(\alpha_{j}\)</span> en <span class="math inline">\(\beta_{j}\)</span>. Dit model kan gefit worden met gebruik van <code>lmer()</code> en wel als volgt:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>M3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> female <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> female <span class="sc">|</span> school), </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> GCSE, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">REML =</span> <span class="cn">FALSE</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M3) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood  ['lmerMod']
Formula: course ~ 1 + female + (1 + female | school)
   Data: GCSE

     AIC      BIC   logLik deviance df.resid 
 13983.4  14016.2  -6985.7  13971.4     1719 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-4.6886 -0.5222  0.1261  0.6529  2.6729 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 school   (Intercept) 102.93   10.146        
          femaleF      47.94    6.924   -0.52
 Residual             169.79   13.030        
Number of obs: 1725, groups:  school, 73

Fixed effects:
            Estimate Std. Error t value
(Intercept)   69.425      1.352  51.338
femaleF        7.128      1.131   6.302

Correlation of Fixed Effects:
        (Intr)
femaleF -0.574</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>In dit model wordt de residuele standaardafwijking binnen de school geschat als <span class="math inline">\(\hat{\sigma}_{y}=\)</span> 13.03. De geschatte standaardafwijkingen van de schoolintercepten en de schoolhellingen zijn respectievelijk <span class="math inline">\(\hat{\sigma}_{\alpha}= 10.15\)</span> en <span class="math inline">\(\hat{\sigma}_{\beta}= 6.92\)</span>. De geschatte correlatie tussen variërende intercepts en hellingen is <span class="math inline">\(\hat{\rho} = -0.52\)</span>. We kunnen een soortgelijke code als die in paragraaf 2.2 gebruiken om de gegevens en de schoolspecifieke regressielijnen voor een selectie van acht scholen te plotten.</p>
<div class="cell" data-fig.margin="true">
<div class="cell-output-display">
<p><img src="multilevelrstan_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="480"></p>
</div>
</div>
</section>
</section>
<section id="bayesiaanse-inferentie-voor-model-1" class="level1">
<h1>Bayesiaanse inferentie voor Model 1</h1>
<p>We kunnen snel en eenvoudig veel multilevel modellen fitten met behulp van de <code>lmer()</code> functie in <strong>R</strong>. Zoals eerder vermeld, zijn functies zoals <code>lmer()</code> gebaseerd op een combinatie van maximale waarschijnlijkheid (ML) schatting van de model parameters en empirische Bayes (EB) voorspellingen van de variërende intercepts en/of hellingen. In sommige gevallen, wanneer het aantal groepen klein is of wanneer het model veel variërende coëfficiënten of niet-nested componenten bevat, kan de ML-benadering echter minder goed werken, ten dele omdat er misschien niet genoeg informatie is om de variantieparameters nauwkeurig te schatten. In dergelijke gevallen levert de Restricted Maximum Likelihood (REML) Estimation redelijker gevolgtrekkingen op.</p>
<p>Een volledig Bayesiaanse benadering levert ook in deze gevallen redelijke gevolgtrekkingen op, met als bijkomend voordeel dat bij de voorspelling van de variërende intercepten en hellingen rekening wordt gehouden met alle onzekerheid in de parameterschattingen en met de daarmee samenhangende onzekerheid. Dit is een van de vele redenen waarom men geïnteresseerd zou moeten zijn in volledig Bayesiaanse schattingen. Andere redenen worden besproken in paragraaf 3.4.3. Men kan beginnen met het snel fitten van vele specificaties bij het bouwen van een model met behulp van de <code>lmer()</code> functie, en dan gebruik maken van de flexibiliteit van een volledig Bayesiaanse benadering met <strong>rstanarm</strong> om simulaties te verkrijgen die de onzekerheid over coëfficiënten, voorspellingen en andere grootheden die van belang zijn samenvatten.</p>
<p>In dit gedeelte laten we zien hoe model 1 kan worden ingepast en geëvalueerd met behulp van het pakket <strong>rstanarm</strong>. Als alternatief, maar dat komt niet in deze tutorial aan de orde, kan men ook een handgeschreven programma maken in <strong>Stan</strong> en het uitvoeren met behulp van het <strong>rstan</strong> pakket.</p>
<section id="gebruik-van-het-rstanarm-pakket" class="level2">
<h2 class="anchored" data-anchor-id="gebruik-van-het-rstanarm-pakket">Gebruik van het rstanarm pakket</h2>
<p>Veel relatief eenvoudige modellen kunnen worden aangepast met behulp van het <strong>rstanarm</strong> pakket zonder enige code te schrijven in de <strong>Stan</strong> taal. Het <strong>rstanarm</strong> pakket is een “wrapper” voor het <strong>rstan</strong> pakket waarmee de meest gebruikte regressiemodellen kunnen worden geschat met behulp van Markov Chain Monte Carlo (MCMC) en toch kunnen worden gespecificeerd met de gebruikelijke R modelleersyntaxis. Onderwijs onderzoekers kunnen Bayesiaanse schatting gebruiken voor multilevel modellen met slechts minimale veranderingen in hun bestaande code met <code>lmer()</code>.</p>
<p>Bijvoorbeeld, Model 1 met standaard prior verdelingen voor <span class="math inline">\(\mu_{\alpha}\)</span>, <span class="math inline">\(\sigma_{\alpha}\)</span>, en <span class="math inline">\(\sigma_{y}\)</span> kan worden gespecificeerd met het <strong>rstanarm</strong> pakket door <code>stan_</code> toe te voegen aan de <code>lmer</code> aanroep:</p>
<div class="cell" data-hash="multilevelrstan_cache/html/unnamed-chunk-17_dd52ebc6c39b602b44846f829ca07f26">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>M1_stanlmer <span class="ot">&lt;-</span> <span class="fu">stan_lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school), </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> GCSE,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">seed =</span> <span class="dv">349</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Deze <code>stan_lmer()</code> functie is qua syntax gelijk aan <code>lmer()</code>, maar in plaats van een maximum likelihood schatting uit te voeren, wordt een Bayesiaanse schatting uitgevoerd via MCMC. Omdat elke stap in de MCMC schatting random trekkingen uit de parameter ruimte inhoudt, voegen we een seed optie toe om ervoor te zorgen dat <code>stan_lmer</code> elke keer dat de code wordt uitgevoerd, dezelfde resultaten geeft.</p>
</section>
<section id="prior-distributies" class="level2">
<h2 class="anchored" data-anchor-id="prior-distributies">Prior distributies</h2>
<p>Model 1 is een variabel interceptiemodel met normaal verdeelde leerlingresiduen en intercepten op schoolniveau: <span class="math inline">\(y_{ij} \sim N(\alpha_{j}, \sigma_{y}^{2}),\)</span> en <span class="math inline">\(\alpha_{j},\sim N(\mu_{alpha}, \sigma_{alpha}^{2})\)</span>. De normale verdeling voor de <span class="math inline">\(\alpha{j}\)</span>’s kan worden beschouwd als een prioriteitsverdeling voor deze variërende intercepten. De parameters van deze prior verdeling, <span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\sigma_{\alpha}\)</span>, worden geschat uit de gegevens bij gebruik van maximum likelihood schatting. Bij volledige Bayesiaanse inferentie hebben alle hyperparameters (<span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\sigma_{\alpha}\)</span>), samen met de andere niet-gemodelleerde parameters (in dit geval, <span class="math inline">\(\sigma_{y}\)</span>) ook een priorverdeling nodig.</p>
<p>Hier gebruiken we de standaard prior verdelingen voor de hyperparameters in <code>stan_lmer</code> door geen prior opties op te geven in <code>stan_lmer()</code> functie. De standaard priors zijn bedoeld als zwak informatief in de zin dat ze gematigde regularisatie bieden [Regularisatie kan worden beschouwd als een techniek om ervoor te zorgen dat schattingen binnen een acceptabel bereik van waarden worden begrensd] en helpen bij het stabiliseren van de berekening. Opgemerkt moet worden dat de auteurs van <strong>rstanarm</strong> suggereren om niet te vertrouwen op <strong>rstanarm</strong> om de standaard prior voor een model te specificeren, maar eerder om de priors expliciet te specificeren, zelfs als ze inderdaad de huidige standaard zijn, aangezien updates van het pakket andere defaults mee kunnen krijgen.</p>
<p>Ten eerste wordt, alvorens rekening te houden met de schaal van de variabelen, <span class="math inline">\(\mu_{alpha}\)</span> een normale priorverdeling gegeven met gemiddelde 0 en standaardafwijking 10. Dat wil zeggen, <span class="math inline">\(mu_{alpha} \sim N(0, 10^2)\)</span>. De standaardafwijking van deze prioriteitsverdeling, 10, is vijf keer zo groot als de standaardafwijking van de respons indien deze gestandaardiseerd zou zijn. Dit zou een dichte benadering moeten zijn van een niet-informatieve prior over het door de waarschijnlijkheid ondersteunde bereik, die in gevolgtrekkingen zou moeten geven die vergelijkbaar zijn met die verkregen met maximale waarschijnlijkheidsmethoden indien even zwakke priors worden gebruikt voor de andere parameters.</p>
<p>Ten tweede wordt de (ongeschaalde) prior voor <span class="math inline">\(\sigma_{y}\)</span> ingesteld op een exponentiële verdeling met de ‘rate’-parameter op 1.</p>
<p>Ten derde, om een prior voor de varianties en covarianties van de variërende (of “willekeurige”) effecten te specificeren, zal <strong>rstanarm</strong> deze matrix ontbinden in een correlatiematrix van de variërende effecten en een functie van hun varianties. Omdat er in dit voorbeeld slechts één variërend effect is, reduceert de standaard (ongeschaalde) prior voor <span class="math inline">\(\sigma_{\alpha}\)</span> die <strong>rstanarm</strong> gebruikt tot een exponentiële verdeling met de rate parameter op 1.</p>
<p>Ook moet worden opgemerkt dat <strong>rstanarm</strong> de priors zal schalen tenzij de <code>autoscale = FALSE</code> optie wordt gebruikt. Na het fitten van een model met <code>stan_lmer</code>, kunnen we de gebruikte priors controleren door de <code>prior_summary()</code> functie op te roepen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Een samenvatting krijgen van de priors die gebruikt worden </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">prior_summary</span>(<span class="at">object =</span> M1_stanlmer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Priors for model 'M1_stanlmer' 
------
Intercept (after predictors centered)
  Specified prior:
    ~ normal(location = 73, scale = 2.5)
  Adjusted prior:
    ~ normal(location = 73, scale = 41)

Auxiliary (sigma)
  Specified prior:
    ~ exponential(rate = 1)
  Adjusted prior:
    ~ exponential(rate = 0.061)

Covariance
 ~ decov(reg. = 1, conc. = 1, shape = 1, scale = 1)
------
See help('prior_summary.stanreg') for more details</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Hiermee krijgen we de SD van de uitkomst </span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(GCSE<span class="sc">$</span>course, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.32096</code></pre>
</div>
</div>
<p>Zoals hierboven te zien is, worden de schalen van de priors voor <span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\sigma_y\)</span> op respectievelijk <span class="math inline">\(163,21\)</span> en <span class="math inline">\(16,32\)</span> gezet na herschaling. Aangezien de standaard prior voor het intercept normaal is met een schaalparameter van <span class="math inline">\(10\)</span>, is de herschaalde prior ook normaal maar met een schaalparameter van <span class="math inline">\(\text{scale} \times \text{SD}(y) = 10 \times 16.321= 163.21\)</span>. Aangezien de standaard prior voor <span class="math inline">\(\sigma_y\)</span> exponentieel is met een snelheidsparameter van <span class="math inline">\(1\)</span> (of gelijkwaardig, de schaalparameter <span class="math inline">\(\text{scale} = \frac{1}{text{rate} = 1\)</span>), is de herschaalde prior eveneens exponentieel met een schaalparameter van <span class="math inline">\(\text{scale} \maal \text{SD}(y) = 1 maal 16,321= 16,32\)</span>.</p>
</section>
<section id="directe-output-van-stan_lmer" class="level2">
<h2 class="anchored" data-anchor-id="directe-output-van-stan_lmer">Directe output van <code>stan_lmer</code></h2>
<section id="posterior-medianen-en-posterior-mediaan-absolute-deviaties" class="level3">
<h3 class="anchored" data-anchor-id="posterior-medianen-en-posterior-mediaan-absolute-deviaties">Posterior medianen en posterior mediaan absolute deviaties</h3>
<p>We kunnen een snelle samenvatting van de fit van Model 1 weergeven door de <code>print</code> methode op de volgende manier te gebruiken:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(M1_stanlmer, <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_lmer
 family:       gaussian [identity]
 formula:      course ~ 1 + (1 | school)
 observations: 1725
------
            Median MAD_SD
(Intercept) 73.68   1.14 

Auxiliary parameter(s):
      Median MAD_SD
sigma 13.82   0.24 

Error terms:
 Groups   Name        Std.Dev.
 school   (Intercept)  8.87   
 Residual             13.82   
Num. levels: school 73 

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>Hier is de puntschatting van <span class="math inline">\(\mu_{\alpha}\)</span> uit <code>stan_lmer</code> <span class="math inline">\(73.75\)</span> en dit komt overeen met de mediaan van de posterior trekkingen. Dit is vergelijkbaar met de ML schatting uit <code>lmer</code>. De puntschatting voor <span class="math inline">\(`sigma_{_alpha}\)</span> van <code>stan_lmer</code> is <span class="math inline">\(8.87\)</span>, die groter is dan de ML schatting (<span class="math inline">\(8.67\)</span>). Dit verschil kan deels komen doordat de ML benadering in <code>lmer()</code> geen rekening houdt met de onzekerheid in <span class="math inline">\(\mu_{\alpha}\)</span> bij het schatten van <span class="math inline">\(\sigma_{\alpha}\)</span>. De REML benadering (<span class="math inline">\(8.75\)</span>) in <code>lmer()</code> houdt, zoals eerder vermeld, wel rekening met deze onzekerheid.</p>
<p>Bij gebruik van <code>stan_lmer</code> worden standaardfouten verkregen door de mediaan absolute afwijking (MAD) van elke trekking ten opzichte van de mediaan van die trekkingen te beschouwen. Het is bekend dat ML de neiging heeft om onzekerheden te onderschatten, omdat het gebaseerd is op puntschattingen van hyperparameters. Full Bayes daarentegen propageert de onzekerheid in de hyperparameters over alle niveaus van het model en levert adequatere onzekerheidsschattingen op. Zie ook Brown e.a. (2006) voor verdere discussie.</p>
</section>
<section id="posterior-gemiddelden-posterior-standaard-deviaties-95-credible-interval-en-monte-carlo-fouten" class="level3">
<h3 class="anchored" data-anchor-id="posterior-gemiddelden-posterior-standaard-deviaties-95-credible-interval-en-monte-carlo-fouten">Posterior gemiddelden, posterior standaard deviaties, 95% credible interval en Monte Carlo fouten</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(M1_stanlmer, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">pars =</span> <span class="fu">c</span>(<span class="st">"(Intercept)"</span>, <span class="st">"sigma"</span>, <span class="st">"Sigma[school:(Intercept),(Intercept)]"</span>),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>),</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">digits =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Model Info:
 function:     stan_lmer
 family:       gaussian [identity]
 formula:      course ~ 1 + (1 | school)
 algorithm:    sampling
 sample:       4000 (posterior sample size)
 priors:       see help('prior_summary')
 observations: 1725
 groups:       school (73)

Estimates:
                                        mean   sd     2.5%   97.5%
(Intercept)                            73.67   1.12  71.49  75.92 
sigma                                  13.82   0.24  13.36  14.30 
Sigma[school:(Intercept),(Intercept)]  78.67  15.55  53.46 114.10 

MCMC diagnostics
                                      mcse Rhat n_eff
(Intercept)                           0.05 1.01  572 
sigma                                 0.00 1.00 4579 
Sigma[school:(Intercept),(Intercept)] 0.61 1.00  641 

For each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).</code></pre>
</div>
</div>
<p>Het is de moeite waard om op te merken dat bij gebruik van de <code>summary</code> methode, de schatting voor de standaardafwijking <span class="math inline">\(sigma_y\)</span> het gemiddelde is van de posterior trekkingen van de parameter. Dit in tegenstelling tot de mediaan van de posterior trekkingen die we krijgen bij gebruik van de <code>print</code> methode. Een voordeel van het gebruik van de mediaan is dat de schatting voor <span class="math inline">\(\sigma_y^2\)</span> gewoon het kwadraat is van de schatting voor <span class="math inline">\(\sigma_y\)</span> als het aantal steekproeven oneven is. Dit is niet het geval bij gebruik van het gemiddelde. In dit geval, en meer algemeen wanneer we andere functies van de parameters moeten evalueren, moeten we de posterior trekkingen rechtstreeks benaderen. Dit wordt beschreven in het volgende deel.</p>
<p>Onder <code>Diagnostics</code>, verwijzen we de lezer naar Paragraaf 5 voor meer informatie over <code>Rhat</code> en <code>n_eff</code>. De waarden onder <code>mcse</code> vertegenwoordigen schattingen voor de Monte Carlo standaardfouten, die de willekeurigheid vertegenwoordigen die geassocieerd is met elke MCMC schattingsrun. Dat wil zeggen, met dezelfde dataset, herhaaldelijk gebruik van een MCMC benadering om een parameter te schatten levert schattingen op met een standaardafwijking gelijk aan de Monte Carlo standaardfout.</p>
</section>
</section>
<section id="andere-output-van-stan_lmer" class="level2">
<h2 class="anchored" data-anchor-id="andere-output-van-stan_lmer">Andere output van <code>stan_lmer</code></h2>
<p>Zoals gezegd, kunnen gebruikers er de voorkeur aan geven om direct met de posterior trekkingen te werken om schattingen van meer complexe parameters te verkrijgen. Om dit te doen, moeten gebruikers ze handmatig benaderen vanuit het <code>stan_lmer</code> object. We laten zien hoe dit moet in de context van het maken van vergelijkingen tussen individuele scholen.</p>
<section id="toegang-tot-de-simulaties-en-samenvattende-resultaten" class="level3">
<h3 class="anchored" data-anchor-id="toegang-tot-de-simulaties-en-samenvattende-resultaten">Toegang tot de simulaties en samenvattende resultaten</h3>
<p>Gebaseerd op de standaard instellingen, genereert <code>stan_lmer</code> 4 MCMC-ketens van 2.000 iteraties elk. De helft van deze iteraties in elke keten wordt gebruikt als warming-up/burn-in (om de keten te laten convergeren naar de posterior verdeling), en daarom gebruiken we slechts 1.000 steekproeven per keten. Deze door MCMC gegenereerde steekproeven worden geacht getrokken te zijn uit de posterior verdelingen van de parameters in het model. Wij kunnen deze steekproeven gebruiken voor voorspellingen, om de onzekerheid samen te vatten en ‘çredible intervals’ (geloofwaardige intervallen) te schatten voor elke functie van de parameters.</p>
<p>Om toegang te krijgen tot de posterior trekkingen voor alle parameters, passen we de methode <code>as.matrix()</code> toe op het <code>stanreg</code> object <code>M1_stanlmer</code>. Dit geeft een <span class="math inline">\(S\)</span> bij <span class="math inline">\(P\)</span> matrix, waarbij <span class="math inline">\(S\)</span> de grootte is van de posterior steekproef (of gelijkwaardig, het aantal MCMC iteraties na warm-up) en <span class="math inline">\(P\)</span> het aantal parameters/kwantiteiten. Door deze matrix te manipuleren kunnen we een matrix genereren voor de variërende intercepts <span class="math inline">\(\alpha_{j}\)</span> en vectoren met de trekkingen voor de within standaardafwijking en de between variantie. Merk op dat om de juiste kolommen voor de parameter van belang te selecteren, het nuttig is om de kolomnamen van de matrix <code>sims</code> te onderzoeken.</p>
<p>Een meer directe benadering voor het verkrijgen van de posterior trekkingen voor specifieke parameters is gebruik te maken van de ingebouwde functionaliteit van de <code>as.matrix</code> methode voor <code>stanreg</code> objecten. Wanneer de <code>as.matrix</code> methode wordt toegepast op een <code>stanreg</code> object, kan de gebruiker ofwel een optionele karaktervector van parameternamen specificeren, of een optionele karaktervector van reguliere expressies<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> om de posterior trekkingen van alleen de parameters waarin ze geïnteresseerd zijn te extraheren. Bijvoorbeeld, omdat de parameter die het totale gemiddelde representeert is gelabeld met <code>(Intercept)</code>, kunnen we de posterior trekkingen van alleen deze parameter extraheren door de optie <code>pars = "(Intercept)"</code> op te nemen. En omdat de parameters die de 73 schoolfouten representeren allemaal de string <code>b[(Intercept) school:</code> bevatten, kunnen we alle parameters die deze string bevatten extraheren door de optie <code>regex_pars = "b[(Intercept) school:</code>” te gebruiken.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraheren van de posterior trekkingen voor alle parameters</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(M1_stanlmer)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(sims)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4000   76</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>para_name <span class="ot">&lt;-</span> <span class="fu">colnames</span>(sims)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>para_name</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "(Intercept)"                          
 [2] "b[(Intercept) school:20920]"          
 [3] "b[(Intercept) school:22520]"          
 [4] "b[(Intercept) school:22710]"          
 [5] "b[(Intercept) school:22738]"          
 [6] "b[(Intercept) school:22908]"          
 [7] "b[(Intercept) school:23208]"          
 [8] "b[(Intercept) school:25241]"          
 [9] "b[(Intercept) school:30474]"          
[10] "b[(Intercept) school:35270]"          
[11] "b[(Intercept) school:37224]"          
[12] "b[(Intercept) school:47627]"          
[13] "b[(Intercept) school:50627]"          
[14] "b[(Intercept) school:50631]"          
[15] "b[(Intercept) school:60421]"          
[16] "b[(Intercept) school:60427]"          
[17] "b[(Intercept) school:60437]"          
[18] "b[(Intercept) school:60439]"          
[19] "b[(Intercept) school:60441]"          
[20] "b[(Intercept) school:60455]"          
[21] "b[(Intercept) school:60457]"          
[22] "b[(Intercept) school:60501]"          
[23] "b[(Intercept) school:60729]"          
[24] "b[(Intercept) school:60741]"          
[25] "b[(Intercept) school:63619]"          
[26] "b[(Intercept) school:63833]"          
[27] "b[(Intercept) school:64251]"          
[28] "b[(Intercept) school:64321]"          
[29] "b[(Intercept) school:64327]"          
[30] "b[(Intercept) school:64343]"          
[31] "b[(Intercept) school:64359]"          
[32] "b[(Intercept) school:64428]"          
[33] "b[(Intercept) school:65385]"          
[34] "b[(Intercept) school:66365]"          
[35] "b[(Intercept) school:67051]"          
[36] "b[(Intercept) school:67105]"          
[37] "b[(Intercept) school:67311]"          
[38] "b[(Intercept) school:68107]"          
[39] "b[(Intercept) school:68111]"          
[40] "b[(Intercept) school:68121]"          
[41] "b[(Intercept) school:68125]"          
[42] "b[(Intercept) school:68133]"          
[43] "b[(Intercept) school:68137]"          
[44] "b[(Intercept) school:68201]"          
[45] "b[(Intercept) school:68207]"          
[46] "b[(Intercept) school:68217]"          
[47] "b[(Intercept) school:68227]"          
[48] "b[(Intercept) school:68233]"          
[49] "b[(Intercept) school:68237]"          
[50] "b[(Intercept) school:68241]"          
[51] "b[(Intercept) school:68255]"          
[52] "b[(Intercept) school:68271]"          
[53] "b[(Intercept) school:68303]"          
[54] "b[(Intercept) school:68321]"          
[55] "b[(Intercept) school:68329]"          
[56] "b[(Intercept) school:68405]"          
[57] "b[(Intercept) school:68411]"          
[58] "b[(Intercept) school:68417]"          
[59] "b[(Intercept) school:68531]"          
[60] "b[(Intercept) school:68611]"          
[61] "b[(Intercept) school:68629]"          
[62] "b[(Intercept) school:68711]"          
[63] "b[(Intercept) school:68723]"          
[64] "b[(Intercept) school:68805]"          
[65] "b[(Intercept) school:68809]"          
[66] "b[(Intercept) school:71927]"          
[67] "b[(Intercept) school:74330]"          
[68] "b[(Intercept) school:74862]"          
[69] "b[(Intercept) school:74874]"          
[70] "b[(Intercept) school:76531]"          
[71] "b[(Intercept) school:76631]"          
[72] "b[(Intercept) school:77207]"          
[73] "b[(Intercept) school:84707]"          
[74] "b[(Intercept) school:84772]"          
[75] "sigma"                                
[76] "Sigma[school:(Intercept),(Intercept)]"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verkrijgen van school-niveau varyiërende intercept a_j</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="co"># trekking voor het algemeen gemiddelde</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mu_a_sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(M1_stanlmer, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">pars =</span> <span class="st">"(Intercept)"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># trekkingen voor 73 scholen van de school-niveua fouten </span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>u_sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(M1_stanlmer, </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">regex_pars =</span> <span class="st">"b</span><span class="sc">\\</span><span class="st">[</span><span class="sc">\\</span><span class="st">(Intercept</span><span class="sc">\\</span><span class="st">) school</span><span class="sc">\\</span><span class="st">:"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="co"># trekkingen van alle 73 school variërende intercepten               </span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>a_sims <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(mu_a_sims) <span class="sc">+</span> u_sims          </span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Verkrijgen van sigma_y en sigma_alpha^2</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># trekkingen van sigma_y</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>s_y_sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(M1_stanlmer, </span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>                       <span class="at">pars =</span> <span class="st">"sigma"</span>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="co"># trekkingen van sigma_alpha^2</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>s__alpha_sims <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(M1_stanlmer, </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>                       <span class="at">pars =</span> <span class="st">"Sigma[school:(Intercept),(Intercept)]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="verkrijgen-van-gemiddelden-standaard-deviaties-medianen-en-95-geloofwaardigheids-intervallen" class="level3">
<h3 class="anchored" data-anchor-id="verkrijgen-van-gemiddelden-standaard-deviaties-medianen-en-95-geloofwaardigheids-intervallen">Verkrijgen van gemiddelden, standaard deviaties, medianen en 95% geloofwaardigheids intervallen</h3>
<p>In <code>a_sims</code> hebben we 4.000 posterior trekkingen (van alle 4 ketens) voor de variërende intercepten <span class="math inline">\(\alpha_{j}\)</span> van de 73 scholen opgeslagen. De eerste kolom van de matrix van 4.000 bij 73 is bijvoorbeeld een vector van 4.000 posterior simulatietrekkingen voor de variërende intercept van de eerste school (School 20920). Een kwantitatieve manier om de posterior kansverdeling van deze 4.000 schattingen voor <span class="math inline">\(1,1pha_{1}\)</span> samen te vatten is het onderzoeken van hun quantielen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Computeer gemiddelde, SD, mediaan en 95% geloofwaardigheids interval van de varyiërende intercepten</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior gemiddelde en SD van elke alpha</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>a_mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X =</span> a_sims,     <span class="co"># posterior gemiddelde</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">MARGIN =</span> <span class="dv">2</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">FUN =</span> mean)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>a_sd <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X =</span> a_sims,       <span class="co"># posterior SD</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">MARGIN =</span> <span class="dv">2</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">FUN =</span> sd)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Posterior mediaan en 95% geloofwaardigheids interval</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>a_quant <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X =</span> a_sims, </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">MARGIN =</span> <span class="dv">2</span>, </span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">FUN =</span> quantile, </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>                 <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.50</span>, <span class="fl">0.975</span>))</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>a_quant <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">t</span>(a_quant))</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(a_quant) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Q2.5"</span>, <span class="st">"Q50"</span>, <span class="st">"Q97.5"</span>)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Combineer samenvattende statistieken van posterior simulatie trekkingen</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>a_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(a_mean, a_sd, a_quant)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">head</span>(a_df), <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            a_mean a_sd  Q2.5   Q50 Q97.5
b[(Intercept) school:20920]  63.63 4.40 54.97 63.57 72.17
b[(Intercept) school:22520]  57.15 1.79 53.72 57.15 60.60
b[(Intercept) school:22710]  81.64 3.15 75.47 81.64 87.78
b[(Intercept) school:22738]  73.03 4.27 64.48 73.11 81.50
b[(Intercept) school:22908]  66.51 5.28 56.47 66.47 76.70
b[(Intercept) school:23208]  79.23 2.81 73.60 79.22 85.02</code></pre>
</div>
</div>
<p>Wij kunnen een rupsplot maken om de volledige Bayes-schattingen voor de schoolafhankelijke intercepts in rangorde te tonen, samen met hun 95% credible intervallen.</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sorteer dataframe die een geschatte alfa gemiddelde en sd voor elke school omvatten</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>a_df <span class="ot">&lt;-</span> a_df[<span class="fu">order</span>(a_df<span class="sc">$</span>a_mean), ]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>a_df<span class="sc">$</span>a_rank <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span> <span class="sc">:</span> <span class="fu">dim</span>(a_df)[<span class="dv">1</span>])  <span class="co"># een vector van de schoolranking </span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot school-niveau alfas posterior gemiddelde en 95% credible interval</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> a_df, </span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> a_rank, </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> a_mean)) <span class="sc">+</span></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> Q2<span class="fl">.5</span>, </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                      <span class="at">ymax =</span> Q97<span class="fl">.5</span>),</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, </span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>                                             <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span> </span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(a_df<span class="sc">$</span>a_mean), </span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="fl">0.5</span>, </span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">col =</span> <span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">"Rank"</span>, </span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, </span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">to =</span> <span class="dv">80</span>, </span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">by =</span> <span class="dv">5</span>)) <span class="sc">+</span> </span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"varying intercept, "</span>, alpha[j]))) <span class="sc">+</span> </span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>( <span class="at">base_family =</span> <span class="st">"serif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multilevelrstan_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="528"></p>
</div>
</div>
<p>Dezelfde aanpak kan natuurlijk worden gevolgd om 95% geloofwaardige intervallen te genereren voor <span class="math inline">\(\sigma_y\)</span> en <span class="math inline">\(\sigma_\alpha\)</span>.</p>
</section>
<section id="vergelijkingen-maken-tussen-individuele-scholen" class="level3">
<h3 class="anchored" data-anchor-id="vergelijkingen-maken-tussen-individuele-scholen">Vergelijkingen maken tussen individuele scholen</h3>
<p>Het hebben van steekproeven van alle parameters en variërende intercepten uit hun gezamenlijke posterior verdeling maakt het gemakkelijk om inferenties te trekken over functies van deze parameters.</p>
<p>In onderwijsonderzoek en in de onderwijspraktijk is het vaak interessant om de scholen in de data met elkaar te vergelijken. Relevante vragen zijn bijvoorbeeld (1) wat is het verschil tussen de gemiddelden van school A en school B, (2) presteert school A beter dan school B en (3) wat is de rangorde van deze scholen binnen de steekproef. Wanneer niet-Bayesiaanse methoden worden gebruikt, kunnen wij proberen dergelijke vergelijkingen te maken op basis van empirische Bayes- (of Best Linear Unbiased-) voorspellingen van de variërende intercepten. Maar het zal in het algemeen onmogelijk zijn om de onzekerheid uit te drukken voor niet-lineaire functies zoals rangschikkingen. Zie ook Goldstein en Spiegelhalter (2006) voor verdere discussie.</p>
<p>Hier zullen we twee scholen vergelijken als voorbeeld: Scholen 60501 (de 21<sup>ste</sup> school) en 68271 (de 51<sup>ste</sup> school). We hebben al 4.000 posterior simulatietrekkingen voor beide scholen. Om conclusies te trekken over het verschil tussen de gemiddelde scores van de twee scholen, kunnen we eenvoudigweg het verschil nemen tussen de twee vectoren van trekkingen <span class="math inline">\(\alpha_{51} - \alpha_{21}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Het verschil tussen de twee schoolgemiddelden (school #21 en #51)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>school_diff <span class="ot">&lt;-</span> a_sims[, <span class="dv">21</span>] <span class="sc">-</span> a_sims[, <span class="dv">51</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Wij kunnen de posterior verdeling van het verschil als volgt onderzoeken met beschrijvende statistieken en een histogram:</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Onderzoek verschillen van twee distributies </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(school_diff)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(school_diff)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">quantile</span>(school_diff, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.50</span>, <span class="fl">0.975</span>))</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">t</span>(quantile))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(quantile) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Q2.5"</span>, <span class="st">"Q50"</span>, <span class="st">"Q97.5"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>diff_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(mean, sd, quantile)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(diff_df, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  mean   sd  Q2.5  Q50 Q97.5
1 5.12 4.48 -3.53 5.12 14.02</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram van de verschillen </span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> <span class="fu">data.frame</span>(school_diff), </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> school_diff)) <span class="sc">+</span> </span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">"black"</span>, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"gray"</span>, </span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="fl">0.75</span>) <span class="sc">+</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="st">"Score verschil tussen twee scholen: #21, #51"</span>,</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="sc">-</span><span class="dv">20</span>, </span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">to =</span> <span class="dv">20</span>, </span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span> </span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(<span class="fu">mean</span>(school_diff),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">quantile</span>(school_diff, </span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>))),</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">colour =</span> <span class="st">"red"</span>, </span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"longdash"</span>) <span class="sc">+</span> </span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="fl">5.11</span>, <span class="dv">20</span>, <span class="at">label =</span> <span class="st">"mean = 5.11"</span>), </span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="dv">9</span>, <span class="dv">50</span>, <span class="at">label =</span> <span class="st">"SD = 4.46"</span>), </span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"blue"</span>, </span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> </span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>( <span class="at">base_family =</span> <span class="st">"serif"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="multilevelrstan_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(a_sims[, <span class="dv">21</span>] <span class="sc">&gt;</span> a_sims[, <span class="dv">51</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  FALSE    TRUE 
0.12425 0.87575 </code></pre>
</div>
</div>
<p>Het verwachte verschil komt uit op 5,11 met een standaardafwijking van 4,46 en een grote bandbreedte van onzekerheid. Het 95% geloofwaardigheidsinterval is [-3.64, 13.66], dus we zijn er 95% zeker van dat de ware waarde van het verschil tussen de twee scholen binnen het bereik ligt, gegeven de gegevens.</p>
<p>We kunnen ook het deel van de tijd bepalen dat School 60501 een hoger gemiddelde heeft dan School 68271:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(a_sims[, <span class="dv">21</span>] <span class="sc">&gt;</span> a_sims[, <span class="dv">51</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  FALSE    TRUE 
0.12425 0.87575 </code></pre>
</div>
</div>
<div class="cell">

</div>
<p>Dit betekent dat de posterior waarschijnlijkheid dat School 60501 beter is dan School 68271 87.6% is. Elk paar scholen binnen de steekproef van scholen kan op deze manier vergeleken worden.</p>
</section>
</section>
</section>
<section id="bayesiaanse-inferentie-voor-model-2-en-3" class="level1">
<h1>Bayesiaanse inferentie voor Model 2 en 3</h1>
<section id="model-2-een-voorspeller-op-studentenniveau-toevoegen" class="level2">
<h2 class="anchored" data-anchor-id="model-2-een-voorspeller-op-studentenniveau-toevoegen">Model 2: Een voorspeller op studentenniveau toevoegen</h2>
<p>Onderzoekers zouden de variërende interceptmodellen kunnen uitbreiden met waargenomen verklarende variabelen op het niveau van de leerling <span class="math inline">\(x_{ij}\)</span>, in dit voorbeeld een indicatorvariabele voor vrouw. Een eenvoudig variërend interceptmodel met één voorspeller op het niveau van de leerling kan worden geschreven als <span class="math inline">\(y_{ij} \N(\alpha_{j} + \beta x_{ij}, \sigma_{y}^{2})\)</span> en <span class="math inline">\(\alpha_{j} \N(\mu_{alpha}, \sigma_{alpha}^{2})\)</span>. We gebruiken niet-informatieve prioriteitsverdelingen voor de hyperparameters (<span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\sigma_{\alpha}\)</span>) zoals gespecificeerd in het variërende interceptmodel zonder voorspellers. Bovendien krijgt de regressiecoëfficiënt <span class="math inline">\(\beta\)</span> een normale prioriteitsverdeling met gemiddelde 0 en standaardafwijking 100. Dit betekent, ruwweg, dat we verwachten dat deze coëfficiënt in het bereik <span class="math inline">\((-100, 100)\)</span> ligt, en als de ML schatting in dit bereik ligt, geeft de prior verdeling zeer weinig informatie voor de inferentie.</p>
<p>Het bovenstaande model kan als volgt worden gefit met de <code>stan_lmer()</code> functie in het <strong>rstanarm</strong> pakket:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>M2_stanlmer <span class="ot">&lt;-</span> <span class="fu">stan_lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> female <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> school), </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> GCSE, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">prior =</span> <span class="fu">normal</span>(<span class="at">location =</span> <span class="dv">0</span>, </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">scale =</span> <span class="dv">100</span>,</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">autoscale =</span> <span class="cn">FALSE</span>),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">prior_intercept =</span> <span class="fu">normal</span>(<span class="at">location =</span> <span class="dv">0</span>, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">scale =</span> <span class="dv">100</span>, </span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>                                                  <span class="at">autoscale =</span> <span class="cn">FALSE</span>),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>                         <span class="at">seed =</span> <span class="dv">349</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prior_summary</span>(<span class="at">object =</span> M2_stanlmer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Priors for model 'M2_stanlmer' 
------
Intercept (after predictors centered)
 ~ normal(location = 0, scale = 100)

Coefficients
 ~ normal(location = 0, scale = 100)

Auxiliary (sigma)
  Specified prior:
    ~ exponential(rate = 1)
  Adjusted prior:
    ~ exponential(rate = 0.061)

Covariance
 ~ decov(reg. = 1, conc. = 1, shape = 1, scale = 1)
------
See help('prior_summary.stanreg') for more details</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>M2_stanlmer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_lmer
 family:       gaussian [identity]
 formula:      course ~ female + (1 | school)
 observations: 1725
------
            Median MAD_SD
(Intercept) 69.7    1.3  
femaleF      6.7    0.7  

Auxiliary parameter(s):
      Median MAD_SD
sigma 13.4    0.2  

Error terms:
 Groups   Name        Std.Dev.
 school   (Intercept)  9      
 Residual             13      
Num. levels: school 73 

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<p>Merk op dat in plaats van de standaard priors in <code>stan_lmer</code>, <span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\beta\)</span> normale prior verdelingen krijgen met gemiddelde 0 en standaardafwijking 100 door de argumenten <code>prior</code> en <code>prior_intercept</code> op te geven als <code>normal(location = 0, scale = 100, autoscale = FALSE)</code>. Om te voorkomen dat <code>stan_lmer</code> de prior schaalt, moeten we ervoor zorgen dat het argument <code>autoscale = FALSE</code> wordt toegevoegd.</p>
<p>De puntschattingen van <span class="math inline">\(_mu_{alpha}\)</span>, <span class="math inline">\(\beta\)</span>, en <span class="math inline">\(\sigma_{y}\)</span> zijn bijna identiek aan de ML-schattingen van de <code>lmer()</code> fit. Echter, deels omdat ML de onzekerheid over <span class="math inline">\(\mu_{alpha}\)</span> negeert bij het schatten van <span class="math inline">\(\sigma_{alpha}\)</span>, is de Bayesiaanse schatting voor <span class="math inline">\(\sigma_{alpha}\)</span> (<span class="math inline">\(9,0\)</span>) groter dan de ML-schatting (<span class="math inline">\(8,8\)</span>), net als bij model 1.</p>
<section id="model-3-variërende-slopes-over-scholen-toevoegen" class="level3">
<h3 class="anchored" data-anchor-id="model-3-variërende-slopes-over-scholen-toevoegen">Model 3: Variërende slopes over scholen toevoegen</h3>
<p>We also use <code>stan_lmer</code> to fit Model 3 using the command below. Note that here, we use the default priors which are mostly similar to what was done in Model 1. Additionally, we are also required to specify a prior for the covariance matrix <span class="math inline">\(\Sigma\)</span> for <span class="math inline">\(\alpha_j\)</span> and <span class="math inline">\(\beta_j\)</span> in this Model. <code>stan_lmer</code> decomposes this covariance matrix (up to a factor of <span class="math inline">\(\sigma_y\)</span>) into (i) a correlation matrix <span class="math inline">\(R\)</span> and (ii) a matrix of variances <span class="math inline">\(V\)</span>, and assigns them separate priors as shown below.</p>
<p>$$</p>
<span class="math display">\[\begin{aligned}
\Sigma &amp;=
\left(\begin{matrix}
\sigma_\alpha^2 &amp; \rho\sigma_\alpha \sigma_\beta \\
\rho\sigma_\alpha\sigma_\beta&amp;\sigma_\beta^2
\end{matrix} \right)\\ &amp;=
\sigma_y^2\left(\begin{matrix}
\sigma_\alpha^2/\sigma_y^2 &amp; \rho\sigma_\alpha \sigma_\beta/\sigma_y^2 \\
\rho\sigma_\alpha\sigma_\beta/\sigma_y^2 &amp; \sigma_\beta^2/\sigma_y^2
\end{matrix} \right)\\ &amp;=
\sigma_y^2\left(\begin{matrix}
\sigma_\alpha/\sigma_y &amp; 0 \\
0&amp;\sigma_\beta/\sigma_y
\end{matrix} \right)
\left(\begin{matrix}
1 &amp; \rho\\
\rho&amp;1
\end{matrix} \right)
\left(\begin{matrix}
\sigma_\alpha/\sigma_y &amp; 0 \\
0&amp;\sigma_\beta/\sigma_y
\end{matrix} \right)\\
&amp;= \sigma_y^2VRV.
\end{aligned}\]</span>
<p>$$</p>
<p>De correlatiematrix <span class="math inline">\(R\)</span> is een 2 bij 2 matrix met 1-en op de diagonaal en <span class="math inline">\(rho\)</span>’s op de off-diagonaal. <code>stan_lmer</code> kent er een LKJ^[Voor meer details over de LKJ verdeling, zie <a href="http://www.psychstatistics.com/2014/12/27/d-lkj-priors/">hier</a> en <a href="http://mc-stan.org/users/documentation/case-studies/lotka-volterra-predator-prey.html">hier</a> prior aan toe, met regularisatieparameter 1 (Lewandowski et all., 2009). Dit komt overeen met het toekennen van een uniforme prior voor <span class="math inline">\(rho\)</span>. Hoe groter de regularisatieparameter is dan 1, hoe meer de verdeling voor <span class="math inline">\(\rho\)</span> de waarde 0 aanneemt.</p>
<p>De matrix van (geschaalde) varianties <span class="math inline">\(V\)</span> kan eerst worden samengevat in een vector van (geschaalde) varianties, en vervolgens ontleed in drie delen, <span class="math inline">\(J\)</span>, <span class="math inline">\(\tau^2\)</span> en <span class="math inline">\(\pi\)</span> zoals hieronder getoond. $$</p>
(
<span class="math display">\[\begin{matrix}
\sigma_\alpha^2/\sigma_y^2 \\
\sigma_\beta^2/\sigma_y^2
\end{matrix}\]</span>
) = 2()(
<span class="math display">\[\begin{matrix}
\frac{\sigma_\alpha^2/\sigma_y^2}{\sigma_\alpha^2/\sigma_y^2 + \sigma_\beta^2/\sigma_y^2} \\
\frac{\sigma_\beta^2/\sigma_y^2}{\sigma_\alpha^2/\sigma_y^2 + \sigma_\beta^2/\sigma_y^2}
\end{matrix}\]</span>
<p>)= J^2 .</p>
<p>$$<br>
In deze formulering is <span class="math inline">\(J\)</span> het aantal variërende effecten in het model (hier <span class="math inline">\(J=2\)</span>), kan <span class="math inline">\(Jtau^2\)</span> worden beschouwd als een gemiddelde (geschaalde) variantie over de variërende effecten <span class="math inline">\(Jalpha_j\)</span> en <span class="math inline">\(Jbeta_j\)</span>, en is <span class="math inline">\(Jpi\)</span> een niet-negatieve vector die sommeert tot 1 (een zogenaamde simplex/probabiliteitsvector). Een symmetrische Dirichlet<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> verdeling met concentratieparameter ingesteld op 1 wordt dan gebruikt als de prior voor <span class="math inline">\(\pi\)</span>. Standaard impliceert dit een gezamenlijk uniforme prior over alle simplexvectoren van dezelfde grootte. Een schaalinvariante Gamma-voorrang met vorm- en schaalparameters beide op 1 wordt dan toegekend voor <span class="math inline">\(\tau\)</span>. Dit komt overeen met het toekennen van de exponentiële verdeling met de snelheidsparameter op 1 die consistent is met de prioriteit toegekend aan <span class="math inline">\(\sigma_y\)</span> als prioriteit.</p>
<div class="cell" data-hash="multilevelrstan_cache/html/unnamed-chunk-35_9696782dd0c718ea12dcb3b191a5e0ac">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>M3_stanlmer <span class="ot">&lt;-</span> <span class="fu">stan_lmer</span>(<span class="at">formula =</span> course <span class="sc">~</span> female <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> female <span class="sc">|</span> school), </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> GCSE,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">seed =</span> <span class="dv">349</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">prior_summary</span>(<span class="at">object =</span> M3_stanlmer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Priors for model 'M3_stanlmer' 
------
Intercept (after predictors centered)
  Specified prior:
    ~ normal(location = 73, scale = 2.5)
  Adjusted prior:
    ~ normal(location = 73, scale = 41)

Coefficients
  Specified prior:
    ~ normal(location = 0, scale = 2.5)
  Adjusted prior:
    ~ normal(location = 0, scale = 83)

Auxiliary (sigma)
  Specified prior:
    ~ exponential(rate = 1)
  Adjusted prior:
    ~ exponential(rate = 0.061)

Covariance
 ~ decov(reg. = 1, conc. = 1, shape = 1, scale = 1)
------
See help('prior_summary.stanreg') for more details</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>M3_stanlmer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>stan_lmer
 family:       gaussian [identity]
 formula:      course ~ female + (1 + female | school)
 observations: 1725
------
            Median MAD_SD
(Intercept) 69.4    1.3  
femaleF      7.1    1.1  

Auxiliary parameter(s):
      Median MAD_SD
sigma 13.0    0.2  

Error terms:
 Groups   Name        Std.Dev. Corr 
 school   (Intercept) 10.3          
          femaleF      7.2     -0.49
 Residual             13.0          
Num. levels: school 73 

------
* For help interpreting the printed output see ?print.stanreg
* For info on the priors used see ?prior_summary.stanreg</code></pre>
</div>
</div>
<div class="cell">

</div>
<p>Hier zien we dat de puntschattingen voor <span class="math inline">\(\mu_{\alpha}\)</span> en <span class="math inline">\(\sigma_{y}\)</span> identiek zijn aan de ML-schattingen uit <code>lmer()</code> fit. De puntschatting voor $<span class="math inline">\(_bèta\)</span> is iets anders in dit model (7.14 vergeleken met 7.13). Verder is, net als bij de vorige twee modellen, de Bayesiaanse schatting voor <span class="math inline">\(\sigma_{\alpha}\)</span> (10.3) groter dan de ML schatting (10.15). Daarnaast zijn de Bayesiaanse schattingen voor <span class="math inline">\(\sigma_{\beta}\)</span> (7.2) en <span class="math inline">\(\rho\)</span> (-0.49) groter dan de overeenkomstige ML schattingen (respectievelijk 6.92 en -0.52).</p>
</section>
</section>
</section>
<section id="evalueren-van-model-convergentie" class="level1">
<h1>Evalueren van model convergentie</h1>
<div class="cell" data-fig.margin="true">
<div class="cell-output-display">
<p><img src="multilevelrstan_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="288"></p>
</div>
</div>
<p>Standaard zullen alle <strong>rstanarm</strong> modelleerfuncties 4 willekeurig geïnitialiseerde Markov-ketens laten lopen, elk gedurende 2000 iteraties (inclusief een opwarmperiode van 1000 iteraties). Alle ketens moeten naar de doelverdeling convergeren om geldige conclusies te kunnen trekken. De diagnostica die wij gebruiken om te beoordelen of de ketens naar de posterior verdeling zijn geconvergeerd, zijn de statistieken <span class="math inline">\(\hat{R}\)</span> en <span class="math inline">\(N_{text{eff}}\)</span> <span class="citation" data-cites="gelman1992inference">[@gelman1992inference]</span>. Aan elke parameter zijn de statistiek <span class="math inline">\(\hat{R}\)</span> en <span class="math inline">\(N_{text{eff}}\)</span> verbonden. Zoals eerder gezien, worden deze statistieken automatisch gegenereerd bij gebruik van de <code>summary</code> methode.</p>
<p>De <span class="math inline">\(\hat{R}\)</span> is in wezen de verhouding tussen-keten variantie en binnen-keten variantie analoog aan ANOVA. De statistiek <span class="math inline">\(\hat{R}\)</span> zou kleiner dan 1,1 moeten zijn als de ketens zijn geconvergeerd. Om een plot te zien van de <span class="math inline">\(\hat{R}\)</span> waarden over de parameters kunnen we de <code>plot</code> methode gebruiken voor <code>stanreg</code> object <code>M1_stanlmer</code>:</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(M1_stanlmer, <span class="st">"rhat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(M1_stanlmer, <span class="st">"ess"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De statistiek <span class="math inline">\(N_{text{eff}}\)</span> geeft het effectieve aantal trekkingen van de simulatie weer. Als de trekkingen onafhankelijk zouden zijn, zou <span class="math inline">\(N_{text{eff}}\)</span> het aantal opgeslagen trekkingen zijn, 4.000 (4 ketens $ maal$ (2.000 iteraties - 1.000 iteraties voor warmup)), maar <span class="math inline">\(N_{text{eff}}\)</span> is meestal kleiner dan 4.000 omdat Markov chain simulaties de neiging hebben autocorrelatie te vertonen. De <span class="math inline">\(N_{text{eff}}\)</span> statistiek zou typisch minstens 100 moeten zijn voor alle parameters. We kunnen een histogram plotten van de verhouding tussen de effectieve steekproefgrootte en de totale steekproefgrootte:</p>
<div class="cell" data-fig.margin="true">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(M1_stanlmer, <span class="st">"ess"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="literatuur" class="level1">
<h1>Literatuur</h1>
<p>Browne, William J, David Draper, and others. 2006. “A Comparison of Bayesian and Likelihood-Based Methods for Fitting Multilevel Models.” <em>Bayesian Analysis 1 (3)</em>: 473–514.</p>
<p>Gelman, Andrew, and Jennifer Hill. 2006. <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.</p>
<p>Gelman, Andrew, and Donald B Rubin. 1992. “Inference from Iterative Simulation Using Multiple Sequences.” <em>Statistical Science. JSTOR</em>, 457–72.</p>
<p>Goldstein, Harvey, and David J Spiegelhalter. 1996. “League Tables and Their Limitations: Statistical Issues in Comparisons of Institutional Performance.” <em>Journal of the Royal Statistical Society. Series A (Statistics in Society)</em>, 385–443.</p>
<p>Lewandowski, Daniel, Dorota Kurowicka, and Harry Joe. 2009. “Generating Random Correlation Matrices Based on Vines and Extended Onion Method.” <em>Journal of Multivariate Analysis 100 (9)</em>. Elsevier: 1989–2001.</p>
<p>Rasbash, Jon, William Browne, Harvey Goldstein, Min Yang, Ian Plewis, Michael Healy, Geoff Woodhouse, David Draper, Ian Langford, and Toby Lewis. 2000. “<em>A User’s Guide to Mlwin.</em>” University of London, Institute of Education, Centre for Multilevel Modelling.</p>


</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>We werken meer over prioriteitsverdelingen uit in hoofdstuk 3. 2<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Gebruikers die niet vertrouwd zijn met de syntaxis van <strong>ggplot2</strong> verwijzen we naar <a href="https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf">hier</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p>Voor meer informatie over reguliere expressies, zie <a href="http://www.rstudio.com/wp-content/uploads/2016/09/RegExCheatsheet.pdf">hier</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>De Dirichlet-verdeling is een multivariate veralgemening van de bètaverdeling met één concentratieparameter, die kan worden geïnterpreteerd als voorafgaande tellingen van een multinomiale willekeurige variabele (de simplexvector in onze context), zie voor details <a href="https://cran.r-project.org/web/packages/rstanarm/vignettes/glmer.html#details">hier</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>