<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Russel Poldrack, bewerking HarrieJonkman">
<meta name="dcterms.date" content="2022-11-07">
<meta name="description" content="Statistisch denken in de 21ste eeuw met R én Python">

<title>Statistisch denken in de 21ste eeuw</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3a1197cc0774821054ad3543cdc64272.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Harrie’s Hoekje</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Jonkman1"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Statistisch denken in de 21ste eeuw</h1>
                  <div>
        <div class="description">
          <p>Statistisch denken in de 21ste eeuw met R én Python</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">voorbereiden</div>
                <div class="quarto-category">modelleren</div>
                <div class="quarto-category">communiceren</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Russel Poldrack, bewerking HarrieJonkman </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 7, 2022</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#inleiding" id="toc-inleiding" class="nav-link active" data-scroll-target="#inleiding">Inleiding</a></li>
  <li><a href="#r-en-python" id="toc-r-en-python" class="nav-link" data-scroll-target="#r-en-python">R en Python</a></li>
  <li><a href="#quarto" id="toc-quarto" class="nav-link" data-scroll-target="#quarto">Quarto</a></li>
  <li><a href="#waarschijnlijkheid" id="toc-waarschijnlijkheid" class="nav-link" data-scroll-target="#waarschijnlijkheid">Waarschijnlijkheid</a></li>
  <li><a href="#wat-is-waarschijnlijkheid" id="toc-wat-is-waarschijnlijkheid" class="nav-link" data-scroll-target="#wat-is-waarschijnlijkheid">Wat is waarschijnlijkheid?</a></li>
  <li><a href="#hoe-stellen-we-waarschijnlijkheden-vast" id="toc-hoe-stellen-we-waarschijnlijkheden-vast" class="nav-link" data-scroll-target="#hoe-stellen-we-waarschijnlijkheden-vast">Hoe stellen we waarschijnlijkheden vast?</a></li>
  <li><a href="#waarschijnlijkheidsdistributies" id="toc-waarschijnlijkheidsdistributies" class="nav-link" data-scroll-target="#waarschijnlijkheidsdistributies">Waarschijnlijkheidsdistributies</a></li>
  <li><a href="#conditionele-waarschijnlijkheid" id="toc-conditionele-waarschijnlijkheid" class="nav-link" data-scroll-target="#conditionele-waarschijnlijkheid">Conditionele waarschijnlijkheid</a></li>
  <li><a href="#vaststellen-van-conditionele-waarschijnlijkheden-van-data" id="toc-vaststellen-van-conditionele-waarschijnlijkheden-van-data" class="nav-link" data-scroll-target="#vaststellen-van-conditionele-waarschijnlijkheden-van-data">Vaststellen van conditionele waarschijnlijkheden van data</a></li>
  <li><a href="#onafhankelijkheid" id="toc-onafhankelijkheid" class="nav-link" data-scroll-target="#onafhankelijkheid">Onafhankelijkheid</a></li>
  <li><a href="#omdraaien-van-een-conditionele-waarschijnlijkheid-bayes-regel" id="toc-omdraaien-van-een-conditionele-waarschijnlijkheid-bayes-regel" class="nav-link" data-scroll-target="#omdraaien-van-een-conditionele-waarschijnlijkheid-bayes-regel">Omdraaien van een conditionele waarschijnlijkheid: Bayes’ regel</a></li>
  <li><a href="#leren-van-data" id="toc-leren-van-data" class="nav-link" data-scroll-target="#leren-van-data">Leren van data</a></li>
  <li><a href="#odds-en-odds-ratios" id="toc-odds-en-odds-ratios" class="nav-link" data-scroll-target="#odds-en-odds-ratios">Odds en odds ratio’s</a></li>
  <li><a href="#wat-betekenen-waarschijnlijkheden" id="toc-wat-betekenen-waarschijnlijkheden" class="nav-link" data-scroll-target="#wat-betekenen-waarschijnlijkheden">Wat betekenen waarschijnlijkheden?</a></li>
  <li><a href="#bayesiaanse-statistiek" id="toc-bayesiaanse-statistiek" class="nav-link" data-scroll-target="#bayesiaanse-statistiek">Bayesiaanse statistiek</a>
  <ul class="collapse">
  <li><a href="#generatieve-modellen" id="toc-generatieve-modellen" class="nav-link" data-scroll-target="#generatieve-modellen">Generatieve modellen</a></li>
  <li><a href="#bayes-theorema-en-inverse-inferentie" id="toc-bayes-theorema-en-inverse-inferentie" class="nav-link" data-scroll-target="#bayes-theorema-en-inverse-inferentie">Bayes’ theorema en inverse inferentie</a></li>
  <li><a href="#een-bayesiaanse-schatting-doen" id="toc-een-bayesiaanse-schatting-doen" class="nav-link" data-scroll-target="#een-bayesiaanse-schatting-doen">Een Bayesiaanse schatting doen</a></li>
  <li><a href="#schatten-van-posterior-distributies" id="toc-schatten-van-posterior-distributies" class="nav-link" data-scroll-target="#schatten-van-posterior-distributies">Schatten van posterior distributies</a></li>
  <li><a href="#het-kiezen-van-een-prior" id="toc-het-kiezen-van-een-prior" class="nav-link" data-scroll-target="#het-kiezen-van-een-prior">Het kiezen van een prior</a></li>
  <li><a href="#bayesiaanse-hypothesetests" id="toc-bayesiaanse-hypothesetests" class="nav-link" data-scroll-target="#bayesiaanse-hypothesetests">Bayesiaanse hypothesetests</a></li>
  <li><a href="#bayesiaanse-hypothese-test" id="toc-bayesiaanse-hypothese-test" class="nav-link" data-scroll-target="#bayesiaanse-hypothese-test">Bayesiaanse hypothese test</a></li>
  <li><a href="#wat-hebben-we-geleerd" id="toc-wat-hebben-we-geleerd" class="nav-link" data-scroll-target="#wat-hebben-we-geleerd">Wat hebben we geleerd</a></li>
  <li><a href="#suggesties-om-te-lezen" id="toc-suggesties-om-te-lezen" class="nav-link" data-scroll-target="#suggesties-om-te-lezen">Suggesties om te lezen</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="inleiding" class="level2">
<h2 class="anchored" data-anchor-id="inleiding">Inleiding</h2>
<p><img src="Screenshot.PNG" class="img-fluid"></p>
<p>Een paar jaar geleden schreef Russell A. Poldrack <a href="https://statsthinking21.github.io/statsthinking21-core-site/">Statistical Thinking for the 21st Century</a>. Dat vind ik een inspirerend boek. Poldrack wil ons de basisideeën van statistisch denken laten begrijpen. Zijn boek presenteert een systematische manier van denken over het beschrijven van de wereld met behulp van data, hoe we deze kunnen gebruiken bij het nemen van beslissingen en het doen van voorspellingen en dit alles in de context van onzekerheid die er in de wereld bestaat. Met de traditionele statistiekboeken kon hij niet uit de voeten en daarom besloot hij zijn eigen boek te maken. Hij gebruikt aansprekende datasets in zijn boek en moderne manieren om hiermee om te gaan.</p>
<p>Om je deze nieuwe manier van statistisch denken eigen te maken, moet je ermee werken, je moet het doen.</p>
</section>
<section id="r-en-python" class="level2">
<h2 class="anchored" data-anchor-id="r-en-python">R en Python</h2>
<p>Poldrack presenteert niet alleen zijn ideeën open-source, hij werkt ook met open-source programma’s en wil ons ermee laten werken. Naast zijn open-source boek <em>Statistical Thinking for the 21st Centrury</em> heeft hij ook twee open-source programmaboeken gemaakt die laten zien hoe je met data kunt werken. Allereerst is er <a href="https://statsthinking21.github.io/statsthinking21-R-site/">An R companion to Statistical Thinking for the 21st Centrury</a>. Dit document richt zich op het gebruik van R (en RStudio) als programmeertaal voor statistiek en data-analyse. Met dit programma heeft hijzelf niet zoveel mee op, maar daarin zitten wel pakketten waar hij graag mee werkt en die niet in andere programma’s zitten. Hijzelf heeft meer op met Python en hij schreef daarom ook de <a href="https://statsthinking21.github.io/statsthinking21-python/">Python Companion to Statistical Thinking in the 21st Century</a></p>
</section>
<section id="quarto" class="level2">
<h2 class="anchored" data-anchor-id="quarto">Quarto</h2>
<p>Afgelopen weken heb ik zijn interessante boek nog eens gelezen. Ook nu weer vind ik zijn boek weer zeer aansprekend en uitdagend. Met beide programmaboeken in R en Python ernaast leer je met de goede talen van deze tijd te werken. Voor deze blog heb ik daarom twee hoofdstukken genomen die over waarschijnlijkheid en Bayesiaanse statistiek gaan. Dit leert mij niet alleen om met R te werken maar ook om deze handelingen in Python te doen. Via Quarto kun je met beide programma’s werken. Ik heb hoofdstuk 6 (Waarschijnlijkheid) en hoofdstuk 11 (Bayesiaanse statstiek) genomen en voor dit blog gewerkt. Deze blog schrijf ik in R en Quarto en de bewerking hiervan vind je hieronder<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
</section>
<section id="waarschijnlijkheid" class="level2">
<h2 class="anchored" data-anchor-id="waarschijnlijkheid">Waarschijnlijkheid</h2>
<p>Eerst maar eens enkele R-pakketten openen om mee te werken (dplyr, reshap2, tidyr, ggplot2, knitr, readr, cowplot, janitor) en om de data te kunnen laden (NHANES):</p>
<p>Waarschijnlijkheidstheorie is de tak van de wiskunde die zich bezighoudt met kans en onzekerheid. Het vormt een belangrijk deel van de basis voor statistiek omdat het ons de wiskundige instrumenten verschaft om onzekere gebeurtenissen te beschrijven. De studie van waarschijnlijkheid is deels ontstaan uit belangstelling voor het begrijpen van kansspelen, zoals kaarten of dobbelen. Deze spelen bieden nuttige voorbeelden van veel statistische concepten omdat bij herhaling van deze spelen de kans op verschillende uitkomsten (meestal) gelijk blijft. Er zijn echter diepgaande vragen over de betekenis van waarschijnlijkheid die we hier niet zullen behandelen (zie Aanbevolen literatuur aan het einde als je meer wilt weten over dit fascinerende onderwerp en zijn geschiedenis).</p>
</section>
<section id="wat-is-waarschijnlijkheid" class="level2">
<h2 class="anchored" data-anchor-id="wat-is-waarschijnlijkheid">Wat is waarschijnlijkheid?</h2>
<p>Informeel denken we bij waarschijnlijkheid meestal aan een getal dat de waarschijnlijkheid beschrijft dat een bepaalde gebeurtenis zich voordoet, variërend van nul (onmogelijk) tot één (zeker). Soms worden waarschijnlijkheden uitgedrukt in percentages, die variëren van nul tot honderd, zoals wanneer het weerbericht voorspelt dat er vandaag twintig procent kans is op regen. In elk geval drukken deze getallen uit hoe waarschijnlijk die bepaalde gebeurtenis is, variërend van absoluut onmogelijk tot absoluut zeker.</p>
<p>Om de kansrekening te formaliseren, moeten we eerst een paar termen definiëren:</p>
<ul>
<li>Een <strong>experiment</strong> is elke activiteit die een resultaat oplevert of observeert. Voorbeelden zijn het opgooien van een munt, het gooien met een zeszijdige dobbelsteen of het uitproberen van een nieuwe route naar het werk om te zien of die sneller is dan de oude route.</li>
<li>De <strong>steekproefruimte</strong> is de verzameling mogelijke uitkomsten voor een experiment. Wij stellen deze voor door ze op te sommen binnen een reeks haakjes. Voor een muntstuk is de steekproefruimte {koppen, munt}. Voor een zeszijdige dobbelsteen is de steekproefruimte elk van de mogelijke getallen die kunnen verschijnen: {1,2,3,4,5,6}. Voor de hoeveelheid tijd die nodig is om aan het werk te gaan, is de steekproefruimte alle mogelijke reële getallen groter dan nul (omdat het geen negatieve hoeveelheid tijd kan kosten om ergens te komen, tenminste nog niet). We zullen niet proberen al die getallen tussen haakjes te zetten.</li>
<li>Een <strong>gebeurtenis</strong> is een deelverzameling van de steekproefruimte. In principe kan het een of meer mogelijke uitkomsten in de steekproefruimte zijn, maar we zullen ons hier voornamelijk richten op <em>elementaire gebeurtenissen</em> die bestaan uit precies één mogelijke uitkomst. Dit kan bijvoorbeeld kop zijn bij een enkele muntworp, een 4 gooien bij een dobbelsteenworp of 21 minuten over de nieuwe route naar huis doen.</li>
</ul>
<p>Nu we deze definities hebben, kunnen we de formele kenmerken van een kans schetsen, die voor het eerst werden gedefinieerd door de Russische wiskundige Andrei Kolmogorov. Dit zijn de kenmerken die een waarde <em>moeten</em> hebben om een kans te zijn. Laten we zeggen dat we een steekproefruimte hebben gedefinieerd door N onafhankelijke gebeurtenissen, <span class="math inline">\({E_1, E_2, .... , E_N}\)</span>, en <span class="math inline">\(X\)</span> is een willekeurige variabele die aangeeft welke gebeurtenis zich heeft voorgedaan. <span class="math inline">\(P(X=E_i)\)</span> is de kans op gebeurtenis <span class="math inline">\(i\)</span>:</p>
<ul>
<li>De waarschijnlijkheid kan niet negatief zijn: <span class="math inline">\(P(X=E_i) \ge 0\)</span>.</li>
<li>De totale waarschijnlijkheid van alle uitkomsten in de steekproefruimte is 1; dat wil zeggen, als we de waarschijnlijkheid van elke Ei nemen en optellen, moeten ze bij elkaar opgeteld 1 zijn. We kunnen dit uitdrukken met het sommatieteken <span class="math inline">\(sum\)</span>:</li>
</ul>
<p><span class="math display">\[
\sum_{i=1}^N{P(X=E_i)} = P(X=E_1) + P(X=E_2) + ... + P(X=E_N) = 1
\]</span></p>
<p>Dit wordt geïnterpreteerd als: “Neem alle N elementaire gebeurtenissen, die we gelabeld hebben van 1 tot N, en tel hun kansen op. Deze moeten bij elkaar opgeteld één zijn.”<br>
- De waarschijnlijkheid van een individuele gebeurtenis kan niet groter zijn dan één: <span class="math inline">\(P(X=E_i)≤ 1\)</span>. Dit vloeit voort uit het vorige punt; aangezien zij moeten optellen tot één en zij niet negatief kunnen zijn, kan geen enkele kans groter zijn dan één.</p>
</section>
<section id="hoe-stellen-we-waarschijnlijkheden-vast" class="level2">
<h2 class="anchored" data-anchor-id="hoe-stellen-we-waarschijnlijkheden-vast">Hoe stellen we waarschijnlijkheden vast?</h2>
<p>Nu we weten wat een waarschijnlijkheid is, hoe komen we er eigenlijk achter wat de waarschijnlijkheid is voor een bepaalde gebeurtenis?</p>
<section id="persoonlijke-overtuiging" class="level3">
<h3 class="anchored" data-anchor-id="persoonlijke-overtuiging">Persoonlijke overtuiging</h3>
<p>Stel dat ik u vraag wat de kans is dat Bernie Sanders de presidentsverkiezingen van 2016 zou hebben gewonnen als hij de democratische kandidaat was geweest in plaats van Hilary Clinton? We kunnen het experiment niet uitvoeren om de uitkomst te vinden. Maar de meeste mensen met kennis van de Amerikaanse politiek zouden bereid zijn om op zijn minst een gokje te wagen naar de waarschijnlijkheid van deze gebeurtenis. In veel gevallen is persoonlijke kennis en/of mening de enige leidraad die we hebben om de waarschijnlijkheid van een gebeurtenis te bepalen, maar dit is wetenschappelijk gezien niet erg bevredigend.</p>
</section>
<section id="empirische-frequentie" class="level3">
<h3 class="anchored" data-anchor-id="empirische-frequentie">Empirische frequentie</h3>
<p>Een andere manier om de waarschijnlijkheid van een gebeurtenis te bepalen is het experiment vele malen uit te voeren en te tellen hoe vaak elke gebeurtenis zich voordoet. Uit de relatieve frequentie van de verschillende uitkomsten kunnen we de waarschijnlijkheid van elke uitkomst berekenen. Laten we bijvoorbeeld zeggen dat we de kans op regen in San Francisco willen weten. We moeten eerst het experiment definiëren — laten we zeggen dat we voor elke dag in 2017 de gegevens van de National Weerstation bekijken en bepalen of er regen is gevallen op het weerstation in het centrum van San Francisco. Volgens deze gegevens waren er in 2017 73 regendagen. Om de kans op regen in San Francisco te berekenen, delen we gewoon het aantal regendagen door het aantal getelde dagen (365), wat P(regen in SF in 2017) = 0,2 oplevert.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">aantal regendagen</th>
<th style="text-align: right;">aantal dagen gemeten</th>
<th style="text-align: right;">P(regen)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">73</td>
<td style="text-align: right;">365</td>
<td style="text-align: right;">0.2</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Hoe weten we dat de empirische waarschijnlijkheid ons het juiste getal geeft? Het antwoord op deze vraag komt van de <em>wet van de grote getallen</em>, die aantoont dat de empirische kans de ware kans benadert naarmate de steekproefomvang toeneemt. We kunnen dit zien als een groot aantal keren munten opgooien (simuleren), en kijken naar onze schatting van de kans op kop na elke worp. Ga er voor hier maar van uit dat we voor de computer een manier hebben om een willekeurige uitkomst te genereren voor elke worp.</p>
<p>Het linkerpaneel van figuur laat zien dat de geschatte kans op koppen convergeert naar de werkelijke waarde van 0,5 naarmate het aantal steekproeven (d.w.z. muntproeven) toeneemt. Merk echter op dat de schattingen zeer ver van de ware waarde kunnen afwijken wanneer de steekproefomvang klein is. Een praktijkvoorbeeld hiervan werd gezien bij de speciale verkiezing voor de Amerikaanse Senaat in Alabama in 2017, waarbij de Republikein Roy Moore het opnam tegen de Democraat Doug Jones.Het rechterpaneel toont het relatieve aantal stemmen dat in de loop van de avond voor elk van de kandidaten werd gemeld, naarmate er meer stembiljetten werden geteld. Aan het begin van de avond waren de stemmenaantallen bijzonder onstabiel, met een grote aanvankelijke voorsprong voor Jones en een lange periode waarin Moore de leiding had, totdat Jones uiteindelijk de leiding nam en de race won.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/ElectionResults-1.png" style="height:50.0%" width="768" class="figure-img"></p>
<figcaption>Figuur1. Links: Een demonstratie van de wet van de grote getallen. Een munt werd 30.000 keer opgegooid, en na elke worp werd de kans op kop berekend op basis van het aantal koppen en staarten dat tot dan toe was verzameld. Het duurt ongeveer 15.000 keer voordat de waarschijnlijkheid de werkelijke waarschijnlijkheid van 0,5 bereikt. Rechts: Relatief aandeel van de stemmen in de speciale verkiezing van 12 december 2017 voor de zetel van de Amerikaanse Senaat in Alabama, als functie van het percentage kiesdistricten dat rapporteert. Deze gegevens zijn overgenomen uit: https://www.ajc.com/news/national/alabama-senate-race-live-updates-roy-moore-doug-jones/KPRfkdaweoiXICW3FHjXqI/</figcaption>
</figure>
</div>
</div>
</div>
<p><br> Deze twee voorbeelden tonen aan dat, hoewel grote steekproeven uiteindelijk zullen convergeren naar de ware waarschijnlijkheid, de resultaten met kleine steekproeven er ver naast kunnen zitten. Helaas vergeten veel mensen dit en overinterpreteren ze de resultaten van kleine steekproeven. Dit werd de wet van de kleine aantallen genoemd door de psychologen Danny Kahneman en Amos Tversky, die aantoonden dat mensen (zelfs getrainde onderzoekers) zich vaak gedragen alsof de wet van de grote aantallen ook geldt voor kleine steekproeven en te veel geloof hechten aan resultaten die gebaseerd zijn op kleine datasets. In het boek laten we voorbeelden zien van hoe onstabiel statistische resultaten kunnen zijn wanneer zij worden gegenereerd op basis van kleine steekproeven.</p>
</section>
<section id="klassieke-waarschijnlijkheid" class="level3">
<h3 class="anchored" data-anchor-id="klassieke-waarschijnlijkheid">Klassieke waarschijnlijkheid</h3>
<p>Het is onwaarschijnlijk dat iemand van ons ooit tienduizenden keren een munt heeft opgegooid, maar we zijn toch bereid te geloven dat de kans dat er kop wordt gegooid 0,5 is. Dit weerspiegelt het gebruik van nog een andere benadering om kansen te berekenen, die we <em>klassieke kans</em> noemen. Bij deze benadering berekenen we de kans rechtstreeks op basis van onze kennis van de situatie.</p>
<p>Klassieke kansberekening is ontstaan uit de studie van kansspelen zoals dobbelen en kaarten. Een beroemd voorbeeld ontstond uit een probleem van een Franse gokker die Chevalier de Méré heette. De Méré speelde twee verschillende dobbelspellen: Bij het eerste gokte hij op de kans op minstens één zes bij vier worpen met een zeszijdige dobbelsteen, terwijl hij bij het tweede gokte op de kans op minstens één dubbele zes bij 24 worpen met twee dobbelstenen. Hij verwachtte bij beide gokken geld te winnen, maar hij ontdekte dat hij bij de eerste gok gemiddeld geld won, maar bij de tweede gok gemiddeld geld verloor. Om dit te begrijpen wendde hij zich tot zijn vriend, de wiskundige Blaise Pascal, die nu erkend wordt als een van de grondleggers van de kansrekening.</p>
<p>Hoe kunnen we deze vraag begrijpen met behulp van de kansrekening? In de klassieke kansrekening gaan we ervan uit dat alle elementaire gebeurtenissen in de steekproefruimte even waarschijnlijk zijn; dat wil zeggen, als je met een dobbelsteen gooit, is de kans dat elk van de mogelijke uitkomsten ({1,2,3,4,5,6}) zich voordoet even groot. (Daarom kunnen we de waarschijnlijkheid van elke individuele uitkomst berekenen als één gedeeld door het aantal mogelijke uitkomsten):</p>
<p><span class="math display">\[
P(uitkomst_i) = \frac{1}{\text{aantal mogelijke uitkomsten}}
\]</span></p>
<p>Voor de zeszijdige dobbelsteen is de kans op elke individuele uitkomst 1/6.</p>
<p>Dit is mooi, maar de Méré was geïnteresseerd in meer complexe gebeurtenissen, zoals wat er gebeurt bij meerdere dobbelsteenworpen. Hoe berekenen we de waarschijnlijkheid van een complexe gebeurtenis (die een <em>vereniging</em> is van afzonderlijke gebeurtenissen), zoals het gooien van een zes bij de eerste <em>of</em> tweede worp? We geven de vereniging van gebeurtenissen wiskundig weer met behulp van het symbool <span class="math inline">\(\Cup\)</span>: als bijvoorbeeld de kans op het gooien van een zes bij de eerste worp <span class="math inline">\(P(Uitkomst6_{worp1})\)</span> is en de kans op het gooien van een zes bij de tweede worp <span class="math inline">\(P(Uitkomst6_{worp2})\)</span>, dan wordt de vereniging <span class="math inline">\(P(Uitkomst6_{worp1} \cup Uitkomst6_{worp2})\)</span> genoemd.</p>
<p>De Méré dacht (ten onrechte, zoals we hieronder zullen zien) dat hij gewoon de kansen van de individuele gebeurtenissen kon optellen om de kans op de gecombineerde gebeurtenis te berekenen, wat betekent dat de kans op het gooien van een zes bij de eerste of tweede worp als volgt zou worden berekend:</p>
<p><span class="math display">\[
P(Uitkomst6_{worp1}) = 1/6
\]</span></p>
<p><span class="math display">\[
P(Uitkomst6_{worp2}) = 1/6
\]</span></p>
<p><span class="math display">\[
de Méré's \ fout:
\]</span></p>
<p><span class="math display">\[
P(Uitkomst6_{worp1} \cup Uitkomst6_{worp2}) = P(Uitkomst6_{worp1}) + P(Uitkomst6_{worp2}) = 1/6 + 1/6 = 1/3
\]</span></p>
<p>De Méré redeneerde op basis van deze onjuiste veronderstelling dat de kans op minstens één zes in vier worpen de som was van de kansen op elke afzonderlijke worp: <span class="math inline">\(4*\frac{1}{6}= \frac{2}{3}\)</span>. Evenzo redeneerde hij dat aangezien de kans op een dubbele zes bij het gooien van twee dobbelstenen 1/36 is, de kans op minstens één dubbele zes bij 24 worpen met twee dobbelstenen <span class="math inline">\(24*\frac{1}{36}=\frac{2}{3}\)</span> zou zijn. Maar terwijl hij consequent geld won met de eerste weddenschap, verloor hij geld met de tweede weddenschap. Wat is er aan de hand?</p>
<p>Om de fout van de Méré te begrijpen, moeten we enkele regels van de kansrekening introduceren. De eerste is de <em>aftrekregel</em>, die zegt dat de kans dat een gebeurtenis A <em>niet</em> gebeurt, één is min de kans dat de gebeurtenis wel gebeurt:</p>
<p><span class="math display">\[
P(\neg A) = 1 - P(A)
\]</span></p>
<p>waarbij <span class="math inline">\(\neg A\)</span> betekent “niet A”. Deze regel vloeit rechtstreeks voort uit de axioma’s die we hierboven hebben besproken; omdat A en <span class="math inline">\(\neg A\)</span> de enige mogelijke uitkomsten zijn, moet hun totale waarschijnlijkheid opgeteld 1 zijn. Bijvoorbeeld, als de kans op het gooien van een één in een enkele worp <span class="math inline">\(\frac{1}{6}\)</span> is, dan is de kans op het gooien van iets anders dan een één <span class="math inline">\(\frac{5}{6}\)</span>.</p>
<p>Een tweede regel vertelt ons hoe we de kans op een gecombineerde gebeurtenis moeten berekenen – dat wil zeggen, de kans dat twee gebeurtenissen allebei voorkomen. We noemen dit een <em>intersectie</em>, die wordt aangeduid met het symbool <span class="math inline">\(\cap\)</span>; zo betekent <span class="math inline">\(P(A \cap B)\)</span> de kans dat zowel A als B zich voordoen. We zullen ons concentreren op een versie van de regel die ons vertelt hoe we deze grootheid moeten berekenen in het speciale geval dat de twee gebeurtenissen onafhankelijk van elkaar zijn; we zullen later leren wat het begrip <em>onafhankelijkheid</em> precies betekent, maar voor nu kunnen we gewoon aannemen dat de twee dobbelsteenworpen onafhankelijke gebeurtenissen zijn. We berekenen de kans op het snijpunt van twee onafhankelijke gebeurtenissen door eenvoudigweg de kansen van de afzonderlijke gebeurtenissen te vermenigvuldigen:</p>
<p><span class="math display">\[
P(A \cap B) = P(A) * P(B)\ \text{als en alleen als A en B onafhankelijk zijn}
\]</span></p>
<p>De kans op een zes bij beide worpen is dus <span class="math inline">\(\frac{1}{6}*\frac{1}{6}=\frac{1}{36}\)</span>.</p>
<p>De derde regel vertelt ons hoe we kansen moeten optellen - en hier zien we de bron van de fout van de Méré. De optelregel vertelt ons dat om de kans te krijgen dat een van twee gebeurtenissen zich voordoet, we de individuele kansen bij elkaar optellen, maar vervolgens de kans dat beide gebeurtenissen zich samen voordoen van elkaar aftrekken:</p>
<p><span class="math display">\[
P(A \cup B) = P(A) + P(B) - P(A \cap B)
\]</span></p>
<p>In zekere zin voorkomt dit dat we die gevallen tweemaal tellen, en dat is wat de regel onderscheidt van de onjuiste berekening van de Méré. Laten we zeggen dat we de kans op een 6 willen vinden bij een van de twee worpen. Volgens onze regels:</p>
<p><span class="math display">\[
P(Uitkomst6_{worp1} \cup Uitkomst6_{worp2}) = P(Uitkomst6_{worp1}) + P(Uitkomst6_{worp2}) - P(Uitkomst6_{worp1} \cap Uitkomst6_{worp2})
\]</span></p>
<p><span class="math display">\[
= \frac{1}{6} + \frac{1}{6} - \frac{1}{36} = \frac{11}{36}
\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/ThrowMatrix-1.png" style="height:50.0%" width="384" class="figure-img"></p>
<figcaption>Figuur2. Elke cel in deze matrix vertegenwoordigt een uitkomst van twee worpen van een dobbelsteen, waarbij de kolommen staan voor de eerste worp en de rijen voor de tweede worp. De cellen in rood staan voor de cellen met een zes in de eerste of tweede worp; de rest is blauw..</figcaption>
</figure>
</div>
</div>
</div>
<p>Laten we een grafische voorstelling gebruiken om een andere kijk op deze regel te krijgen. Het figuur hierboven toont een matrix met alle mogelijke combinaties van resultaten bij twee worpen en benadrukt de cellen met een zes bij de eerste of tweede worp. Als je de cellen in het rood optelt, zie je dat er 11 van zulke cellen zijn. Hieruit blijkt waarom de optelregel een ander antwoord geeft dan dat van de Méré; als we simpelweg de kansen voor de twee worpen bij elkaar zouden optellen zoals hij deed, dan zouden we (6,6) bij beide tellen, terwijl het eigenlijk maar één keer geteld zou moeten worden.</p>
</section>
<section id="oplossen-van-het-probleem-van-de-méré" class="level3">
<h3 class="anchored" data-anchor-id="oplossen-van-het-probleem-van-de-méré">Oplossen van het probleem van de Méré</h3>
<p>Blaise Pascal gebruikte de regels van de waarschijnlijkheid om een oplossing te vinden voor het probleem van de Méré. Ten eerste besefte hij dat het berekenen van de kans op minstens één gebeurtenis uit een combinatie lastig was, terwijl het berekenen van de kans dat iets niet voorkomt bij meerdere gebeurtenissen relatief eenvoudig is – het is gewoon het product van de kansen van de afzonderlijke gebeurtenissen. Dus in plaats van de kans te berekenen op minstens één zes in vier worpen, berekende hij de kans op geen zessen in alle worpen:</p>
<p><span class="math display">\[
P(\text{geen zessen bij vier keer werpen}) = \frac{5}{6}*\frac{5}{6}*\frac{5}{6}*\frac{5}{6}=\bigg(\frac{5}{6}\bigg)^4=0.482
\]</span></p>
<p>Hij gebruikte vervolgens het feit dat de kans op geen zessen in vier worpen het complement is van ten minste één zes in vier worpen (ze moeten dus optellen tot één), en gebruikte de aftrekregel om de kans op rente te berekenen:</p>
<p><span class="math display">\[
P(\text{op z'n minst een zes in vier worpen}) = 1 - \bigg(\frac{5}{6}\bigg)^4=0.517
\]</span></p>
<p>De Méré’s gok dat hij minstens één zes zou gooien in vier worpen heeft een waarschijnlijkheid van meer dan 0,5, wat verklaart waarom de Méré gemiddeld geld verdiende met deze inzet.</p>
<p>Maar hoe zit het met de Méré’s tweede weddenschap? Pascal gebruikte dezelfde truc:</p>
<p><span class="math display">\[
P(\text{geen dubbele zes in 24 worpen}) = \bigg(\frac{35}{36}\bigg)^{24}=0.509
\]</span></p>
<p><span class="math display">\[
P(\text{ten minste een dubbele zes in 24 worpen}) = 1 - \bigg(\frac{35}{36}\bigg)^{24}=0.491
\]</span></p>
<p>De kans op dit resultaat lag iets onder 0,5, wat aantoont waarom de Méré gemiddeld geld verloor op deze weddenschap.</p>
</section>
</section>
<section id="waarschijnlijkheidsdistributies" class="level2">
<h2 class="anchored" data-anchor-id="waarschijnlijkheidsdistributies">Waarschijnlijkheidsdistributies</h2>
<p>Een <em>waarschijnlijkheidsdistributie</em> beschrijft de waarschijnlijkheid van alle mogelijke uitkomsten in een experiment. Bijvoorbeeld, op 20 januari 2018 raakte de basketballer Steph Curry slechts 2 van de 4 vrije worpen in een wedstrijd tegen de Houston Rockets. We weten dat Curry’s totale kans op vrije worpen over het hele seizoen 0,91 was, dus het lijkt vrij onwaarschijnlijk dat hij slechts 50% van zijn vrije worpen in een wedstrijd zou raken, maar hoe onwaarschijnlijk is het precies? We kunnen dit bepalen met behulp van een theoretische kansverdeling; in dit boek zullen we een aantal van deze kansverdelingen tegenkomen, die elk geschikt zijn om verschillende soorten gegevens te beschrijven. In dit geval gebruiken we de <em>binomiale</em> verdeling, die een manier biedt om de kans te berekenen op een bepaald aantal successen uit een aantal proeven met succes of mislukking en niets daartussen (bekend als “Bernoulli proeven”), gegeven een bekende kans op succes op elke proef. Deze verdeling wordt gedefinieerd als:</p>
<p><span class="math display">\[
P(k; n,p) = P(X=k) = \binom{n}{k} p^k(1-p)^{n-k}
\]</span></p>
<p>Dit verwijst naar de kans op k successen op n proeven als de kans op succes p is. Je bent misschien niet bekend met <span class="math inline">\(\binom{n}{k}\)</span>, die de <em>binomiaalcoëfficiënt</em> wordt genoemd. De binomiaalcoëfficiënt wordt ook wel “n-kiezen” genoemd, omdat hij het aantal verschillende manieren beschrijft waarop men k items kan kiezen uit n totale items. De binomiaalcoëfficiënt wordt als volgt berekend:</p>
<p><span class="math display">\[
\binom{n}{k} = \frac{n!}{k!(n-k)!}
\]</span> waarbij het uitroepteken (!) verwijst naar het <em>factoriale</em> van het getal:</p>
<p><span class="math display">\[
n! = \prod_{i=1}^n i = n*(n-1)*...*2*1
\]</span></p>
<p>De productoperator <span class="math inline">\(\prod\)</span> lijkt op de sommator <span class="math inline">\(\sum\)</span>, maar vermenigvuldigt in plaats van telt op. In dit geval worden alle getallen van één tot <span class="math inline">\(n\)</span> met elkaar vermenigvuldigd.</p>
<p>In het voorbeeld van Steph Curry’s vrije worpen:</p>
<p><span class="math display">\[
P(2;4,0.91) = \binom{4}{2} 0.91^2(1-0.91)^{4-2} = 0.040
\]</span></p>
<p>Hieruit blijkt dat gezien Curry’s totale percentage vrije worpen, het zeer onwaarschijnlijk is dat hij slechts 2 van de 4 vrije worpen zou raken. Zo zie je maar dat onwaarschijnlijke dingen echt gebeuren in de echte wereld.</p>
<section id="cumulatieve-waarschijnlijkheids-distributies" class="level3">
<h3 class="anchored" data-anchor-id="cumulatieve-waarschijnlijkheids-distributies">Cumulatieve waarschijnlijkheids-distributies</h3>
<p>Vaak willen we niet alleen weten hoe waarschijnlijk een bepaalde waarde is, maar ook hoe waarschijnlijk het is om een waarde te vinden die even extreem of meer is dan een bepaalde waarde; dit wordt heel belangrijk als later hypothesetesten worden besproken. Om deze vraag te beantwoorden kunnen we een <em>cumulatieve</em> kansverdeling gebruiken; terwijl een standaard kansverdeling ons de kans op een bepaalde waarde vertelt, vertelt de cumulatieve verdeling ons de kans op een waarde die even groot of groter (of even klein of kleiner) is dan een bepaalde waarde.</p>
<p><span class="math display">\[
P(k\le2)= P(k=2) + P(k=1) + P(k=0) = 6e^{-5} + .002 + .040 = .043  
\]</span></p>
<p>In veel gevallen zou het aantal mogelijke uitkomsten te groot zijn om de cumulatieve kans te berekenen door alle mogelijke waarden op te sommen; gelukkig kan deze direct worden berekend voor elke theoretische kansverdeling. De tabel hieronder toont de cumulatieve kans op elk mogelijk aantal geslaagde vrije worpen in het voorbeeld van hierboven, waaruit we kunnen opmaken dat de kans dat Curry 2 of minder vrije worpen maakt uit 4 pogingen 0,043 is.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Simpele en cumulatieve waarschijnlijkheidsdistributies voor aantal succesvolle vrije worpen van Steph Curry in 4 pogingen.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">numSuccesses</th>
<th style="text-align: right;">Probability</th>
<th style="text-align: right;">CumulativeProbability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.040</td>
<td style="text-align: right;">0.043</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.271</td>
<td style="text-align: right;">0.314</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.686</td>
<td style="text-align: right;">1.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="conditionele-waarschijnlijkheid" class="level2">
<h2 class="anchored" data-anchor-id="conditionele-waarschijnlijkheid">Conditionele waarschijnlijkheid</h2>
<p>Tot nu toe hebben wij ons beperkt tot eenvoudige kansen - dat wil zeggen de kans op een enkele gebeurtenis of combinatie van gebeurtenissen. Vaak willen we echter de waarschijnlijkheid van een bepaalde gebeurtenis bepalen, gegeven dat een andere gebeurtenis heeft plaatsgevonden, wat bekend staat als <em>conditionele waarschijnlijkheid</em>.</p>
<p>Laten we de Amerikaanse presidentsverkiezingen van 2016 als voorbeeld nemen. Er zijn twee eenvoudige waarschijnlijkheden die we kunnen gebruiken om het electoraat te beschrijven. Ten eerste weten we de kans dat een kiezer in de VS aangesloten is bij de Republikeinse partij: <span class="math inline">\(p(Republikein) = 0,44\)</span>. We weten ook de kans dat een kiezer zijn stem uitbrengt ten gunste van Donald Trump: <span class="math inline">\(p(Trump-stemmer)=0,46\)</span>. Laten we echter zeggen dat we het volgende willen weten: Wat is de kans dat iemand zijn stem op Donald Trump heeft uitgebracht, <em>gegeven dat hij Republikein is</em>?</p>
<p>Om de voorwaardelijke kans op A gegeven B te berekenen (die we schrijven als <span class="math inline">\(P(A|B)\)</span>, “kans op A, gegeven B”), moeten we de <em>gezamenlijke kans</em> kennen (d.w.z. de kans dat zowel A als B voorkomen), evenals de totale kans op B:</p>
<p><span class="math display">\[
P(A|B) = \frac{P(A \cap B)}{P(B)}
\]</span></p>
<p>Dat wil zeggen, we willen weten hoe groot de kans is dat beide dingen waar zijn, gegeven dat hetgene waarop de voorwaarde betrekking heeft waar is.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/conditional_probability.png" style="height:50.0%" width="288" class="figure-img"></p>
<figcaption>Figuur 3. Een grafische voorstelling van de voorwaardelijke waarschijnlijkheid, die laat zien hoe de voorwaardelijke waarschijnlijkheid onze analyse beperkt tot een deelverzameling van de gegevens.</figcaption>
</figure>
</div>
</div>
</div>
<p>Het kan nuttig zijn dit grafisch voor te stellen. Hierboven zien we een stroomdiagram die laat zien hoe de volledige populatie kiezers uiteenvalt in Republikeinen en Democraten, en hoe de conditionele waarschijnlijkheid (conditionering op partij) de leden van elke partij verder uitsplitst naar hun stemgedrag.</p>
</section>
<section id="vaststellen-van-conditionele-waarschijnlijkheden-van-data" class="level2">
<h2 class="anchored" data-anchor-id="vaststellen-van-conditionele-waarschijnlijkheden-van-data">Vaststellen van conditionele waarschijnlijkheden van data</h2>
<p>Wij kunnen voorwaardelijke kansen ook rechtstreeks uit gegevens berekenen. Stel dat we geïnteresseerd zijn in de volgende vraag: Wat is de kans dat iemand diabetes heeft, als hij niet lichamelijk actief is? – Dat is <span class="math inline">\(P(diabetes|inactief)\)</span>. De NHANES-dataset bevat twee variabelen die de twee delen van deze vraag behandelen. De eerste (<code>Diabetes</code>) vraagt of de persoon ooit te horen heeft gekregen dat hij diabetes heeft, de tweede (``PhysActive```) registreert of de persoon deelneemt aan sport, fitness of recreatieve activiteiten van ten minste matige intensiteit. Laten we eerst de eenvoudige kansen berekenen die in de tabel staan. De tabel laat zien dat de kans dat iemand in de NHANES-dataset diabetes heeft .1 is, en dat de kans dat iemand inactief is .45 is.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Samenvattende data voor diabetes en fysieke activiteit</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Answer</th>
<th style="text-align: right;">N_diabetes</th>
<th style="text-align: right;">P_diabetes</th>
<th style="text-align: right;">N_PhysActive</th>
<th style="text-align: right;">P_PhysActive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">4893</td>
<td style="text-align: right;">0.8989528</td>
<td style="text-align: right;">2472</td>
<td style="text-align: right;">0.4541613</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">550</td>
<td style="text-align: right;">0.1010472</td>
<td style="text-align: right;">2971</td>
<td style="text-align: right;">0.5458387</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Gedeelde waarschijnlijkheden voor Diabetes en FysActieve variabelen.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Diabetes</th>
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">prob</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">2123</td>
<td style="text-align: right;">0.3900423</td>
</tr>
<tr class="even">
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">2770</td>
<td style="text-align: right;">0.5089105</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
<td style="text-align: right;">349</td>
<td style="text-align: right;">0.0641191</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">201</td>
<td style="text-align: right;">0.0369282</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Om <span class="math inline">\(P(diabetes|inactief)\)</span> te berekenen moeten we ook de gezamenlijke waarschijnlijkheid van diabetes <em>en</em> inactiviteit kennen, naast de eenvoudige waarschijnlijkheid van elk van beide. Deze staan in de tabel. Op basis van deze gezamenlijke kansen kunnen we <span class="math inline">\(P(diabetes|inactief)\)</span> berekenen. Een manier om dit in een computerprogramma te doen is eerst te bepalen of de FysActieve variabele voor elk individu gelijk was aan “Nee”, en dan het gemiddelde van die waarheidswaarden te nemen. Aangezien TRUE/FALSE-waarden door de meeste programmeertalen (waaronder R en Python) worden behandeld als respectievelijk 1/0, kunnen we de waarschijnlijkheid van een eenvoudige gebeurtenis gemakkelijk bepalen door eenvoudigweg het gemiddelde te nemen van een logische variabele die de waarheidswaarde ervan weergeeft. Vervolgens gebruiken we die waarde om de voorwaardelijke kans te berekenen, waarbij we vinden dat de kans dat iemand diabetes heeft, gegeven dat hij lichamelijk inactief is, is 0.141.</p>
</section>
<section id="onafhankelijkheid" class="level2">
<h2 class="anchored" data-anchor-id="onafhankelijkheid">Onafhankelijkheid</h2>
<p>De term “onafhankelijk” heeft een zeer specifieke betekenis in de statistiek, die enigszins afwijkt van het gangbare gebruik van de term. Statistische onafhankelijkheid tussen twee variabelen betekent dat het kennen van de waarde van de ene variabele niets zegt over de waarde van de andere. Dit kan worden uitgedrukt als:</p>
<p><span class="math display">\[
P(A|B) = P(A)
\]</span></p>
<p>Dat wil zeggen, de kans op A gegeven een bepaalde waarde van B is gewoon hetzelfde als de totale kans op A. Als we het zo bekijken, zien we dat veel gevallen van wat we in de echte wereld “onafhankelijkheid” zouden noemen, eigenlijk niet statistisch onafhankelijk zijn. Zo wil een kleine groep Californiërs momenteel een nieuwe onafhankelijke staat uitroepen, Jefferson genaamd, die een aantal provincies in Noord-Californië en Oregon zou omvatten. Als dit zou gebeuren, dan zou de kans dat een huidige inwoner van Californië nu in de staat Jefferson zou wonen <span class="math inline">\(P({Jeffersonian})=0.014\)</span> zijn, terwijl de kans dat hij een inwoner van Californië zou blijven <span class="math inline">\(P({Californian})=0.986\)</span> zou zijn. De nieuwe staten zouden politiek onafhankelijk kunnen zijn, maar ze zouden <em>niet</em> statistisch onafhankelijk zijn, want als we weten dat iemand Jeffersonian is, dan kunnen we er zeker van zijn dat hij <em>niet</em> Californiër is! Dat wil zeggen, terwijl onafhankelijkheid in het gewone taalgebruik vaak verwijst naar reeksen die elkaar uitsluiten, verwijst statistische onafhankelijkheid naar het geval waarin men niets kan voorspellen over een variabele op basis van de waarde van een andere variabele. Als je bijvoorbeeld iemands haarkleur kent, kun je waarschijnlijk niet zeggen of hij chocolade- of aardbeienijs prefereert.</p>
<p>Laten we een ander voorbeeld bekijken, aan de hand van de NHANES-gegevens: Zijn lichamelijke en geestelijke gezondheid onafhankelijk van elkaar? NHANES bevat twee relevante vragen: <em>PhysActive</em>, die vraagt of de persoon lichamelijk actief is, en <em>DaysMentHlthBad</em>, die vraagt hoeveel dagen van de laatste 30 de persoon een slechte geestelijke gezondheid had. Laten we iedereen die de afgelopen maand meer dan 7 dagen een slechte geestelijke gezondheid had, beschouwen als iemand met een slechte geestelijke gezondheid. Op basis hiervan kunnen we een nieuwe variabele genaamd <em>badMentalHealth</em> definiëren als een logische variabele die aangeeft of elke persoon meer dan 7 dagen een slechte geestelijke gezondheid had of niet. We kunnen de gegevens eerst samenvatten om te laten zien hoeveel personen in elke combinatie van de twee variabelen vallen (weergegeven in de tabel hieronder en dan delen door het totale aantal waarnemingen om een tabel met verhoudingen te maken.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Samenvatting van absolute frequentiedata voor mentale gezondheid en fysieke activiteit.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">Bad Mental Health</th>
<th style="text-align: right;">Good Mental Health</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">629</td>
<td style="text-align: right;">2510</td>
<td style="text-align: right;">3139</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">471</td>
<td style="text-align: right;">3095</td>
<td style="text-align: right;">3566</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">1100</td>
<td style="text-align: right;">5605</td>
<td style="text-align: right;">6705</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Samenvatting van relatieve frequentiedata voor mentale gezondheid en fysieke activiteit.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">Bad Mental Health</th>
<th style="text-align: right;">Good Mental Health</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">0.0938106</td>
<td style="text-align: right;">0.3743475</td>
<td style="text-align: right;">0.4681581</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0.0702461</td>
<td style="text-align: right;">0.4615958</td>
<td style="text-align: right;">0.5318419</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">0.1640567</td>
<td style="text-align: right;">0.8359433</td>
<td style="text-align: right;">1.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Dit toont ons het aandeel van alle waarnemingen die in elke cel vallen. Wat we hier echter willen weten is de voorwaardelijke kans op een slechte geestelijke gezondheid, afhankelijk van of men lichamelijk actief is of niet. Om dit te berekenen delen we elke groep lichaamsbeweging door het totale aantal waarnemingen, zodat elke rij nu sommeert tot één (weergegeven in Tabel hierboven). Hier zien we de voorwaardelijke kansen op een slechte of goede geestelijke gezondheid voor elke groep lichaamsbeweging (in de bovenste twee rijen) samen met de algemene kans op een goede of slechte geestelijke gezondheid in de derde rij. Om te bepalen of geestelijke gezondheid en lichamelijke activiteit onafhankelijk zijn, zouden we de eenvoudige kans op een slechte geestelijke gezondheid (in de derde rij) vergelijken met de voorwaardelijke kans op een slechte geestelijke gezondheid als men lichamelijk actief is (in de tweede rij).</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Samenvatting van conditionele waarschijnlijkheid voor mentale gezondheid gegeven fysieke activiteit.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">PhysActive</th>
<th style="text-align: right;">Bad Mental Health</th>
<th style="text-align: right;">Good Mental Health</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">No</td>
<td style="text-align: right;">0.2003823</td>
<td style="text-align: right;">0.7996177</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yes</td>
<td style="text-align: right;">0.1320808</td>
<td style="text-align: right;">0.8679192</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">0.1640567</td>
<td style="text-align: right;">0.8359433</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>De totale kans op slechte geestelijke gezondheid <span class="math inline">\(P({ slechte geestelijke gezondheid})\)</span> is 0.1640567 terwijl de voorwaardelijke kans <span class="math inline">\(P({ slechte geestelijke gezondheid|fysiek actief})\)</span> 0.1320808 is. Het lijkt er dus op dat de voorwaardelijke waarschijnlijkheid iets kleiner is dan de totale waarschijnlijkheid, wat suggereert dat ze niet onafhankelijk zijn, hoewel we dat niet zeker kunnen weten door alleen naar de getallen te kijken, omdat die getallen anders kunnen zijn door willekeurige variabiliteit in onze steekproef. Later in het boek bespreken we statistische hulpmiddelen waarmee we direct kunnen testen of twee variabelen onafhankelijk zijn.</p>
</section>
<section id="omdraaien-van-een-conditionele-waarschijnlijkheid-bayes-regel" class="level2">
<h2 class="anchored" data-anchor-id="omdraaien-van-een-conditionele-waarschijnlijkheid-bayes-regel">Omdraaien van een conditionele waarschijnlijkheid: Bayes’ regel</h2>
<p>In veel gevallen weten we <span class="math inline">\(P(A|B)\)</span> maar willen we eigenlijk <span class="math inline">\(P(B|A)\)</span> weten. Dit komt vaak voor bij medische screening, waar we <span class="math inline">\(P(positieve testuitslag|ziekte)\)</span> weten, maar wat we willen weten is <span class="math inline">\(P(ziekte|positieve testuitslag)\)</span>. Sommige artsen bevelen bijvoorbeeld aan dat mannen boven de 50 jaar een screening ondergaan met een test, die prostaat-specifiek antigeen (PSA) heet, om te screenen op mogelijke prostaatkanker. Voordat een test wordt goedgekeurd voor gebruik in de medische praktijk moet de fabrikant twee aspecten van de werking van de test testen. Ten eerste moeten ze aantonen hoe <em>sensitief</em> de test is - dat wil zeggen, hoe groot de kans is dat de ziekte wordt gevonden als die aanwezig is: <span class="math inline">\(\text{gevoeligheid} = P(\text{positieve test|ziekte})\)</span>. Ze moeten ook aantonen hoe <em>specifiek</em> de test is, dat wil zeggen hoe groot de kans is dat de test een negatief resultaat geeft als er geen ziekte aanwezig is: <span class="math display">\[\text{specificiteit} = P(\text{negatieve test|geen ziekte}\]</span>. Voor de PSA-test weten we dat de sensitiviteit ongeveer 80% en de specificiteit ongeveer 70% is. Deze geven echter geen antwoord op de vraag die de arts voor een bepaalde patiënt wil beantwoorden: hoe groot is de kans dat hij daadwerkelijk kanker heeft, als de test positief is? Dit vereist dat we de voorwaardelijke waarschijnlijkheid die de gevoeligheid definieert omkeren: in plaats van <span class="math inline">\(P(positieve test|ziekte)\)</span> willen we <span class="math inline">\(P(ziekte|positieve test)\)</span> weten.</p>
<p>Om een voorwaardelijke kans om te keren, kunnen we de <em>regel van Bayes</em> gebruiken:</p>
<p><span class="math display">\[
P(B|A) = \frac{P(A|B)*P(B)}{P(A)}
\]</span></p>
<p>De regel van Bayes is vrij gemakkelijk af te leiden, op basis van de waarschijnlijkheidsregels die we eerder in het hoofdstuk hebben geleerd (zie de Appendix hiervoor).</p>
<p>Als we slechts twee uitkomsten hebben, kunnen we de regel van Bayes iets duidelijker uitdrukken door de somregel te gebruiken om <span class="math inline">\(P(A)\)</span> opnieuw te definiëren:</p>
<p><span class="math display">\[
P(A) = P(A|B)*P(B) + P(A|\neg B)*P(\neg B)
\]</span></p>
<p>Als we dit gebruiken, kunnen we Bayes’ regel omdraaien:</p>
<p><span class="math display">\[
P(B|A) = \frac{P(A|B)*P(B)}{P(A|B)*P(B) + P(A|\neg B)*P(\neg B)}
\]</span></p>
<p>We kunnen de relevante getallen in deze vergelijking stoppen om de waarschijnlijkheid te bepalen dat iemand met een positieve PSA-uitslag daadwerkelijk kanker heeft – maar om dit te kunnen doen, moeten we ook de algemene waarschijnlijkheid van kanker voor die persoon kennen, die we vaak het <em>basispercentage</em> noemen. Nemen we een man van 60 jaar voor wie de kans op prostaatkanker in de komende 10 jaar <span class="math inline">\(P(kanker)=0,058\)</span> is. Met behulp van de sensitiviteits- en specificiteitswaarden die we hierboven hebben geschetst, kunnen we berekenen hoe groot de kans is dat iemand kanker krijgt bij een positieve test:</p>
<p><span class="math display">\[
P(\text{kanker|test}) = \frac{P(\text{test|kanker})*P(\text{kanker})}{P(\text{test|kanker})*P(\text{kanker}) + P(\text{test|}\neg\text{kanker})*P(\neg\text{kanker})}
\]</span></p>
<p><span class="math display">\[
= \frac{0.8*0.058}{0.8*0.058 +0.3*0.942 } = 0.14
\]</span></p>
<p>Dat is vrij klein – vindt u dat verrassend? Veel mensen wel en in feite is er een aanzienlijke psychologische literatuur die aantoont dat mensen systematisch <em>basiscijfers</em> (d.w.z. algemene prevalentie) verwaarlozen in hun oordeel.</p>
</section>
<section id="leren-van-data" class="level2">
<h2 class="anchored" data-anchor-id="leren-van-data">Leren van data</h2>
<p>Een andere manier om de regel van Bayes te zien is als een manier om onze overtuigingen bij te werken op basis van gegevens - dat wil zeggen, leren over de wereld met behulp van gegevens. Laten we de regel van Bayes nog eens bekijken:</p>
<p><span class="math display">\[
P(B|A) =  \frac{P(A|B)*P(B)}{P(A)}
\]</span></p>
<p>De verschillende onderdelen van de regel van Bayes hebben specifieke namen, die verband houden met hun rol bij het gebruik van de regel van Bayes om onze overtuigingen bij te werken. We beginnen met een eerste schatting van de waarschijnlijkheid van B (<span class="math inline">\(P(B)\)</span>), die we de <em>prior</em> waarschijnlijkheid noemen. In het PSA-voorbeeld gebruikten we het basispercentage als onze prior, omdat dat onze beste inschatting was van de kans op kanker van de betrokkene voordat we het testresultaat kenden. Vervolgens verzamelen wij gegevens, in ons voorbeeld het testresultaat. De mate waarin de gegevens A overeenkomen met uitkomst B wordt gegeven door <span class="math inline">\(P(A|B)\)</span>, die we de <em>waarschijnlijkheid</em> noemen. U kunt dit zien als hoe waarschijnlijk de gegevens zijn, gegeven dat de bepaalde geteste hypothese waar is. In ons voorbeeld was de geteste hypothese of het individu kanker had, en de waarschijnlijkheid was gebaseerd op onze kennis over de sensitiviteit van de test (d.w.z. de kans op een positief testresultaat als er kanker aanwezig is). De noemer (<span class="math inline">\(P(A)\)</span>) wordt de <em>marginale waarschijnlijkheid</em> genoemd, omdat deze de totale waarschijnlijkheid van de gegevens weergeeft, gemiddeld over alle mogelijke waarden van B (in ons voorbeeld ziekte aanwezig en ziekte afwezig). De uitkomst aan de linkerkant (<span class="math inline">\(P(B|A)\)</span>) wordt de <em>posterior</em> genoemd, omdat die na de berekening eruit komt.</p>
<p>Er is een andere manier om de regel van Bayes te schrijven die dit wat duidelijker maakt:</p>
<p><span class="math display">\[
P(B|A) = \frac{P(A|B)}{P(A)}*P(B)
\]</span></p>
<p>Het linkerdeel (<span class="math inline">\(\frac{P(A|B)}{P(A)}\)</span>) vertelt ons hoeveel meer of minder waarschijnlijk de gegevens A zijn gegeven B, in verhouding tot de algemene (marginale) waarschijnlijkheid van de gegevens, terwijl het rechterdeel (<span class="math inline">\(P(B)\)</span>) ons vertelt hoe waarschijnlijk we dachten dat B was voordat we iets over de gegevens wisten. Dit maakt duidelijker dat de rol van het theorema van Bayes erin bestaat onze voorkennis bij te werken op basis van de mate waarin de gegevens waarschijnlijker zijn gegeven B dan zij globaal zouden zijn. Als de hypothese gezien de gegevens waarschijnlijker is dan zij in het algemeen zou zijn, vergroten wij ons geloof in de hypothese; als zij gezien de gegevens minder waarschijnlijk is, verminderen wij ons geloof.</p>
</section>
<section id="odds-en-odds-ratios" class="level2">
<h2 class="anchored" data-anchor-id="odds-en-odds-ratios">Odds en odds ratio’s</h2>
<p>Het resultaat in de vorige paragraaf toonde aan dat de kans dat de persoon kanker heeft op basis van een positieve PSA-testuitslag nog steeds vrij laag is, ook al is die meer dan twee keer zo groot als voordat we de testuitslag kenden. Vaak willen we de relatie tussen kansen directer kwantificeren, wat we kunnen doen door ze om te zetten in <em>odds</em> die de relatieve waarschijnlijkheid uitdrukken dat iets wel of niet gebeurt:</p>
<p><span class="math display">\[
\text{odds van A} = \frac{P(A)}{P(\neg A)}
\]</span></p>
<p>In ons PSA voorbeeld is dat de kans op kanker (gegeven de positieve test):</p>
<p><span class="math display">\[
\text{odds van kanker} = \frac{P(\text{kanker})}{P(\neg \text{kanker})} =\frac{0.14}{1 - 0.14} = 0.16
\]</span></p>
<p>Dit vertelt ons dat de kans vrij klein is dat je kanker hebt, ook al was de test positief. Ter vergelijking, de kans op een 6 bij een enkele worp met een dobbelsteen is:</p>
<p><span class="math display">\[
\text{odds van 6} = \frac{1}{5} = 0.2
\]</span></p>
<p>Terzijde: dit is een reden waarom veel medische onderzoekers steeds huiveriger zijn geworden voor het gebruik van wijdverbreide screeningtests voor relatief ongebruikelijke aandoeningen; de meeste positieve resultaten zullen vals-positief blijken te zijn, wat leidt tot onnodige vervolgonderzoeken met mogelijke complicaties, om nog maar te zwijgen van de extra stress voor de patiënt.</p>
<p>We kunnen kansen ook gebruiken om verschillende waarschijnlijkheden te vergelijken, door een zogenaamde <em>odds ratio</em> te berekenen - en dat is precies hoe het klinkt. Laten we bijvoorbeeld zeggen dat we willen weten hoeveel de positieve test de kans op kanker verhoogt. We kunnen eerst de <em>prior odds</em> berekenen, dat wil zeggen de kansen voordat we wisten dat de persoon positief getest was. Deze worden berekend met behulp van het basispercentage:</p>
<p><span class="math display">\[
\text{prior odds} = \frac{P(\text{kanker})}{P(\neg \text{kanker})} =\frac{0.058}{1 - 0.058} = 0.061
\]</span></p>
<p>Wij kunnen deze dan vergelijken met de posterior odds, die worden berekend met behulp van de posterior waarschijnlijkheid:</p>
<p><span class="math display">\[
\text{odds ratio} = \frac{\text{posterior odds}}{\text{prior odds}} = \frac{0.16}{0.061} = 2.62
\]</span></p>
<p>Dit vertelt ons dat de kans om kanker te krijgen 2,62 keer zo groot is bij een positieve testuitslag. Een odds ratio is een voorbeeld van wat we later een <em>effectgrootte</em> zullen noemen, een manier om te kwantificeren hoe relatief groot een bepaald statistisch effect is.</p>
</section>
<section id="wat-betekenen-waarschijnlijkheden" class="level2">
<h2 class="anchored" data-anchor-id="wat-betekenen-waarschijnlijkheden">Wat betekenen waarschijnlijkheden?</h2>
<p>Het is misschien een beetje vreemd om te praten over de waarschijnlijkheid dat iemand kanker heeft, afhankelijk van een testresultaat; de persoon heeft immers kanker of niet. Historisch gezien zijn er twee verschillende manieren om kansen te interpreteren. De eerste (bekend als de <em>frequentistische</em> interpretatie) interpreteert kansen in termen van langetermijnfrequenties. In het geval van het opgooien van een muntstuk bijvoorbeeld, zou de kans de relatieve frequentie van koppen op de lange termijn weergeven na een groot aantal opgooien. Hoewel deze interpretatie zinvol kan zijn voor gebeurtenissen die zich vele malen kunnen herhalen, zoals het opgooien van een munt, is zij minder zinvol voor gebeurtenissen die slechts eenmaal zullen plaatsvinden, zoals het leven van een individuele persoon of een bepaalde presidentsverkiezing; en zoals de econoom John Maynard Keynes ooit zei: “Op de lange termijn zijn we allemaal dood”.</p>
<p>De andere interpretatie van waarschijnlijkheden (bekend als de <em>Bayesiaanse</em> interpretatie) is als een mate van geloof in een bepaalde stelling. Als ik u zou vragen “Hoe waarschijnlijk is het dat de VS in 2040 naar de maan terugkeert”, kunt u deze vraag beantwoorden op basis van uw kennis en overtuigingen, ook al zijn er geen relevante frequenties om een frequentistische waarschijnlijkheid te berekenen. Een manier waarop we subjectieve kansen vaak formuleren is in termen van iemands bereidheid om een bepaalde gok te aanvaarden. Als u bijvoorbeeld denkt dat de kans dat de VS in 2040 op de maan zal landen 0,1 is (d.w.z. een kans van 9 tegen 1), dan betekent dit dat u bereid zou moeten zijn een gok te aanvaarden die meer dan 9 tegen 1 oplevert als de gebeurtenis plaatsvindt.</p>
<p>Zoals we zullen zien, zijn deze twee verschillende definities van waarschijnlijkheid zeer relevant voor de twee verschillende manieren waarop statistici denken over het testen van statistische hypothesen, die we in latere hoofdstukken zullen tegenkomen.</p>
</section>
<section id="bayesiaanse-statistiek" class="level1">
<h1>Bayesiaanse statistiek</h1>
<p>Dit deel gaat in op de benadering van statistische modellering en inferentie die in contrast staat met de nulhypothesetest die we standaard kennen. Wat hier behandeld wordt staat bekend als “Bayesiaanse statistiek”, naar dominee Thomas Bayes, wiens theorema hierboven aan de orde kwam. In dit deel leer je hoe het theorema van Bayes een manier is om gegevens te begrijpen die veel van de conceptuele problemen oplost die samenhangen met het testen van nulhypothesen. Maar het introduceert ook enkele nieuwe uitdagingen.</p>
<section id="generatieve-modellen" class="level2">
<h2 class="anchored" data-anchor-id="generatieve-modellen">Generatieve modellen</h2>
<p>Stel dat je op straat loopt en een vriend van je loopt voorbij, maar zegt geen gedag. Je zou waarschijnlijk proberen te bepalen waarom dit gebeurde – Heeft hij je niet gezien? Zijn ze boos op je? Ben je plotseling gehuld in een magisch onzichtbaarheidsschild? Een van de basisideeën achter Bayesiaanse statistiek is dat we de details willen afleiden van hoe de gegevens worden gegenereerd, op basis van de gegevens zelf. In dit geval wil je de gegevens (d.w.z. het feit dat je vriend geen gedag heeft gezegd) gebruiken om het proces af te leiden dat de gegevens heeft gegenereerd (d.w.z. of hij je wel of niet heeft gezien, wat hij voor je voelt, enz.)</p>
<p>Het idee achter een generatief model is dat een <em>latent</em> (ongezien) proces de gegevens genereert die wij waarnemen, meestal met een zekere mate van willekeur in het proces. Wanneer wij een steekproef van gegevens uit een populatie nemen en uit de steekproef een parameter schatten, proberen wij in wezen de waarde te leren van een latente variabele (het populatiegemiddelde) die door bemonstering leidt tot de waargenomen gegevens (het steekproefgemiddelde). Het figuur hieronder toont een schematisch overzicht van dit idee.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/BayesianInference.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figuur 4. Een schema van het idee van een generatief model.</figcaption>
</figure>
</div>
</div>
</div>
<p>Als we de waarde van de latente variabele kennen, dan is het eenvoudig om te reconstrueren hoe de waargenomen gegevens eruit zouden moeten zien. Stel bijvoorbeeld dat we een munt opgooien waarvan we weten dat hij eerlijk is, zodat we verwachten dat hij in 50% van de gevallen op kop terechtkomt. We kunnen de munt beschrijven met een binomiale verdeling met een waarde van <span class="math inline">\(P_{kop}=0,5\)</span>, en dan kunnen we willekeurige steekproeven uit zo’n verdeling genereren om te zien hoe de waargenomen gegevens eruit zouden moeten zien. In het algemeen bevinden we ons echter in de omgekeerde situatie: We kennen de waarde van de latente variabele van belang niet, maar we hebben wel gegevens die we willen gebruiken om die te schatten.</p>
</section>
<section id="bayes-theorema-en-inverse-inferentie" class="level2">
<h2 class="anchored" data-anchor-id="bayes-theorema-en-inverse-inferentie">Bayes’ theorema en inverse inferentie</h2>
<p>De Bayesiaanse statistiek heet zo omdat zij gebruik maakt van de stelling van Bayes om uit gegevens conclusies te trekken over het onderliggende proces dat de gegevens heeft voortgebracht. Stel dat we willen weten of een munt eerlijk is. Om dit te testen gooien we de munt 10 keer op en krijgen we 7 koppen. Vóór deze test waren we er vrij zeker van dat de <span class="math inline">\(P_{kop}=0,5\)</span>, maar 7 koppen vinden uit 10 opgooien zou ons zeker aan het denken zetten als we geloofden dat <span class="math inline">\(P_{kop}=0,5\)</span>. We weten al hoe we met behulp van de binomiale verdeling de voorwaardelijke kans kunnen berekenen dat we 7 of meer koppen op 10 gooien als de munt echt eerlijk is (<span class="math inline">\(P(n\ge7|p_{kop}=0,5)\)</span>).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0546875</code></pre>
</div>
</div>
<p>De resulterende waarschijnlijkheid is 0.055. Dat is een vrij klein getal, maar dit getal beantwoordt niet echt de vraag die we stellen – het zegt ons iets over de waarschijnlijkheid van 7 of meer koppen bij een bepaalde kans op koppen, terwijl we eigenlijk de werkelijke kans op koppen voor deze specifieke munt willen weten. Dit zou bekend moeten klinken, want het is precies de situatie waarin we ons bevonden met nulhypothesetests, die ons iets zeiden over de waarschijnlijkheid van gegevens in plaats van over de waarschijnlijkheid van hypothesen.</p>
<p>Vergeet niet dat de stelling van Bayes ons het instrument verschaft dat we nodig hebben om een voorwaardelijke kans om te keren:</p>
<p><span class="math display">\[
P(H|D) = \frac{P(D|H)*P(H)}{P(D)}
\]</span></p>
<p>We kunnen deze stelling zien als bestaande uit vier delen:</p>
<ul>
<li><em>prior</em> (<span class="math inline">\(P(Hypothese)\)</span>): Onze mate van overtuiging over hypothese H voordat we de Data D hebben gezien</li>
<li><em>likelihood</em> (<span class="math inline">\(P(Data|Hypothese)\)</span>): Hoe waarschijnlijk zijn de waargenomen Data D onder hypothese H?</li>
<li><em>marginale likelihood</em> (<span class="math inline">\(P(Data)\)</span>): Hoe waarschijnlijk zijn de waargenomen gegevens, gecombineerd over alle mogelijke hypothesen?</li>
<li><em>posterior</em> (<span class="math inline">\(P(Hypothese|Data)\)</span>): Onze bijgewerkte overtuiging over hypothese H, gegeven de data D</li>
</ul>
<p>In het geval van ons voorbeeld van de munt opgooien:</p>
<ul>
<li><em>prior</em> (<span class="math inline">\(P_{kop}\)</span>): Onze mate van overtuiging over de waarschijnlijkheid van kop gooien, die <span class="math inline">\(P_{kop}=0,5\)</span> was.</li>
<li><em>likelihood</em> (<span class="math inline">\(P\text{7 of meer koppen uit 10 worpen}|P_{kop}=0.5)\)</span>): Hoe groot is de kans op 7 of meer koppen uit 10 worpen als <span class="math inline">\(P_{kop}=0,5)\)</span>?</li>
<li><em>marginale waarschijnlijkheid</em> (<span class="math inline">\(P\text{7 of meer koppen uit 10 worpen})\)</span>): Hoe groot is de kans dat we in het algemeen 7 koppen op 10 munttesten waarnemen?</li>
<li><em>posterior</em> (<span class="math inline">\(P_{kop}|{7 of meer koppen uit 10 munt worpen})\)</span>): Onze bijgewerkte overtuiging over <span class="math inline">\(P_{kop}\)</span> gegeven de waargenomen muntworpen.</li>
</ul>
<p>Hier zien we een van de belangrijkste verschillen tussen frequentistische en Bayesiaanse statistiek. Frequentisten geloven niet in het idee van een waarschijnlijkheid van een hypothese (d.w.z. onze mate van geloof in een hypothese) – voor hen is een hypothese waar of niet. Een andere manier om dit te zeggen is dat voor de frequentist de hypothese vaststaat en de gegevens willekeurig zijn. Daarom richt frequentistische inferentie zich op het beschrijven van de waarschijnlijkheid van data gegeven een hypothese (d.w.z. de p-waarde). Bayesianen daarentegen doen graag waarschijnlijkheidsuitspraken over zowel data als hypothesen.</p>
</section>
<section id="een-bayesiaanse-schatting-doen" class="level2">
<h2 class="anchored" data-anchor-id="een-bayesiaanse-schatting-doen">Een Bayesiaanse schatting doen</h2>
<p>Uiteindelijk willen we Bayesiaanse statistiek gebruiken om beslissingen te nemen over hypothesen, maar voordat we dat doen moeten we de parameters schatten die nodig zijn om de beslissing te nemen. Hier zullen we het proces van Bayesiaanse schatting doorlopen. Laten we een ander screening voorbeeld gebruiken: Veiligheidscontrole op luchthavens. Als je veel vliegt, is het slechts een kwestie van tijd tot een van de willekeurige explosievencontroles positief uitvalt; ik had de bijzonder ongelukkige ervaring dat dit gebeurde kort na 11 september 2001, toen het luchthavenbeveiligingspersoneel bijzonder gespannen was.</p>
<section id="de-prior-specificeren" class="level3">
<h3 class="anchored" data-anchor-id="de-prior-specificeren">De prior specificeren</h3>
<p>Om het theorema van Bayes te gebruiken, moeten we eerst de prior voor de hypothese specificeren. In dit geval kennen we het reële getal niet, maar we kunnen aannemen dat het vrij klein is. Volgens de <a href="https://www.faa.gov/air_traffic/by_the_numbers/media/Air_Traffic_by_the_Numbers_2018.pdf">FAA</a> waren er in 2017 971.595.898 vliegtuigpassagiers in de VS. Laten we zeggen dat een van die reizigers een explosief in zijn tas had — dat zou een voorafgaande waarschijnlijkheid van 1 op 971 miljoen geven, wat erg klein is! Het beveiligingspersoneel kan in de maanden na de aanslag van 9/11 redelijkerwijs een sterkere waarschijnlijkheid hebben gehad, dus laten we zeggen dat hun subjectieve overtuiging was dat één op de miljoen reizigers een explosief bij zich droeg.</p>
</section>
<section id="wat-data-verzamelen" class="level3">
<h3 class="anchored" data-anchor-id="wat-data-verzamelen">Wat data verzamelen</h3>
<p>De gegevens bestaan uit de resultaten van de explosieve screeningtest. Laten we zeggen dat het beveiligingspersoneel de tas 3 keer door zijn testapparaat haalt en het geeft een positieve uitslag op 3 van de 3 tests.</p>
</section>
<section id="de-likelihood-berekenen" class="level3">
<h3 class="anchored" data-anchor-id="de-likelihood-berekenen">De likelihood berekenen</h3>
<p>We willen de waarschijnlijkheid van de gegevens berekenen onder de hypothese dat er een explosief in de zak zit. Laten we zeggen dat we weten (van de fabrikant van de machine) dat de sensititiviteit van de test 0.99 is – dat wil zeggen, wanneer een apparaat aanwezig is, zal het 99% van de tijd detecteren. Om de waarschijnlijkheid van onze gegevens te bepalen onder de hypothese dat een apparaat aanwezig is, kunnen we elke test behandelen als een Bernoulli trial (dat is een trial met een uitkomst van waar of onwaar) met een kans op succes van 0.99, die we kunnen modelleren met een binomiale verdeling.</p>
</section>
<section id="berekenen-van-de-marginale-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="berekenen-van-de-marginale-likelihood">Berekenen van de marginale likelihood</h3>
<p>We moeten ook de totale waarschijnlijkheid van de gegevens kennen – dat wil zeggen 3 positieven vinden uit 3 tests. Het berekenen van de marginale waarschijnlijkheid is vaak een van de moeilijkste aspecten van Bayesiaanse analyse, maar voor ons voorbeeld is het eenvoudig omdat we gebruik kunnen maken van de specifieke vorm van de stelling van Bayes voor een binaire uitkomst die we hebben geïntroduceerd in het vorige deel:</p>
<p>We moeten ook de totale waarschijnlijkheid van de gegevens kennen – dat wil zeggen 3 positieven vinden uit 3 tests. Het berekenen van de marginale waarschijnlijkheid is vaak een van de moeilijkste aspecten van Bayesiaanse analyse, maar voor ons voorbeeld is het eenvoudig omdat we gebruik kunnen maken van de specifieke vorm van de stelling van Bayes voor een binaire uitkomst die we eerder hebben geïntroduceerd:</p>
<p><span class="math display">\[
P(E|T) = \frac{P(T|E)*P(E)}{P(T|E)*P(E) + P(T|\neg E)*P(\neg E)}
\]</span></p>
<p>waarbij <span class="math inline">\(E\)</span> refereert naar de aanwezigheid van explosieven, en <span class="math inline">\(T\)</span> refereert naar een postief testresultaat.</p>
<p>De marginale waarschijnlijkheid is in dit geval een gewogen gemiddelde van de waarschijnlijkheid van de gegevens bij aan- of afwezigheid van het explosief, vermenigvuldigd met de waarschijnlijkheid dat het explosief aanwezig is (d.w.z. de prior). Laten we in dit geval zeggen dat we weten (van de fabrikant) dat de specificiteit van de test 0.99 is, zodat de waarschijnlijkheid van een positief resultaat wanneer er geen explosief is (<span class="math inline">\(P(T|neg E)\)</span>) 0.01 is.</p>
</section>
<section id="de-posterior-berekenen" class="level3">
<h3 class="anchored" data-anchor-id="de-posterior-berekenen">De posterior berekenen</h3>
<p>We hebben nu alle onderdelen die we nodig hebben om de posterior kans op de aanwezigheid van een explosief te berekenen, gegeven de waargenomen 3 positieve uitkomsten uit 3 testen. Dit resultaat toont ons dat de posterior kans op een explosief in de zak gegeven deze positieve tests (0.492) net onder de 50% ligt, wat nogmaals benadrukt dat het testen op zeldzame gebeurtenissen bijna altijd een groot aantal fout-positieven kan opleveren, zelfs als de specificiteit en sensitiviteit zeer hoog zijn.</p>
<p>Een belangrijk aspect van Bayesiaanse analyse is dat zij sequentieel kan zijn. Zodra we de posterior van één analyse hebben, kan deze de prior worden voor de volgende analyse!</p>
</section>
</section>
<section id="schatten-van-posterior-distributies" class="level2">
<h2 class="anchored" data-anchor-id="schatten-van-posterior-distributies">Schatten van posterior distributies</h2>
<p>In het vorige voorbeeld waren er slechts twee mogelijke uitkomsten - het explosieve is er of het is er niet - en we wilden weten welke uitkomst het meest waarschijnlijk was, gegeven de gegevens. Maar in andere gevallen willen we Bayesiaanse schattingen gebruiken om de numerieke waarde van een parameter te schatten. Laten we zeggen dat we willen weten hoe doeltreffend een nieuw pijnstiller is; om dit te testen kunnen we een groep patiënten het medicijn toedienen en hen dan vragen of hun pijn al dan niet verbeterd is na het innemen van het medicijn. We kunnen Bayesiaanse analyse gebruiken om aan de hand van deze gegevens te schatten voor welk deel van de mensen het geneesmiddel effectief zal zijn.</p>
<section id="specificeren-van-de-prior" class="level3">
<h3 class="anchored" data-anchor-id="specificeren-van-de-prior">Specificeren van de prior</h3>
<p>In dit geval hebben we geen voorafgaande informatie over de werkzaamheid van het geneesmiddel, dus gebruiken we een <em>uniforme verdeling</em> als onze prior, omdat alle waarden even waarschijnlijk zijn bij een uniforme verdeling. Om het voorbeeld te vereenvoudigen, bekijken we slechts een deelverzameling van 99 mogelijke waarden van werkzaamheid (van .01 tot .99, in stappen van .01). Daarom heeft elke mogelijke waarde een prioriteitswaarschijnlijkheid van 1/99.</p>
</section>
<section id="verzamelen-van-wat-data" class="level3">
<h3 class="anchored" data-anchor-id="verzamelen-van-wat-data">Verzamelen van wat data</h3>
<p>We hebben gegevens nodig om het effect van het geneesmiddel te schatten. Laten we zeggen dat we het middel aan 100 personen toedienen en dat we merken dat 64 positief op het middel reageren.</p>
</section>
<section id="berekenen-van-de-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="berekenen-van-de-likelihood">Berekenen van de likelihood</h3>
<p>We kunnen de waarschijnlijkheid van de waargenomen gegevens onder een bepaalde waarde van de effectiviteitsparameter berekenen met behulp van de binomiale dichtheidsfunctie. In het figuur hieronder ziet je de waarschijnlijkheidscurven over het aantal responders voor verschillende waarden van <span class="math inline">\(P_{respond}\)</span>. Hieruit blijkt dat onze waargenomen gegevens relatief waarschijnlijker zijn onder de hypothese <span class="math inline">\(P_{antwoord}=0,7\)</span>, iets minder waarschijnlijk onder de hypothese <span class="math inline">\(P_{antwoord}=0,5\)</span>, en vrij onwaarschijnlijk onder de hypothese <span class="math inline">\(P_{antwoord}=0,3\)</span>. Een van de fundamentele ideeën van Bayesiaanse inferentie is dat wij ons geloof in waarden van de parameter die voor ons van belang is, moeten verhogen in verhouding tot hoe waarschijnlijk de gegevens zijn onder die waarden, afgewogen tegen wat wij geloofden over de parameterwaarden voordat wij de gegevens zagen (onze voorkennis).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/like2-1.png" style="height:50.0%" width="384" class="figure-img"></p>
<figcaption>Figuur 5. Waarschijnlijkheid van elk mogelijk aantal responders onder verschillende hypothesen (p(respond)=0,5 (effen), 0,7 (gestippeld), 0,3 (gestreept). Waargenomen waarde weergegeven in de verticale lijn</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="berekenen-van-de-marginale-likelihood-1" class="level3">
<h3 class="anchored" data-anchor-id="berekenen-van-de-marginale-likelihood-1">Berekenen van de marginale likelihood</h3>
<p>Naast de waarschijnlijkheid van de gegevens onder verschillende hypothesen, moeten we ook de totale waarschijnlijkheid van de gegevens kennen, waarbij alle hypothesen worden gecombineerd (d.w.z. de marginale waarschijnlijkheid). Deze marginale waarschijnlijkheid is vooral belangrijk omdat zij helpt waarborgen dat de posterior waarden ware waarschijnlijkheden zijn. In dit geval maakt ons gebruik van een reeks discrete mogelijke parameterwaarden het gemakkelijk om de marginale waarschijnlijkheid te berekenen, omdat we gewoon de waarschijnlijkheid van elke parameterwaarde onder elke hypothese kunnen berekenen en ze kunnen optellen.</p>
</section>
<section id="bereken-de-posterior" class="level3">
<h3 class="anchored" data-anchor-id="bereken-de-posterior">Bereken de posterior</h3>
<p>We hebben nu alle onderdelen die we nodig hebben om de posterior kansverdeling over alle mogelijke waarden van <span class="math inline">\(p_{respond}\)</span> te berekenen, zoals hieronder weergegeven.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/posteriorDist-1.png" style="height:50.0%" width="384" class="figure-img"></p>
<figcaption>Figuur 6. Posterior kansverdeling voor de waargenomen gegevens uitgezet in ononderbroken lijn tegen uniforme prior-verdeling (stippellijn). De maximale a posteriori (MAP) waarde wordt aangegeven door het diamantensymbool.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="maximale-a-posteriori-map-schatting" class="level3">
<h3 class="anchored" data-anchor-id="maximale-a-posteriori-map-schatting">Maximale A Posteriori (MAP) schatting</h3>
<p>Gegeven onze gegevens willen we een schatting van <span class="math inline">\(p_{reageert}\)</span> voor onze steekproef. Een manier om dit te doen is het vinden van de waarde van <span class="math inline">\(p_{reageert}\)</span> waarvoor de posterior waarschijnlijkheid het hoogst is, wat we de <em>maximale a posteriori</em> (MAP) schatting noemen. We kunnen dit vinden aan de hand van de gegevens van hierboven — het is de waarde die met een marker bovenaan de verdeling staat. Merk op dat het resultaat (0.64) gewoon het percentage reageerders uit onze steekproef is – dit komt omdat de prior uniform was en dus onze schatting niet beïnvloedde.</p>
</section>
<section id="credible-intervallen-geloofwaardigheidsintervallen" class="level3">
<h3 class="anchored" data-anchor-id="credible-intervallen-geloofwaardigheidsintervallen">Credible intervallen (geloofwaardigheidsintervallen)</h3>
<p>Vaak willen we niet alleen een enkele schatting voor de posterior weten, maar een interval waarin we er zeker van zijn dat de posterior valt. Het begrip betrouwbaarheidsintervallen wordt gebruikt in de context van frequentistische inferentie en je weet wellicht dat de interpretatie van betrouwbaarheidsintervallen bijzonder ingewikkeld is: Het is een interval dat 95% van de tijd de waarde van de parameter zal bevatten. Wat we eigenlijk willen is een interval waarin we er zeker van zijn dat de ware parameter valt, en de Bayesiaanse statistiek kan ons zo’n interval geven, dat we een <em>credible interval (geloofwaardigheidsinterval)</em> noemen.</p>
<p>De interpretatie van dit geloofwaardigheidsinterval ligt veel dichter bij wat we hadden gehoopt van een betrouwbaarheidsinterval (maar niet konden krijgen): Het vertelt ons dat er 95% kans is dat de waarde van <span class="math inline">\(p_{reageert}\)</span> tussen deze twee waarden valt. Belangrijk is dat het in dit geval laat zien dat we een hoge mate van vertrouwen hebben dat <span class="math inline">\(p_{reageert} &gt; 0,0\)</span>, wat betekent dat het geneesmiddel een positief effect lijkt te hebben.</p>
<p>In sommige gevallen kan het geloofwaardigheidsinterval <em>numeriek</em> worden berekend op basis van een bekende verdeling, maar het is gebruikelijker om een geloofwaardigheidsinterval te genereren door monsters te nemen uit de posterior verdeling en dan kwantielen van de monsters te berekenen. Dit is vooral nuttig wanneer we geen gemakkelijke manier hebben om de posterior distributie numeriek uit te drukken, wat vaak het geval is bij echte Bayesiaanse gegevensanalyse. Eén zo’n methode (rejection sampling) wordt meer in detail uitgelegd in de Appendix aan het eind van dit hoofdstuk.</p>
</section>
<section id="effecten-van-verschillende-priors" class="level3">
<h3 class="anchored" data-anchor-id="effecten-van-verschillende-priors">Effecten van verschillende priors</h3>
<p>In het vorige voorbeeld gebruikten we een <em>vlakke prior</em>, wat betekent dat we geen reden hadden om aan te nemen dat een bepaalde waarde van <span class="math inline">\(p_{reageert}\)</span> meer of minder waarschijnlijk was. Maar stel dat we in plaats daarvan waren uitgegaan van eerdere gegevens: In een eerdere studie hadden onderzoekers 20 mensen getest en vastgesteld dat 10 van hen positief hadden gereageerd. Dit zou ons ertoe gebracht hebben te beginnen met de veronderstelling dat de behandeling bij 50% van de mensen effect heeft. We kunnen dezelfde berekening uitvoeren als hierboven, maar dan met de informatie uit de vorige studie als informatie voor onze prior.</p>
<p>De waarschijnlijkheid en de marginale waarschijnlijkheid zijn niet veranderd, alleen de prior. Het effect van de verandering in de prior is dat de posterior dichter bij de massa van de nieuwe prior, die gecentreerd is op 0,5, komt te liggen.</p>
<p>Laten we nu eens kijken wat er gebeurt als we naar de analyse komen met een nog sterkere prior overtuiging. Stel dat in plaats van 10 responders op 20 mensen te hebben waargenomen, de voorafgaande studie 500 mensen had getest en 250 responders had gevonden. Dit zou ons in principe een veel sterkere prior moeten geven. De prior is veel meer geconcentreerd rond 0,5, en de posterior ligt ook veel dichter bij de prior. Het algemene idee is dat Bayesiaanse inferentie de informatie van de prior en de likelihood combineert, waarbij de relatieve sterkte van elk wordt gewogen.</p>
<p>Dit voorbeeld benadrukt ook het sequentiële karakter van Bayesiaanse analyse – de posterior van de ene analyse kan de prior worden voor de volgende analyse.</p>
<p>Ten slotte is het belangrijk te beseffen dat als de prioriteiten sterk genoeg zijn, ze de gegevens volledig kunnen overweldigen. Stel dat je een absolute prioriteit hebt dat <span class="math inline">\(p_{reageert}\)</span> 0,8 of hoger is, zodat je de prior waarschijnlijkheid van alle andere waarden op nul zet. Wat gebeurt er dan als we de posterior berekenen?</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Use of `df$posteriors_absolute` is discouraged. Use
`posteriors_absolute` instead.</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/posteriorDistPrior-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>Figuur 7. A: Effecten van priors op de posterior verdeling. De oorspronkelijke posterior verdeling op basis van een vlakke prior is blauw gekleurd. De prior gebaseerd op de observatie van 10 responders op 20 personen is uitgezet in de gestippelde zwarte lijn, en de posterior met deze prioriteit is uitgezet in rood. B: Effecten van de sterkte van de prior op de posterior distributie. De blauwe lijn toont de posterior verkregen met de prior op basis van 50 reageerders op 100 personen. De gestippelde zwarte lijn toont de prior gebaseerd op 250 reageerders uit 500 observaties, en de rode lijn toont de posterior gebaseerd op die prioriteit. C: Effecten van de sterkte van de prior op de posterior verdeling. De blauwe lijn toont de posterior verkregen met een absolute prior die stelt dat p(antwoord) 0,8 of groter is. De prior is weergegeven in de gestippelde zwarte lijn.</figcaption>
</figure>
</div>
</div>
</div>
<p>In panel C van het figuur zien we dat er nul dichtheid is in de posterior voor elk van de waarden waar de prior op nul is gezet - de gegevens worden overweldigd door de absolute prior.</p>
</section>
</section>
<section id="het-kiezen-van-een-prior" class="level2">
<h2 class="anchored" data-anchor-id="het-kiezen-van-een-prior">Het kiezen van een prior</h2>
<p>Het effect van priors op de resulterende conclusies is het meest controversiële aspect van de Bayesiaanse statistiek. Wat is de juiste prior om te gebruiken? Als de keuze van de prior bepalend is voor de resultaten (d.w.z. de posterior), hoe kun je er dan zeker van zijn dat je resultaten betrouwbaar zijn? Dit zijn moeilijke vragen, maar we moeten niet terugkrabbelen omdat we met moeilijke vragen worden geconfronteerd. Zoals we eerder hebben besproken, geven Bayesiaanse analyses ons interpretabele resultaten (geloofwaardige intervallen, enz.). Dit alleen al zou ons moeten inspireren om goed over deze vragen na te denken, zodat we tot redelijke en interpreteerbare resultaten komen.</p>
<p>Er zijn verschillende manieren om prioriteiten te kiezen, die (zoals we hierboven zagen) de resulterende conclusies kunnen beïnvloeden. Soms hebben we een zeer specifieke priors, zoals in het geval waarin we verwachten dat onze munt 50% van de tijd op kop zal vallen, maar in veel gevallen hebben we niet zo’n sterk uitgangspunt. <em>Oninformatieve prioriteiten</em> proberen de resulterende posterior zo weinig mogelijk te beïnvloeden, zoals we zagen in het voorbeeld van de uniforme prior hierboven. Het is ook gebruikelijk om <em>zwak informatieve priors</em> (of <em>standaardpriors</em>) te gebruiken, die het resultaat slechts in zeer geringe mate beïnvloeden. Als we bijvoorbeeld een binomiale verdeling op basis van één kop van de twee munttoetsen hadden gebruikt, zou de prior rond 0,5 gecentreerd zijn, maar vrij vlak, en de posterior slechts licht beïnvloeden. Het is ook mogelijk priors te gebruiken die gebaseerd zijn op wetenschappelijke literatuur of reeds bestaande gegevens, die wij <em>empirische priors</em> noemen. In het algemeen zullen wij echter vasthouden aan het gebruik van niet-informatieve/zwak informatieve priors, omdat die de minste bezorgdheid wekken over de beïnvloeding van onze resultaten.</p>
</section>
<section id="bayesiaanse-hypothesetests" class="level2">
<h2 class="anchored" data-anchor-id="bayesiaanse-hypothesetests">Bayesiaanse hypothesetests</h2>
<p>Nu we geleerd hebben hoe Bayesiaanse schattingen moeten worden uitgevoerd, gaan we over tot het gebruik van Bayesiaanse methoden voor hypothesetests. Stel dat er twee politici zijn die van mening verschillen over de vraag of het publiek voorstander is van een extra belasting om de nationale parken te steunen. Senator Smith denkt dat slechts 40% van de mensen voor de belasting is, terwijl senator Jones denkt dat 60% van de mensen voor is. Om dit te testen laten zij een peiling uitvoeren, waarin 1000 willekeurig gekozen mensen wordt gevraagd of zij zo’n belasting steunen. De resultaten zijn dat 490 van de mensen in de steekproef voor de belasting zijn. Op basis van deze gegevens zouden we willen weten: Ondersteunen de gegevens de beweringen van de ene senator boven de andere, en met hoeveel? We kunnen dit testen met een concept dat bekend staat als de [Bayes factor] (https://bayesfactor.blogspot.com/2014/02/the-bayesfactor-package-this-blog-is.html), die kwantificeert welke hypothese beter is door te vergelijken hoe goed elke hypothese de waargenomen gegevens voorspelt.</p>
</section>
<section id="bayesiaanse-hypothese-test" class="level2">
<h2 class="anchored" data-anchor-id="bayesiaanse-hypothese-test">Bayesiaanse hypothese test</h2>
<p>Nu we geleerd hebben hoe Bayesiaanse schattingen moeten worden uitgevoerd, gaan we over tot het gebruik van Bayesiaanse methoden voor hypothesetoetsing. Stel dat er twee politici zijn die van mening verschillen over de vraag of het publiek voorstander is van een extra belasting om de nationale parken te steunen. Senator Smith denkt dat slechts 40% van de mensen voor de belasting is, terwijl senator Jones denkt dat 60% van de mensen voor is. Om dit te testen laten zij een peiling uitvoeren, waarin 1000 willekeurig gekozen mensen wordt gevraagd of zij zo’n belasting steunen. De resultaten zijn dat 490 van de mensen in de steekproef voor de belasting zijn. Op basis van deze gegevens zouden we willen weten: Ondersteunen de gegevens de beweringen van de ene senator boven de andere, en met hoeveel? We kunnen dit testen met een concept dat bekend staat als de [Bayes factor] (https://bayesfactor.blogspot.com/2014/02/the-bayesfactor-package-this-blog-is.html), die kwantificeert welke hypothese beter is door te vergelijken hoe goed elke hypothese de waargenomen gegevens voorspelt.</p>
<section id="bayes-factoren" class="level3">
<h3 class="anchored" data-anchor-id="bayes-factoren">Bayes factoren</h3>
<p>De Bayes-factor kenmerkt de relatieve waarschijnlijkheid van de gegevens onder twee verschillende hypothesen. Hij wordt gedefinieerd als:</p>
<p><span class="math display">\[
BF = \frac{p(data|H_1)}{p(data|H_2)}
\]</span></p>
<p>voor twee hypothesen <span class="math inline">\(H_1\)</span> en <span class="math inline">\(H_2\)</span>. In het geval van onze twee senatoren weten we hoe we de waarschijnlijkheid van de gegevens onder elke hypothese kunnen berekenen met behulp van de binomiale verdeling; laten we voorlopig aannemen dat onze prior waarschijnlijkheid dat elke senator gelijk heeft (<span class="math inline">\(P_{H_1} = P_{H_2} = 0,5\)</span>). We zetten senator Smith in de teller en senator Jones in de noemer, zodat een waarde groter dan één aangeeft dat er meer bewijs is voor senator Smith, en een waarde kleiner dan één dat er meer bewijs is voor senator Jones. De resulterende Bayes-factor (3325.2567301) geeft een maat voor het bewijs dat de gegevens leveren voor de twee hypothesen - in dit geval vertellen ze ons dat de gegevens Senator Smith meer dan 3000 keer sterker ondersteunen dan Senator Jones.</p>
</section>
<section id="bayes-factoren-voor-statistische-hypothesen" class="level3">
<h3 class="anchored" data-anchor-id="bayes-factoren-voor-statistische-hypothesen">Bayes factoren voor statistische hypothesen</h3>
<p>In het vorige voorbeeld hadden we specifieke voorspellingen van elke senator, waarvan we de waarschijnlijkheid konden kwantificeren met behulp van de binomiale verdeling. Bovendien was onze prior waarschijnlijkheid voor de twee hypothesen gelijk. Bij de analyse van reële gegevens hebben wij echter meestal te maken met onzekerheid over onze parameters, wat de factor Bayes bemoeilijkt, omdat wij de marginale waarschijnlijkheid moeten berekenen (dat wil zeggen een geïntegreerd gemiddelde van de waarschijnlijkheden over alle mogelijke modelparameters, gewogen naar hun prior waarschijnlijkheid). In ruil daarvoor krijgen wij echter de mogelijkheid om de relatieve hoeveelheid bewijsmateriaal ten gunste van de nulhypothesen versus de alternatieve hypothesen te kwantificeren.</p>
<p>Stel dat wij een medisch onderzoeker zijn die een klinische proef uitvoert voor de behandeling van diabetes en wij willen weten of een bepaald geneesmiddel de bloedglucose verlaagt in vergelijking met een placebo. Wij werven een groep vrijwilligers en wijzen hen willekeurig toe aan een van beide groepen en wij meten de verandering in hemoglobine A1C (een marker voor het bloedglucosegehalte) in elke groep gedurende de periode waarin het geneesmiddel of het placebo werd toegediend. Wat we willen weten is: Is er een verschil tussen het medicijn en de placebo?</p>
<p>Laten we eerst wat gegevens genereren en ze analyseren met behulp van nulhypothesetests. Laten we vervolgens een onafhankelijke t-test uitvoeren, waaruit blijkt dat er een significant verschil is tussen de groepen:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Stats21_files/figure-html/bayesTesting-1.png" style="height:50.0%" width="384" class="figure-img"></p>
<figcaption>Figuur 8. Box plots met gegevens voor medicijn- en placebogroepen.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  hbchange by group
t = 2.0813, df = 32.091, p-value = 0.02273
alternative hypothesis: true difference in means between group 0 and group 1 is greater than 0
95 percent confidence interval:
 0.1057051       Inf
sample estimates:
mean in group 0 mean in group 1 
    -0.08248954     -0.65013353 </code></pre>
</div>
</div>
<p>Deze test vertelt ons dat er een significant verschil is tussen de groepen, maar kwantificeert niet hoe sterk het bewijs de nulhypothese versus de alternatieve hypothese ondersteunt. Om dat te meten kunnen we een Bayes-factor berekenen met de functie <code>ttestBF</code> uit het pakket BayesFactor in R:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 0&lt;d&lt;Inf    : 3.369297 ±0%
[2] Alt., r=0.707 !(0&lt;d&lt;Inf) : 0.115034 ±0.01%

Against denominator:
  Null, mu1-mu2 = 0 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p>Wij zijn vooral geïnteresseerd in de Bayes-factor voor een effect groter dan nul. De Bayes-factor hier vertelt ons dat de alternatieve hypothese (d.w.z. dat het verschil groter is dan nul) ongeveer 3 keer waarschijnlijker is dan de nulhypothese (d.w.z. een gemiddeld verschil van precies nul), gegeven de data. Hoewel het effect dus significant is, is de hoeveelheid bewijs die het ons levert ten gunste van de alternatieve hypothese eerder zwak.</p>
<section id="een-zijde-tests" class="level4">
<h4 class="anchored" data-anchor-id="een-zijde-tests">Een zijde tests</h4>
<p>In het algemeen zijn we minder geïnteresseerd in het toetsen tegen de nulhypothese van een specifieke puntwaarde (bv. gemiddeld verschil = 0) dan in het toetsen tegen een directionele nulhypothese (bv. dat het verschil kleiner is dan of gelijk aan nul). We kunnen ook een directionele (of <em>eenzijdige</em>) test uitvoeren met de resultaten van de <code>ttestBF</code>-analyse, aangezien die twee Bayes-factoren oplevert: één voor de alternatieve hypothese dat het gemiddelde verschil groter is dan nul, en één voor de alternatieve hypothese dat het gemiddelde verschil kleiner is dan nul. Als we het relatieve bewijs voor een positief effect willen beoordelen, kunnen we een Bayes-factor berekenen die het relatieve bewijs voor een positief versus een negatief effect vergelijkt door eenvoudig de twee door de functie teruggegeven Bayes-factoren te delen:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 0&lt;d&lt;Inf : 29.28958 ±0.01%

Against denominator:
  Alternative, r = 0.707106781186548, mu =/= 0 !(0&lt;d&lt;Inf) 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p>Nu zien we dat de Bayes-factor voor een positief effect versus een negatief effect aanzienlijk groter is (bijna 30).</p>
</section>
<section id="interpreting-bayes-factors" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-bayes-factors">Interpreting Bayes Factors</h4>
<p>Hoe weten we of een Bayes-factor van 2 of 20 goed of slecht is? Er is een algemene richtlijn voor de interpretatie van Bayes-factoren voorgesteld door [Kass &amp; Rafferty (1995)] (https://www.andrew.cmu.edu/user/kk3n/simplicity/KassRaftery1995.pdf):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>BF</th>
<th>Sterkte van bewijs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1 tot 3</td>
<td>nauwelijk benoemen waard</td>
</tr>
<tr class="even">
<td>3 tot 20</td>
<td>positief</td>
</tr>
<tr class="odd">
<td>20 tot 150</td>
<td>sterk</td>
</tr>
<tr class="even">
<td>&gt;150</td>
<td>heel sterk</td>
</tr>
</tbody>
</table>
<p>Op basis hiervan is, ook al is het statistische resultaat significant, de hoeveelheid bewijs ten gunste van de alternatieve versus de punt-nulhypothese zo zwak dat het nauwelijks het vermelden waard is, terwijl het bewijs voor de richtingshypothese relatief sterk is.</p>
</section>
</section>
<section id="beoordeling-van-het-bewijs-voor-de-nulhypothese" class="level3">
<h3 class="anchored" data-anchor-id="beoordeling-van-het-bewijs-voor-de-nulhypothese">Beoordeling van het bewijs voor de nulhypothese</h3>
<p>Omdat de Bayes-factor het bewijs voor twee hypothesen vergelijkt, kunnen we ook beoordelen of er bewijs is ten gunste van de nulhypothese, wat we niet kunnen doen met standaard nulhypothesetests (omdat die uitgaan van de veronderstelling dat de nulhypothese waar is). Dit kan zeer nuttig zijn om te bepalen of een niet-significant resultaat werkelijk sterk bewijs oplevert dat er geen effect is, of in plaats daarvan slechts een algemeen zwak bewijs weergeeft.</p>
</section>
</section>
<section id="wat-hebben-we-geleerd" class="level2">
<h2 class="anchored" data-anchor-id="wat-hebben-we-geleerd">Wat hebben we geleerd</h2>
<p>Na het lezen hiervan ben je in staat om:</p>
<ul>
<li>De steekproefruimte voor een geselecteerd willekeurig experiment te beschrijven.</li>
<li>De relatieve frequentie en empirische waarschijnlijkheid voor een gegeven reeks gebeurtenissen kunnen berekenen.</li>
<li>Kansen berekenen van afzonderlijke gebeurtenissen, complementaire gebeurtenissen en de unies en intersecties van verzamelingen van gebeurtenissen.</li>
<li>De wet van de grote aantallen beschrijven.</li>
<li>Beschrijf het verschil tussen een kans en een voorwaardelijke kans.</li>
<li>Het concept van statistische onafhankelijkheid beschrijven.</li>
<li>De stelling van Bayes gebruiken om de inverse voorwaardelijke kans te berekenen.</li>
</ul>
<p>Daarnaast ben je ook in staat om:</p>
<ul>
<li>De belangrijkste verschillen tussen Bayesiaanse analyse en nulhypothesetests beschrijven;</li>
<li>De stappen in een Bayesiaanse analyse beschrijven en uitvoeren;</li>
<li>De effecten van verschillende prioriteiten en de overwegingen bij de keuze van een prioriteit beschrijven;</li>
<li>Het verschil in interpretatie tussen een betrouwbaarheidsinterval en een Bayesiaans geloofwaardigheidsinterval beschrijven.</li>
</ul>
</section>
<section id="suggesties-om-te-lezen" class="level2">
<h2 class="anchored" data-anchor-id="suggesties-om-te-lezen">Suggesties om te lezen</h2>
<ul>
<li><p><em>The Drunkard’s Walk: How Randomness Rules Our Lives</em>, van Leonard Mlodinow</p></li>
<li><p><em>Ten Great Ideas about Chance</em>, van Persi Diaconis en Brian Skyrms</p></li>
<li><p><em>The Theory That Would Not Die: How Bayes’ Rule Cracked the Enigma Code, Hunted Down Russian Submarines, and Emerged Triumphant from Two Centuries of Controversy</em>, van Sharon Bertsch McGrayne</p></li>
<li><p><em>Doing Bayesian Data Analysis: A Tutorial Introduction with R</em>, van John K. Kruschke</p></li>
</ul>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Het werkt ook met Python en Quarto maar dat kon ik niet in deze blog laten zien.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>