{
  "hash": "7acb8a3a1ee361115bcaf0b16462756a",
  "result": {
    "markdown": "---\ntitle: \"Latente Groei Modeling\"\ndescription: |\n  Dit is een blog over Latente Groei Modeling van longitudinale data van alcoholgebruik van jongeren\nauthor: \"Alexander Cernat, bewerking Harrie Jonkman\"\ndate: \"2022-01-03\"\ncategories: [analyse]\nimage: \"Screenshot1.png\"\n---\n\n\n## Schatten en visualiseren van verandering in de tijd met behulp van Latente Groeimodellen met R\n\nLongitudinale gegevens zijn zo interessant omdat ze ons in staat stellen te kijken naar verandering in de tijd, je krijgt er een beter inzicht mee in causale verbanden en je kunt gebeurtenissen en hun timing ermee verklaren. Om gebruik te maken van dit soort gegevens, moeten we verder gaan dan de klassieke statistische methoden, zoals OLS regressie en ANOVA. Dan moeten we gebruik maken van modellen die de extra complexiteit van de gegevens ook echt aan kunnen. Alexandru Cernat schreef ook [hier](https://www.alexcernat.com/estimating-and-visualizing-change-in-time-using-latent-growth-models-with-r/) een duidelijke blog over dat ik heb bewerkt en waarbij ik ook de alcoholdata van Singer en Willet heb gebruik.  \n\nEen populair model voor de analyse van longitudinale gegevens is het Latente Groei Model (Latent Growth Model, LGM). Hiermee kan de verandering in de tijd worden geschat, terwijl rekening wordt gehouden met de hiërarchische aard van de gegevens (meerdere punten in de tijd die genest zijn binnen individuen). Het is vergelijkbaar met het multilevel model van verandering, maar hier wordt de schatting gedaan met behulp van het Structural Equation Modeling (SEM)-raamwerk. Dit raamwerk maakt gebruik van gegevens in het brede formaat (elke rij is een individu en de diverse metingen in de tijd verschijnen als verschillende kolommen).\n\nMeer in het bijzonder kan het LGM helpen   \n- te begrijpen hoe verandering in de tijd verloopt;     \n- verandering verklaren met behulp van tijdvariërende en tijdconstante voorspellers;      \n- variantie ontleden in tussen- en binnenvariatie;      \n- en het model kan makkelijk worden uitgebreid naar andere analysemodellen.   \n\nHieronder volgt een korte inleiding op LGM, hoe de uitkomsten zijn te schatten en hoe de schattingen van verandering zijn te visualiseren.\n\nLaten we eerst de benodigde pakketten eens laden. We zullen `tidyverse` gebruiken voor het opschonen en visualiseren van de gegevens en `lavaan` voor het uitvoeren van de LGM in `R`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyverse' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Attaching packages --------------------------------------- tidyverse 1.3.1 --\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nv ggplot2 3.3.6     v purrr   0.3.4\nv tibble  3.1.7     v dplyr   1.0.9\nv tidyr   1.2.0     v stringr 1.4.1\nv readr   2.1.2     v forcats 0.5.1\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tibble' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dplyr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'stringr' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n-- Conflicts ------------------------------------------ tidyverse_conflicts() --\nx dplyr::filter() masks stats::filter()\nx dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(lavaan)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'lavaan' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThis is lavaan 0.6-11\nlavaan is FREE software! Please report any bugs.\n```\n:::\n:::\n\n\nLaten we, voordat we aan de LGM beginnen, eens kijken naar het soort gegevens dat we zouden willen analyseren. Hier gebruik ik alcoholdata van jongeren met de drie metingen van Singer en Willet voor die vrij toegankelijk zijn op internet.\n\nStel dat we geïnteresseerd zijn in hoe alcoholscore in de tijd verandert. Om het preciezer te formuleren willen laten zien hoe alcoholgebruik onder jongeren gemiddeld verandert, en tegelijk willen we een onderscheid maken tussen variatie, hoe jongeren veranderen ten opzichte van anderen. Maar tegelijk willen we ook iets zeggen over binnenvariatie en hoe jongeren veranderen ten opzichte van hun eigen gemiddelde/trend.\n\nLaten we eerst eens kijken hoe de gegevens eruit zien. Laten we eens kijken naar de brede gegevens, dit zijn de gegevens die gebruikt worden om LGM uit te voeren en laten we ook maar meteen het lange bestand bekijken:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalcohol1 <- read.table(\"https://stats.idre.ucla.edu/stat/r/examples/alda/data/alcohol1_pp.txt\", header=T, sep=\",\")\nattach(alcohol1)\n```\n:::\n\n\nWe beginnen met het lange formaat, waar elke rij een combinatie is van individu en tijd. Dit is het formaat dat we nodig hebben voor visualisatie met `ggplot2`, en voor andere modellen (zoals het multilevel model voor verandering).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(alcohol1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  id age coa male age_14   alcuse      peer      cpeer  ccoa\n1  1  14   1    0      0 1.732051 1.2649111  0.2469111 0.549\n2  1  15   1    0      1 2.000000 1.2649111  0.2469111 0.549\n3  1  16   1    0      2 2.000000 1.2649111  0.2469111 0.549\n4  2  14   1    1      0 0.000000 0.8944272 -0.1235728 0.549\n5  2  15   1    1      1 0.000000 0.8944272 -0.1235728 0.549\n6  2  16   1    1      2 1.000000 0.8944272 -0.1235728 0.549\n```\n:::\n:::\n\n\nOm een idee te krijgen van wat we gaan modelleren, maken we een eenvoudige grafiek met de gemiddelde verandering in de tijd en de trend voor elk individu.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(alcohol1, aes(age_14, alcuse, group = id)) + \n  geom_line(alpha = 0.1) + # add individual line with transparency\n  stat_summary( # add average line\n    aes(group = 1),\n    fun = mean,\n    geom = \"line\",\n    size = 1.5,\n    color = \"red\"\n  ) +\n  theme_bw() + # nice theme\n  labs(x = \"Leeftijd\", y = \"Alcoholgebruik\") # nice labels\n```\n\n::: {.cell-output-display}\n![](latente-groei-modeling_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nWe zien hier een gemiddelde verandering in de tijd. Tegelijk willen we ook zichtbaar maken wat variatie is in de manier waarop mensen veranderen. LGM is in staat beide tegelijk te schatten!\n\n## Wat is Latente Groei Modellering?\nNu we een idee hebben van de gegevens en het soort onderzoeksvragen dat we zouden kunnen hebben, kunnen we overgaan tot de uitvoering van LGM. De formule voor het LGM is eigenlijk zeer gelijkaardig aan die voor het multilevel model van verandering:\n\n$Y_j=\\alpha_0 + \\alpha_1*\\gamma_j + \\zeta_{00} + \\zeta_{11}*\\gamma_j + \\epsilon_j$\n\nWaarbij:\n\n- $Y_j$ is de variabele van belang (`alcuse`, alchoholgebruik van jongeren) die verandert in tijd, j.    \n- $\\alpha_0$ is de gemiddelde waarde bij het begin van de gegevensverzameling (het beginpunt van de rode lijn hierboven).   \n- $\\alpha_1*\\gamma_j$ is de gemiddelde snelheid van verandering in de tijd (de helling van de rode lijn in de grafiek hierboven). Hier is $gamma_j$ gewoon een maat voor de tijd.   \n- $\\zeta_{00}$ is de **tussenvariatie** aan het begin van de gegevens. Het vat samen hoe verschillend de individuele startpunten zijn ten opzichte van het gemiddelde startpunt.    \n- $\\zeta_{11}\\gamma_j$ is de **tussen variatie in de snelheid van verandering**. Samenvattend hoe verschillend de individuele veranderingsversnellingen zijn ten opzichte van de gemiddelde verandering (rode lijn hierboven).   \n- De $\\epsilon_j$ is de **binnenvariatie** of hoeveel individuen variëren rond hun voorspelde trend.\nMet de onderstaande grafiek kunnen we een beter idee krijgen van de verschillende variatiebronnen:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalcohol1 %>% \n  filter(id %in% 1:2) %>% # selecteer twee individuen\n  ggplot(aes(age_14, alcuse, color = id)) +\n  geom_point() + # punten voor VeerkrachtTotaal\n  geom_smooth(method = lm, se = FALSE) + # liniaire lijn\n  theme_bw() + # mooi thema\n  labs(x = \"Leeftijd\", y = \"Alcoholgebruik\") # nice labels\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`geom_smooth()` using formula 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](latente-groei-modeling_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\nDe interne variatie wordt weergegeven door de afstand tussen de lijn en de punten. Dit wordt voor elk individu afzonderlijk gedaan (door de kleur in de grafiek). De tussenvariatie verwijst naar hoe verschillend de lijnen zijn. Dit kan zowel het beginpunt als de helling zijn.\n\nOmdat deze techniek met brede databestanden werkt, zetten we de data over van lang naar wijd\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nlibrary(dplyr)\n\nalcwide<-alcohol1 %>%\n  select(id, alcuse, age_14) %>%\n  pivot_wider(names_from = age_14, \n              values_from = alcuse) %>%\n  rename(\n    \"age_14\"=\"0\",\n    \"age_15\"=\"1\",         \n    \"age_16\"=\"2\"\n    )\n```\n:::\n\n\n\n```\n i =~ 1*Meting.0 +  1*Meting.1 +  1*Meting.2 \n  s =~ 0*Meting.0 +  1*Meting.1 +  2*Meting.2 \n  i ~~ s\n```\n\nStructural Equation Modeling heeft zijn eigen manier om deze statistische relaties weer te geven. Hieronder is afgebeeld hoe we ons het hierboven beschreven model zouden moeten voorstellen:\n\n\n![**Fig.1**, LGM grafisch verbeeld](Screenshot1.png)\n\nIn de figuur worden de latente variabelen voorgesteld door cirkels (de twee $\\eta$-variabelen, intercept en slope), terwijl de waargenomen variabelen worden voorgesteld door vierkanten (de vier y-variabelen). Wij krijgen ook de residuen (kleine cirkels die $\\epsilon$ voorstellen). Voor de latente variabelen hebben wij gemiddelden ($\\alpha$) en varianties ($\\zeta$). Deze zijn geschat en hebben de hierboven beschreven interpretatie. De pijlen tussen de latente en de geobserveerde variabelen (die gewoon regressiehellingen of ladingen zijn) liggen van tevoren vast. Voor de latente interceptvariabele (weergegeven door $\\eta_0$) zijn de ladingen vastgesteld op 1 (daarom is er in bovenstaande formule niets vermenigvuldigd met $\\alpha_0$ en $\\eta_{00}$). De ladingen voor de hellende latente variabele (weergegeven door $\\eta_1$) worden vastgesteld naar gelang van de verandering in tijd ($\\gamma_j$ in bovenstaande formule). In dit geval gaat het eenvoudig van 0 naar 2. Er is ook een correlatie tussen het beginpunt en de verandering in tijd, weergegeven door de dubbele pijl $\\zeta_{01}$. Dit wordt niet vaak geïnterpreteerd, maar het geeft je in feite een idee of mensen convergeren (of meer op elkaar gaan lijken in de tijd) of divergeren (meer van elkaar gaan verschillen).\n\nNu het technische deel duidelijk is gemaakt, kunnen we wat modelleren en meer grafieken maken!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# first LGM \nmodel <- 'i =~ 1*age_14 + 1*age_15 + 1*age_16\n          s =~ 0*age_14 + 1*age_15 + 2*age_16 '\n                  \n\nfit1 <- growth(model, data = alcwide)\n\nsummary(fit1, standardized = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlavaan 0.6-11 ended normally after 22 iterations\n\n  Estimator                                         ML\n  Optimization method                           NLMINB\n  Number of model parameters                         8\n                                                      \n  Number of observations                            82\n                                                      \nModel Test User Model:\n                                                      \n  Test statistic                                 0.636\n  Degrees of freedom                                 1\n  P-value (Chi-square)                           0.425\n\nParameter Estimates:\n\n  Standard errors                             Standard\n  Information                                 Expected\n  Information saturated (h1) model          Structured\n\nLatent Variables:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  i =~                                                                  \n    age_14            1.000                               0.898    0.963\n    age_15            1.000                               0.898    0.862\n    age_16            1.000                               0.898    0.796\n  s =~                                                                  \n    age_14            0.000                               0.000    0.000\n    age_15            1.000                               0.484    0.464\n    age_16            2.000                               0.967    0.857\n\nCovariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n  i ~~                                                                  \n    s                -0.187    0.102   -1.841    0.066   -0.431   -0.431\n\nIntercepts:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .age_14            0.000                               0.000    0.000\n   .age_15            0.000                               0.000    0.000\n   .age_16            0.000                               0.000    0.000\n    i                 0.634    0.103    6.163    0.000    0.706    0.706\n    s                 0.277    0.062    4.481    0.000    0.573    0.573\n\nVariances:\n                   Estimate  Std.Err  z-value  P(>|z|)   Std.lv  Std.all\n   .age_14            0.064    0.147    0.436    0.663    0.064    0.073\n   .age_15            0.420    0.094    4.463    0.000    0.420    0.387\n   .age_16            0.280    0.180    1.556    0.120    0.280    0.220\n    i                 0.807    0.193    4.177    0.000    1.000    1.000\n    s                 0.234    0.083    2.803    0.005    1.000    1.000\n```\n:::\n:::\n\n\nEr zijn in principe zes soorten coëfficiënten die hier interessant zijn:\n\n- **intercept i**: de waarde 0.634 staat voor de gemiddelde verwachte alcoholgebruik aan het begin van het onderzoek voor alle respondenten wanneer ze 14 jaar zijn.   \n- **slope s**: de waarde 0.277 vertegenwoordigt de gemiddelde verandering voor alle respondenten. Dus bij elke meting stijgt het gebruik van alcohol met met 0.277.   \n- **variantie i**: de waarde 0.807 vertegenwoordigt de tussenvariatie aan het begin van het onderzoek. Dus hoe verschillend zijn mensen vergeleken met het gemiddelde.   \n- **variantie s**: de waarde 0.234 staat voor de tussenvariatie in de veranderingssnelheid. Het laat zien hoe verschillend veranderingshellingen zijn voor verschillende mensen.   \n- **Variantie alcoholgebruik**: de waarden tussen 0.064 en 0.420 geven de interne variatie op elk punt in de tijd weer.   \n- **correlatie tussen i en s**: de waarde -0.187 laat zien dat het alcohol niet in de tijd convergeert (althans niet significant).\n\n### Hoe kunnen we de verandering visualiseren?\nEen goede manier om te begrijpen wat je modelleert, is de voorspelde scores van het model visualiseren. We zullen het `predict()` commando gebruiken om een nieuw object op te slaan met de voorspelde scores op individueel niveau voor het intercept en de helling.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# voorspellen van twee latente variabelen\npred_lgm <- predict(fit1) \n```\n:::\n\n\nDit heeft de voorspelde score voor het intercept en de helling voor elk individu:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(pred_lgm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              i          s\n[1,] 1.67339200 0.15061147\n[2,] 0.01577357 0.41987762\n[3,] 1.03717373 0.89157072\n[4,] 0.15472328 0.80763226\n[5,] 0.01182452 0.09588422\n[6,] 2.85697940 0.05794456\n```\n:::\n:::\n\n\nDeze zijn gebaseerd op ons model. Wij zouden dus bijvoorbeeld het gemiddelde van deze variabelen kunnen schatten en dat gemiddelde voor intercept en slope zou achtereenvolgens dezelfde resultaten moeten geven als hierboven:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gemiddelde van het intercept (eerste kolom)\nmean(pred_lgm[, 1]) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.634417\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# gemiddelde slope (tweede kolom)\nmean(pred_lgm[, 2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2773233\n```\n:::\n:::\n\n\nOm de resultaten te plotten, willen wij deze gegevens (intercept ($\\zeta_0$) en helling ($\\zeta_1$)) omzetten in verwachte scores bij elke meting ($\\gamma_j$j). We kunnen deze transformatie doen op basis van het padmodel dat we hierboven hebben gezien:\n\n$Y_1=\\eta_0 + \\eta_1\\gamma_j$\n\nVoor de eerste meting (time=0) is de verwachte waarde dus alleen het intercept ($\\eta_0$) omdat $\\gamma_j$ gelijk is aan 0. Voor de meting zou de verwachte waarde het intercept ($\\eta_0$) en de helling ($\\eta_1$) zijn. Voor meting drie zou het intercept + 2*helling zijn, enzovoort.\n\nIn `R` zouden we al deze metingen met de hand kunnen berekenen of we zouden het automatisch kunnen doen met behulp van functioneel programmeren. Op basis van de bovenstaande formule kunnen we een tegenhanger in `R` maken:\n\n```\npred_lgm[, 1] + x*pred_lgm[, 2]\n``` \nVoor de eerste meting (alc_14=0) krijgen we deze scores\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_lgm[, 1] + 0*pred_lgm[, 2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 1.67339200 0.01577357 1.03717373 0.15472328 0.01182452 2.85697940\n [7] 1.70002148 0.01182452 0.09353383 0.95999586 0.02431252 0.89485737\n[13] 0.01972262 2.74652531 1.69122663 0.98981031 0.07985392 1.88598973\n[19] 0.01182452 3.16706021 1.01268775 2.68643747 0.96288677 0.07985392\n[25] 2.71888080 0.08543872 2.64724315 0.01182452 0.01577357 1.03091617\n[31] 1.77626546 1.62959225 0.08543872 0.08380297 0.95604681 0.96394491\n[37] 1.09292161 0.13755300 0.01182452 0.01182452 1.25884647 0.01182452\n[43] 0.01182452 0.11987977 2.13501694 0.01740932 0.07985392 0.01182452\n[49] 0.01182452 0.01182452 0.01182452 0.07985392 0.01182452 0.01577357\n[55] 0.01182452 0.11848083 0.01182452 0.99389867 0.02227273 0.08543872\n[61] 1.92422677 0.01182452 0.01182452 0.15671367 0.08543872 1.49845628\n[67] 0.88801741 0.07985392 0.01182452 1.83223971 0.01182452 0.01182452\n[73] 0.01182452 0.13848524 0.01182452 0.01182452 0.11920222 0.01182452\n[79] 1.04572058 0.96288677 0.01182452 0.11198167\n```\n:::\n:::\n\n\nVoor de tweede meting (alc_14=1) ziet het er zo uit\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_lgm[, 1] + 1*pred_lgm[, 2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 1.8240035 0.4356512 1.9287445 0.9623555 0.1077087 2.9149240 1.5604805\n [8] 0.1077087 1.3870516 1.0257079 1.1447539 1.1224615 0.7635937 2.8155774\n[15] 2.0052428 1.2209099 0.2510256 1.5773629 0.1077087 2.4340560 1.3706937\n[22] 2.1045835 1.2657784 0.2510256 2.4588992 0.7148063 2.0159411 0.1077087\n[29] 0.4356512 1.4090953 2.3055104 1.4121079 0.7148063 0.5789681 0.6977654\n[36] 1.3536504 1.9968551 1.0118258 0.1077087 0.1077087 1.3953791 0.1077087\n[43] 0.1077087 1.2942168 2.4109430 0.5714894 0.2510256 0.1077087 0.1077087\n[50] 0.1077087 0.1077087 0.2510256 0.1077087 0.4356512 0.1077087 1.1780436\n[57] 0.1077087 1.5604210 0.9753629 0.7148063 1.9775396 0.1077087 0.1077087\n[64] 1.1276442 0.7148063 2.2197859 0.5544485 0.2510256 0.1077087 1.1445052\n[71] 0.1077087 0.1077087 0.1077087 1.0892425 0.1077087 0.1077087 1.2379508\n[78] 0.1077087 1.3386955 1.2657784 0.1077087 0.6383319\n```\n:::\n:::\n\n\nBij de derde meting ziet het alcoholgebruik er zo uit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_lgm[, 1] + 2*pred_lgm[, 2]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 1.9746149 0.8555288 2.8203152 1.7699878 0.2035930 2.9728685 1.4209395\n [8] 0.2035930 2.6805694 1.0914199 2.2651952 1.3500657 1.5074647 2.8846296\n[15] 2.3192590 1.4520095 0.4221974 1.2687361 0.2035930 1.7010517 1.7286996\n[22] 1.5227296 1.5686701 0.4221974 2.1989176 1.3441739 1.3846391 0.2035930\n[29] 0.8555288 1.7872745 2.8347553 1.1946236 1.3441739 1.0741332 0.4394841\n[36] 1.7433558 2.9007885 1.8860986 0.2035930 0.2035930 1.5319118 0.2035930\n[43] 0.2035930 2.4685539 2.6868691 1.1255695 0.4221974 0.2035930 0.2035930\n[50] 0.2035930 0.2035930 0.4221974 0.2035930 0.8555288 0.2035930 2.2376064\n[57] 0.2035930 2.1269432 1.9284531 1.3441739 2.0308524 0.2035930 0.2035930\n[64] 2.0985747 1.3441739 2.9411155 0.2208797 0.4221974 0.2035930 0.4567708\n[71] 0.2035930 0.2035930 0.2035930 2.0399998 0.2035930 0.2035930 2.3566993\n[78] 0.2035930 1.6316705 1.5686701 0.2035930 1.1646821\n```\n:::\n:::\n\n\nwaarbij `x` onze codering van tijd voorstelt (of $\\gamma_j$). We kunnen deze functie meerdere keren toepassen met het `map()` commando. De onderstaande syntaxis past deze formule toe voor de getallen 0, 1, 2 (onze codering van meting (variabele `alc_14`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap(0:2, # loop over, in ons geval 1,2,3\n    function(x) pred_lgm[, 1] + x * pred_lgm[, 2]) # formule die gebruikt wordt\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[1]]\n [1] 1.67339200 0.01577357 1.03717373 0.15472328 0.01182452 2.85697940\n [7] 1.70002148 0.01182452 0.09353383 0.95999586 0.02431252 0.89485737\n[13] 0.01972262 2.74652531 1.69122663 0.98981031 0.07985392 1.88598973\n[19] 0.01182452 3.16706021 1.01268775 2.68643747 0.96288677 0.07985392\n[25] 2.71888080 0.08543872 2.64724315 0.01182452 0.01577357 1.03091617\n[31] 1.77626546 1.62959225 0.08543872 0.08380297 0.95604681 0.96394491\n[37] 1.09292161 0.13755300 0.01182452 0.01182452 1.25884647 0.01182452\n[43] 0.01182452 0.11987977 2.13501694 0.01740932 0.07985392 0.01182452\n[49] 0.01182452 0.01182452 0.01182452 0.07985392 0.01182452 0.01577357\n[55] 0.01182452 0.11848083 0.01182452 0.99389867 0.02227273 0.08543872\n[61] 1.92422677 0.01182452 0.01182452 0.15671367 0.08543872 1.49845628\n[67] 0.88801741 0.07985392 0.01182452 1.83223971 0.01182452 0.01182452\n[73] 0.01182452 0.13848524 0.01182452 0.01182452 0.11920222 0.01182452\n[79] 1.04572058 0.96288677 0.01182452 0.11198167\n\n[[2]]\n [1] 1.8240035 0.4356512 1.9287445 0.9623555 0.1077087 2.9149240 1.5604805\n [8] 0.1077087 1.3870516 1.0257079 1.1447539 1.1224615 0.7635937 2.8155774\n[15] 2.0052428 1.2209099 0.2510256 1.5773629 0.1077087 2.4340560 1.3706937\n[22] 2.1045835 1.2657784 0.2510256 2.4588992 0.7148063 2.0159411 0.1077087\n[29] 0.4356512 1.4090953 2.3055104 1.4121079 0.7148063 0.5789681 0.6977654\n[36] 1.3536504 1.9968551 1.0118258 0.1077087 0.1077087 1.3953791 0.1077087\n[43] 0.1077087 1.2942168 2.4109430 0.5714894 0.2510256 0.1077087 0.1077087\n[50] 0.1077087 0.1077087 0.2510256 0.1077087 0.4356512 0.1077087 1.1780436\n[57] 0.1077087 1.5604210 0.9753629 0.7148063 1.9775396 0.1077087 0.1077087\n[64] 1.1276442 0.7148063 2.2197859 0.5544485 0.2510256 0.1077087 1.1445052\n[71] 0.1077087 0.1077087 0.1077087 1.0892425 0.1077087 0.1077087 1.2379508\n[78] 0.1077087 1.3386955 1.2657784 0.1077087 0.6383319\n\n[[3]]\n [1] 1.9746149 0.8555288 2.8203152 1.7699878 0.2035930 2.9728685 1.4209395\n [8] 0.2035930 2.6805694 1.0914199 2.2651952 1.3500657 1.5074647 2.8846296\n[15] 2.3192590 1.4520095 0.4221974 1.2687361 0.2035930 1.7010517 1.7286996\n[22] 1.5227296 1.5686701 0.4221974 2.1989176 1.3441739 1.3846391 0.2035930\n[29] 0.8555288 1.7872745 2.8347553 1.1946236 1.3441739 1.0741332 0.4394841\n[36] 1.7433558 2.9007885 1.8860986 0.2035930 0.2035930 1.5319118 0.2035930\n[43] 0.2035930 2.4685539 2.6868691 1.1255695 0.4221974 0.2035930 0.2035930\n[50] 0.2035930 0.2035930 0.4221974 0.2035930 0.8555288 0.2035930 2.2376064\n[57] 0.2035930 2.1269432 1.9284531 1.3441739 2.0308524 0.2035930 0.2035930\n[64] 2.0985747 1.3441739 2.9411155 0.2208797 0.4221974 0.2035930 0.4567708\n[71] 0.2035930 0.2035930 0.2035930 2.0399998 0.2035930 0.2035930 2.3566993\n[78] 0.2035930 1.6316705 1.5686701 0.2035930 1.1646821\n```\n:::\n:::\n\n\n\n### Conclusies\nHopelijk geeft dit je een idee over wat LGM is, hoe je het kan schatten in `R` en hoe je deze verandering kan visualiseren. \n\n[Met dank aan Alexandru Cernat}(https://www.alexcernat.com/estimating-and-visualizing-change-in-time-using-latent-growth-models-with-r/)",
    "supporting": [
      "latente-groei-modeling_files\\figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": null
  }
}